/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.34
 * Generated at: 2026-01-17 11:46:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.mysql.cj.x.protobuf.MysqlxPrepare.Prepare;
import java.sql.*;
import java.sql.*;

public final class customerRegistration_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/DBconnection.jsp", Long.valueOf(1768386619785L));
    _jspx_dependants.put("/sessionManager.jsp", Long.valueOf(1768386620471L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.mysql.cj.x.protobuf.MysqlxPrepare.Prepare");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");

String dbUser = (String) session.getAttribute("id");
String jdbcDriver = (String) session.getAttribute("dbName");
String dbPwd = (String) session.getAttribute("password");

if (dbUser == null || jdbcDriver == null || dbPwd == null) {
    response.sendRedirect("login.jsp");
    return;
}

Connection conn = null;

try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    conn = DriverManager.getConnection(jdbcDriver, dbUser, dbPwd);
} catch (Exception e) {
    e.printStackTrace();
}

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

String dbName = (session != null) ? (String) session.getAttribute("dbName") : null;
String id = (session != null) ? (String) session.getAttribute("id") : null;
String password = (session != null) ? (String) session.getAttribute("password") : null;

/* out.println(password);
out.println(dbName);
out.println(id);
out.println(password); */

String idSortation = (session != null) ? (String) session.getAttribute("idSortation") : null; if (id == null || dbName == null) {
    response.sendRedirect("login.jsp");
    return;
}

jdbcDriver = dbName;

String selectSQL = "select (max(customerNumber) + 1) AS custNum from members";
PreparedStatement pstmt = conn.prepareStatement(selectSQL);
ResultSet res = pstmt.executeQuery();
res.next();
String custNum = res.getString("custNum");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("<style>\r\n");
      out.write("	#wrap{\r\n");
      out.write("		font-size:25px;\r\n");
      out.write("	}\r\n");
      out.write("	#wrap h1{\r\n");
      out.write("		width: 100%;\r\n");
      out.write("    	height: 10px;\r\n");
      out.write("    	text-align: center;\r\n");
      out.write("   	    transform: translateY(50px);\r\n");
      out.write("    }\r\n");
      out.write("    #wrap .Warning,\r\n");
      out.write("    #wrap hr{\r\n");
      out.write("   	    display: block;\r\n");
      out.write("	    width: 60vh;\r\n");
      out.write("	    margin: 10px auto;\r\n");
      out.write("	    text-align: right;\r\n");
      out.write("	    transform: translateY(130px);\r\n");
      out.write("    }\r\n");
      out.write("    #wrap #section, #wrap #updatesection{\r\n");
      out.write("    	display: block;\r\n");
      out.write("	    width: 60vh;\r\n");
      out.write("	    height: 50vh;\r\n");
      out.write("	    margin: 0 auto;\r\n");
      out.write("	    transform: translateY(140px);\r\n");
      out.write("    }\r\n");
      out.write("    #wrap #section input[type=\"text\"],\r\n");
      out.write("    #wrap #updatesection input[type=\"text\"]{\r\n");
      out.write("    	width: 200px;\r\n");
      out.write("	    height: 50px;\r\n");
      out.write("	    border: 1px dashed;\r\n");
      out.write("	    border-radius: 10px;\r\n");
      out.write("	    width:75%;\r\n");
      out.write("    }\r\n");
      out.write("    #wrap #section .lineSorting,\r\n");
      out.write("    #wrap #updatesection .lineSorting{\r\n");
      out.write("        display: flex;\r\n");
      out.write("	    align-items: center; /* 수직 정렬 */\r\n");
      out.write("	    justify-content: space-between;\r\n");
      out.write("    	margin:30px 0;\r\n");
      out.write("    }\r\n");
      out.write("    .essential{\r\n");
      out.write("    	color:red;\r\n");
      out.write("    }\r\n");
      out.write("    .checkbox-container {\r\n");
      out.write("    	display: flex;\r\n");
      out.write("   		gap: 10px;\r\n");
      out.write("	}\r\n");
      out.write("	#wrap #section .lingSorting .membership,\r\n");
      out.write("	#wrap #updatesection .lingSorting .membership{\r\n");
      out.write("	    position: absolute;\r\n");
      out.write("	    left: 50%;\r\n");
      out.write("	    transform: translateX(-50%);\r\n");
      out.write("	    width: 150px;\r\n");
      out.write("	    height: 50px;\r\n");
      out.write("	    font-size: 20px;\r\n");
      out.write("	    border-radius: 10px;\r\n");
      out.write("	}\r\n");
      out.write("	#wrap .registrationUI,\r\n");
      out.write("	#wrap .updateUI{\r\n");
      out.write("		flex:1;\r\n");
      out.write("		text-align:center;\r\n");
      out.write("		border:1px;\r\n");
      out.write("	}\r\n");
      out.write("	#wrap .registrationUI{\r\n");
      out.write("		border: 1px solid;\r\n");
      out.write("	    border-radius: 20px 0 0 20px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#wrap .updateUI{\r\n");
      out.write("		border: 1px solid;\r\n");
      out.write("	    border-radius: 0 20px 20px 0;\r\n");
      out.write("	}\r\n");
      out.write("	.selectUi{\r\n");
      out.write("		border: 1px solid #4682B4;\r\n");
      out.write("    	background: #e0ffff;\r\n");
      out.write("    	color: #483D8B;\r\n");
      out.write("    	font-weight: bold;\r\n");
      out.write("	}\r\n");
      out.write("	.closePopup{\r\n");
      out.write("	    position: absolute;\r\n");
      out.write("	    left: 95%;\r\n");
      out.write("	    top: 5%;\r\n");
      out.write("	}\r\n");
      out.write("	.overDetail{\r\n");
      out.write("	    background-color: #FAFAD2;\r\n");
      out.write("	    color: #000080;\r\n");
      out.write("	    font-weight: bold;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"wrap\" style=\"display: block;\">\r\n");
      out.write("		<header>\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("		</header>\r\n");
      out.write("		<div style=\"display: flex;position: relative;left: 20%;top: 10vh;width: 200px;height: 40px;line-height: 40px;border: 1px solid black;border-radius: 20px;cursor:pointer;\">\r\n");
      out.write("			<span class=\"registrationUI\">등록[F2]</span>\r\n");
      out.write("			<span class=\"updateUI selectUi\">수정[F4]</span>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"dataInsert\"  style=\"display:none;\">\r\n");
      out.write("			<h1>고객등록</h1>\r\n");
      out.write("			<div class=\"Warning\"><span class=\"essential\">&nbsp;*&nbsp;</span>필수 요소</div>\r\n");
      out.write("			<hr>\r\n");
      out.write("			<section id=\"section\">\r\n");
      out.write("				<div class=\"lineSorting\">\r\n");
      out.write("					<span class=\"name\"><span class=\"essential\">&nbsp;*&nbsp;</span>성함</span>\r\n");
      out.write("						&nbsp;&nbsp;<input type=\"text\" class=\"memberName\" placeholder=\"&nbsp;Name\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"lineSorting\">\r\n");
      out.write("					<span class=\"name\"><span class=\"essential\">&nbsp;*&nbsp;</span>전화번호</span>\r\n");
      out.write("						&nbsp;&nbsp;<input type=\"text\" class=\"memberphone\" placeholder=\"phoneNumber [- 없이 입력]\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"lineSorting\">\r\n");
      out.write("					<span class=\"name\"><span class=\"essential\">&nbsp;&nbsp;&nbsp;</span>주민등록번호</span>\r\n");
      out.write("						<input type=\"text\" class=\"jumin1\" placeholder=\"주민등록번호 앞 6자리\" style=\"width:35%;\">\r\n");
      out.write("						<span>-</span>\r\n");
      out.write("						<input type=\"text\" class=\"jumin2\" placeholder=\"주민등록번호 뒤 7자리\" style=\"width:35%;\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"lineSorting\">\r\n");
      out.write("					<span class=\"name\"><span class=\"essential\">&nbsp;*&nbsp;</span>성별</span>\r\n");
      out.write("					<div class=\"checkbox-container\">\r\n");
      out.write("        			    <label><input type=\"radio\" name=\"1\" value=\"1\" checked> 남자</label>\r\n");
      out.write("        			    <label><input type=\"radio\" name=\"1\" value=\"2\"> 여자</label>\r\n");
      out.write("        			</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"lineSorting\">\r\n");
      out.write("					<span class=\"name\"><span class=\"essential\">&nbsp;&nbsp;&nbsp;</span>고객번호</span>\r\n");
      out.write("       			    <input type=\"text\" placeholder=\"절대 수정하지 마시오\" readonly=\"readonly\" value=\"");
      out.print( custNum);
      out.write("\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"lingSorting\">\r\n");
      out.write("					<button class=\"membership\">고객 등록</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</section>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"dataUpdate\">\r\n");
      out.write("			<h1>고객수정</h1>\r\n");
      out.write("			<div class=\"Warning\"><span class=\"essential\">&nbsp;*&nbsp;</span>필수 요소</div>\r\n");
      out.write("			<hr>\r\n");
      out.write("			<section id=\"updatesection\">\r\n");
      out.write("				<div class=\"lineSorting\">\r\n");
      out.write("					<span class=\"name\"><span class=\"essential\">&nbsp;*&nbsp;</span>성함</span>\r\n");
      out.write("							&nbsp;&nbsp;<input type=\"text\" class=\"memberName\" placeholder=\"&nbsp;Name\">\r\n");
      out.write("			</div>\r\n");
      out.write("				<div class=\"lineSorting\">\r\n");
      out.write("					<span class=\"name\"><span class=\"essential\">&nbsp;*&nbsp;</span>전화번호</span>\r\n");
      out.write("						&nbsp;&nbsp;<input type=\"text\" class=\"memberphone\" placeholder=\"phoneNumber [- 없이 입력]\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"lineSorting\">\r\n");
      out.write("					<span class=\"name\"><span class=\"essential\">&nbsp;&nbsp;&nbsp;</span>주민등록번호</span>\r\n");
      out.write("						<input type=\"text\" class=\"jumin1\" placeholder=\"주민등록번호 앞 6자리\" style=\"width:35%;\">\r\n");
      out.write("						<span>-</span>\r\n");
      out.write("						<input type=\"text\" class=\"jumin2\" placeholder=\"주민등록번호 뒤 7자리\" style=\"width:35%;\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"lineSorting\">\r\n");
      out.write("					<span class=\"name\"><span class=\"essential\">&nbsp;*&nbsp;</span>성별</span>\r\n");
      out.write("					<div class=\"checkbox-container\">\r\n");
      out.write("        			    <label><input type=\"radio\" name=\"1\" value=\"1\" checked> 남자</label>\r\n");
      out.write("        			    <label><input type=\"radio\" name=\"1\" value=\"2\"> 여자</label>\r\n");
      out.write("        			</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"lineSorting\">\r\n");
      out.write("					<span class=\"name\"><span class=\"essential\">&nbsp;&nbsp;&nbsp;</span>고객번호</span>\r\n");
      out.write("       			    <input type=\"text\" class=\"custnumber\" placeholder=\"절대 수정하지 마시오\" readonly=\"readonly\" value=\"");
      out.print( custNum);
      out.write("\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"lingSorting\">\r\n");
      out.write("					<button class=\"membership\">고객 수정</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</section>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"popup\" style=\"width: 85vh;height: 50vh;display:none; position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%); padding: 20px; background-color: white; border: 1px solid #ccc; border-radius: 5px;    box-shadow: 0px 0px 30px 0px;z-index:100;\">\r\n");
      out.write("	   	<div id=\"popupContent\"></div>\r\n");
      out.write("	   	<button class=\"closePopup\">닫기</button>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<script src=\"jquery-3.7.1.min.js\"></script><script src=\"script.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		$(document).ready(function(){\r\n");
      out.write("			$(\"#popup #popupContent\").on(\"mouseover\", \" .table_line tbody tr\", function(){\r\n");
      out.write("				$(this).addClass(\"overDetail\");\r\n");
      out.write("			}).on(\"mouseout\", \"tr\", function(){\r\n");
      out.write("				$(this).removeClass(\"overDetail\");\r\n");
      out.write("			});\r\n");
      out.write("			// 등록 유효성 검사\r\n");
      out.write("			$(\"#wrap #section .lingSorting .membership\").on(\"click\", function() {\r\n");
      out.write("				var Sortation = \"1\";\r\n");
      out.write("			    var findVal = $(\"#wrap #section .lineSorting\");\r\n");
      out.write("\r\n");
      out.write("			    // 유효성 검사\r\n");
      out.write("			    if (findVal.find(\".memberName\").val() == \"\" || findVal.find(\".memberName\").val() == null) {\r\n");
      out.write("			        alert(\"성함을 입력해주세요\");\r\n");
      out.write("			        findVal.find(\".memberName\").focus();\r\n");
      out.write("			        return false;\r\n");
      out.write("			    }\r\n");
      out.write("			    if (findVal.find(\".memberphone\").val() == \"\" || findVal.find(\".memberphone\").val() == null) {\r\n");
      out.write("			        alert(\"전화번호 입력해주세요\");\r\n");
      out.write("			        findVal.find(\".memberphone\").focus();\r\n");
      out.write("			        return false;\r\n");
      out.write("			    }\r\n");
      out.write("			    if (!findVal.find(\"input[name='1']:checked\").val()) {\r\n");
      out.write("			        alert(\"성별을 선택해주세요\");\r\n");
      out.write("			        return false;\r\n");
      out.write("			    }\r\n");
      out.write("\r\n");
      out.write("			    // 입력값 가져오기\r\n");
      out.write("			    var memberName = findVal.find(\".memberName\").val();\r\n");
      out.write("			    var memberPhone = findVal.find(\".memberphone\").val();\r\n");
      out.write("			    var jumin1 = findVal.find(\".jumin1\").val();\r\n");
      out.write("			    var jumin2 = findVal.find(\".jumin2\").val();\r\n");
      out.write("			    var gender = findVal.find(\"input[name='1']:checked\").val();\r\n");
      out.write("			    var customerNumber = findVal.find(\"input[readonly]\").val();\r\n");
      out.write("\r\n");
      out.write("			    // AJAX 요청 보내기\r\n");
      out.write("			    $.ajax({\r\n");
      out.write("			        url: 'registerMember.jsp',\r\n");
      out.write("			        type: 'POST',\r\n");
      out.write("			        data: {\r\n");
      out.write("			            Sortation: Sortation,\r\n");
      out.write("			            memberName: memberName,\r\n");
      out.write("			            memberPhone: memberPhone,\r\n");
      out.write("			            jumin1: jumin1,\r\n");
      out.write("			            jumin2: jumin2,\r\n");
      out.write("			            gender: gender,\r\n");
      out.write("			            customerNumber: customerNumber\r\n");
      out.write("			        },\r\n");
      out.write("			        success: function(response) {\r\n");
      out.write("			            alert(response);\r\n");
      out.write("			            location.href = \"customerRegistration.jsp\";\r\n");
      out.write("			        },\r\n");
      out.write("			        error: function(xhr, status, error) {\r\n");
      out.write("			            alert(\"오류 발생: \" + error);\r\n");
      out.write("			        }\r\n");
      out.write("			    });\r\n");
      out.write("			});\r\n");
      out.write("\r\n");
      out.write("			// 수정 유효성 검사\r\n");
      out.write("			$(\"#wrap #updatesection .lingSorting .membership\").on(\"click\", function() {\r\n");
      out.write("				var Sortation = \"2\";\r\n");
      out.write("			    var findVal = $(\"#wrap #updatesection .lineSorting\");\r\n");
      out.write("\r\n");
      out.write("			    // 유효성 검사\r\n");
      out.write("			    if (findVal.find(\".memberName\").val() == \"\" || findVal.find(\".memberName\").val() == null) {\r\n");
      out.write("			        alert(\"성함을 입력해주세요\");\r\n");
      out.write("			        findVal.find(\".memberName\").focus();\r\n");
      out.write("			        return false;\r\n");
      out.write("			    }\r\n");
      out.write("			    if (findVal.find(\".memberphone\").val() == \"\" || findVal.find(\".memberphone\").val() == null) {\r\n");
      out.write("			        alert(\"전화번호 입력해주세요\");\r\n");
      out.write("			        findVal.find(\".memberphone\").focus();\r\n");
      out.write("			        return false;\r\n");
      out.write("			    }\r\n");
      out.write("			    if (!findVal.find(\"input[name='1']:checked\").val()) {\r\n");
      out.write("			        alert(\"성별을 선택해주세요\");\r\n");
      out.write("			        return false;\r\n");
      out.write("			    }\r\n");
      out.write("\r\n");
      out.write("			    // 입력값 가져오기\r\n");
      out.write("			    var memberName = findVal.find(\".memberName\").val();\r\n");
      out.write("			    var memberPhone = findVal.find(\".memberphone\").val();\r\n");
      out.write("			    var jumin1 = findVal.find(\".jumin1\").val();\r\n");
      out.write("			    var jumin2 = findVal.find(\".jumin2\").val();\r\n");
      out.write("			    var gender = findVal.find(\"input[name='1']:checked\").val();\r\n");
      out.write("			    var customerNumber = findVal.find(\"input[readonly]\").val();\r\n");
      out.write("\r\n");
      out.write("			    // AJAX 요청 보내기\r\n");
      out.write("			    $.ajax({\r\n");
      out.write("			        url: 'registerMember.jsp',\r\n");
      out.write("			        type: 'POST',\r\n");
      out.write("			        data: {\r\n");
      out.write("			            Sortation: Sortation,\r\n");
      out.write("			            memberName: memberName,\r\n");
      out.write("			            memberPhone: memberPhone,\r\n");
      out.write("			            jumin1: jumin1,\r\n");
      out.write("			            jumin2: jumin2,\r\n");
      out.write("			            gender: gender,\r\n");
      out.write("			            customerNumber: customerNumber\r\n");
      out.write("			        },\r\n");
      out.write("			        success: function(response) {\r\n");
      out.write("			            alert(response);\r\n");
      out.write("			            location.href = \"customerRegistration.jsp\";\r\n");
      out.write("			        },\r\n");
      out.write("			        error: function(xhr, status, error) {\r\n");
      out.write("			            alert(\"오류 발생: \" + error);\r\n");
      out.write("			        }\r\n");
      out.write("			    });\r\n");
      out.write("			});\r\n");
      out.write("\r\n");
      out.write("			\r\n");
      out.write("			//전화번호, 주민번호에 숫자만 입력\r\n");
      out.write("			$(\".memberphone, .jumin1, .jumin2\").on(\"input\", function() {\r\n");
      out.write("				$(this).val($(this).val().replace(/[^0-9]/g, \"\"));\r\n");
      out.write("		    });\r\n");
      out.write("			\r\n");
      out.write("			$(\".registrationUI\").click(function() {\r\n");
      out.write("		        // \"등록\" 클릭 시\r\n");
      out.write("		        $(this).addClass(\"selectUi\");  // \"등록\"에 selectUi 추가\r\n");
      out.write("		        $(\".updateUI\").removeClass(\"selectUi\");  // \"수정\"에서 selectUi 제거\r\n");
      out.write("		        $(\".dataUpdate\").hide();\r\n");
      out.write("		        $(\".dataInsert\").show();\r\n");
      out.write("		    });\r\n");
      out.write("\r\n");
      out.write("		    $(\".updateUI\").click(function() {\r\n");
      out.write("		        // \"수정\" 클릭 시\r\n");
      out.write("		        $(this).addClass(\"selectUi\");  // \"수정\"에 selectUi 추가\r\n");
      out.write("		        $(\".registrationUI\").removeClass(\"selectUi\");  // \"등록\"에서 selectUi 제거\r\n");
      out.write("		        $(\".dataUpdate\").show();\r\n");
      out.write("		        $(\".dataInsert\").hide();\r\n");
      out.write("		    });\r\n");
      out.write("		    \r\n");
      out.write("		    document.addEventListener('keydown', (e) => {\r\n");
      out.write("		    	if(e.keyCode == '113'){\r\n");
      out.write("		    		$(\".registrationUI\").addClass(\"selectUi\");\r\n");
      out.write("		    		$(\".updateUI\").removeClass(\"selectUi\");  // \"수정\"에서 selectUi 제거\r\n");
      out.write("			        $(\".dataUpdate\").hide();\r\n");
      out.write("			        $(\".dataInsert\").show();\r\n");
      out.write("		    	}\r\n");
      out.write("		    	if(e.keyCode == '115'){\r\n");
      out.write("		    		$(\".registrationUI\").removeClass(\"selectUi\");\r\n");
      out.write("	    			$(\".updateUI\").addClass(\"selectUi\");  // \"수정\"에서 selectUi 제거\r\n");
      out.write("		        	$(\".dataUpdate\").show();\r\n");
      out.write("		        	$(\".dataInsert\").hide();\r\n");
      out.write("		    	}\r\n");
      out.write("		    });\r\n");
      out.write("\r\n");
      out.write("		    $(\".closePopup\").on(\"click\", function(){\r\n");
      out.write("		        $('#popup').hide();  // 팝업 숨기기\r\n");
      out.write("		    });\r\n");
      out.write("		    \r\n");
      out.write("		    $(\"#wrap .dataUpdate #updatesection .lineSorting .memberName\").on(\"keydown\", function(e){\r\n");
      out.write("		    	var Sortation = \"2\";\r\n");
      out.write("		        if (e.key === \"Enter\") {  // Enter 키를 눌렀을 때\r\n");
      out.write("		            var memberName = $(this).val();  // 입력한 회원 이름 값 가져오기\r\n");
      out.write("\r\n");
      out.write("		            if (memberName) {\r\n");
      out.write("		                $.ajax({\r\n");
      out.write("		                    url: 'searchMember.jsp',  // 백엔드 처리할 JSP 파일\r\n");
      out.write("		                    type: 'GET',\r\n");
      out.write("		                    data: { \r\n");
      out.write("		                    	memberName: memberName,\r\n");
      out.write("		                    	Sortation : Sortation\r\n");
      out.write("		                    },  // 입력 값 보내기\r\n");
      out.write("		                    success: function(response) {\r\n");
      out.write("		                        $('#popupContent').html(response);  // 서버에서 받은 테이블 HTML을 팝업에 삽입\r\n");
      out.write("		                        $('#popup').show();  // 팝업 보이기\r\n");
      out.write("		                    },\r\n");
      out.write("		                    error: function(xhr, status, error) {\r\n");
      out.write("		                        alert(\"서버와의 통신 오류가 발생했습니다.\");\r\n");
      out.write("		                    }\r\n");
      out.write("		                });\r\n");
      out.write("		            } else {\r\n");
      out.write("		                $('#popup').hide();  // 입력이 비어 있으면 팝업 숨기기\r\n");
      out.write("		            }\r\n");
      out.write("		        }\r\n");
      out.write("		    });\r\n");
      out.write("		    \r\n");
      out.write("		    $(\"#wrap .dataUpdate #updatesection .lineSorting .memberphone\").on(\"keydown\", function(e){\r\n");
      out.write("		    	var Sortation = \"1\";\r\n");
      out.write("		        if (e.key === \"Enter\") {  // Enter 키를 눌렀을 때\r\n");
      out.write("		            var memberphone = $(this).val();  // 입력한 회원 이름 값 가져오기\r\n");
      out.write("\r\n");
      out.write("		            if (memberphone) {\r\n");
      out.write("		                $.ajax({\r\n");
      out.write("		                    url: 'searchMember.jsp',  // 백엔드 처리할 JSP 파일\r\n");
      out.write("		                    type: 'GET',\r\n");
      out.write("		                    data: { \r\n");
      out.write("		                    	memberphone: memberphone,\r\n");
      out.write("		                    	Sortation : Sortation\r\n");
      out.write("		                    },  // 입력 값 보내기\r\n");
      out.write("		                    success: function(response) {\r\n");
      out.write("		                        $('#popupContent').html(response);  // 서버에서 받은 테이블 HTML을 팝업에 삽입\r\n");
      out.write("		                        $('#popup').show();  // 팝업 보이기\r\n");
      out.write("		                    },\r\n");
      out.write("		                    error: function(xhr, status, error) {\r\n");
      out.write("		                        alert(\"서버와의 통신 오류가 발생했습니다.\");\r\n");
      out.write("		                    }\r\n");
      out.write("		                });\r\n");
      out.write("		            } else {\r\n");
      out.write("		                $('#popup').hide();  // 입력이 비어 있으면 팝업 숨기기\r\n");
      out.write("		            }\r\n");
      out.write("		        }\r\n");
      out.write("		    });\r\n");
      out.write("		    \r\n");
      out.write("		 	// 테이블에서 행 클릭 시, 해당 데이터를 폼에 채우는 코드\r\n");
      out.write("		    $(\"#popup #popupContent\").on(\"click\", \".table_line tbody tr\", function() {\r\n");
      out.write("		        // 클릭한 tr의 각 td 값을 변수에 저장\r\n");
      out.write("		        var memberName = $(this).find(\"td:nth-child(1)\").text();  // 회원 이름\r\n");
      out.write("		        var memberPhone = $(this).find(\"td:nth-child(2)\").text();  // 전화번호\r\n");
      out.write("		        var jumin = $(this).find(\"td:nth-child(3)\").text().split(\"-\");  // 주민등록번호\r\n");
      out.write("		        var gender = $(this).find(\"td:nth-child(4)\").text();  // 성별\r\n");
      out.write("		        var custnumber = $(this).find(\"td:nth-child(5)\").text();  // 성별\r\n");
      out.write("\r\n");
      out.write("		        // 값을 #updatesection 내의 입력 필드에 설정\r\n");
      out.write("		        $(\"#updatesection .memberName\").val(memberName);\r\n");
      out.write("		        $(\"#updatesection .memberphone\").val(memberPhone);\r\n");
      out.write("		        $(\"#updatesection .jumin1\").val(jumin[0]);\r\n");
      out.write("		        $(\"#updatesection .jumin2\").val(jumin[1]);\r\n");
      out.write("		        $(\"#updatesection .custnumber\").val(custnumber);\r\n");
      out.write("		        \r\n");
      out.write("		        // 성별 라디오 버튼 값 설정\r\n");
      out.write("		        if (gender === \"1\") {\r\n");
      out.write("		            $(\"input[name='1'][value='1']\").prop(\"checked\", true);\r\n");
      out.write("		        } else if (gender === \"2\") {\r\n");
      out.write("		            $(\"input[name='1'][value='2']\").prop(\"checked\", true);\r\n");
      out.write("		        }\r\n");
      out.write("		        \r\n");
      out.write("		        $(\"#popup\").hide();\r\n");
      out.write("		    });\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
