/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.34
 * Generated at: 2026-01-16 12:57:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;
import java.text.*;
import java.util.*;
import java.sql.*;
import java.sql.*;

public final class filterMedicine_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/DBconnection.jsp", Long.valueOf(1768386619785L));
    _jspx_dependants.put("/sessionManager.jsp", Long.valueOf(1768386620471L));
    _jspx_dependants.put("/DBclose.jsp", Long.valueOf(1768386619783L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(8);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");

String dbUser = (String) session.getAttribute("id");
String jdbcDriver = (String) session.getAttribute("dbName");
String dbPwd = (String) session.getAttribute("password");

if (dbUser == null || jdbcDriver == null || dbPwd == null) {
    response.sendRedirect("login.jsp");
    return;
}

Connection conn = null;

try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    conn = DriverManager.getConnection(jdbcDriver, dbUser, dbPwd);
} catch (Exception e) {
    e.printStackTrace();
}

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");

String dbName = (session != null) ? (String) session.getAttribute("dbName") : null;
String id = (session != null) ? (String) session.getAttribute("id") : null;
String idSortation = (session != null) ? (String) session.getAttribute("idSortation") : null;

if (id == null || dbName == null) {
    response.setStatus(HttpServletResponse.SC_UNAUTHORIZED);
    return;
}

jdbcDriver = dbName;
request.setCharacterEncoding("UTF-8");

String filterValue = request.getParameter("filterValue");
String medicine = request.getParameter("medicineTotal");

int months = 1;
try {
    if (filterValue != null && !filterValue.trim().isEmpty()) {
        months = Integer.parseInt(filterValue);
    }
} catch (Exception e) {
    response.setStatus(HttpServletResponse.SC_BAD_REQUEST);
    return;
}

/* 날짜 계산 */
SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
Calendar cal = Calendar.getInstance();
String rawEnd = sdf.format(cal.getTime());
cal.add(Calendar.MONTH, -months);
String rawStart = sdf.format(cal.getTime());

String startDate = rawStart + " 00:00:00";

Calendar endCal = Calendar.getInstance();
endCal.setTime(sdf.parse(rawEnd));
endCal.add(Calendar.DATE, 1);
String endDate = sdf.format(endCal.getTime()) + " 23:59:59.999";

PreparedStatement pstmt = null;
ResultSet rs = null;

try {

    /* ============================
       1. 월 목록
    ============================ */
    String monthSql =
        "SELECT DATE_FORMAT(saleDate, '%Y-%m') AS SalesMonth " +
        "FROM SalesRecord" + idSortation + " " +
        "WHERE saleDate >= ? AND saleDate < ? " +
        "AND medicineName LIKE ? " +
        "GROUP BY SalesMonth " +
        "ORDER BY SalesMonth DESC";

    pstmt = conn.prepareStatement(monthSql);
    pstmt.setString(1, startDate);
    pstmt.setString(2, endDate);
    pstmt.setString(3, "%" + medicine + "%");
    rs = pstmt.executeQuery();

    while (rs.next()) {

        String currentMonth = rs.getString("SalesMonth");

        /* ============================
           2. 일별 합계
        ============================ */
        String detailSql =
            "SELECT " +
            " DATE(saleDate) AS SalesDates, " +
            " FORMAT(SUM(CAST(price AS DECIMAL)), 0) AS totalPrice, " +
            " FORMAT(SUM(CAST(Buyingprice AS DECIMAL)), 0) AS totalBuyingprice, " +
            " FORMAT(SUM(CAST(price AS DECIMAL)) - SUM(CAST(Buyingprice AS DECIMAL)), 0) AS margin, " +
            " CONCAT(ROUND( " +
            "   (SUM(CAST(price AS DECIMAL)) - SUM(CAST(Buyingprice AS DECIMAL))) / " +
            "   NULLIF(SUM(CAST(price AS DECIMAL)), 0) * 100 " +
            " , 2), '%') AS marginRate " +
            "FROM SalesRecord" + idSortation + " " +
            "WHERE DATE_FORMAT(saleDate, '%Y-%m') = ? " +
            "AND medicineName LIKE ? " +
            "GROUP BY DATE(saleDate) " +
            "ORDER BY DATE(saleDate) ASC";

        PreparedStatement detailPstmt = conn.prepareStatement(detailSql);
        detailPstmt.setString(1, currentMonth);
        detailPstmt.setString(2, "%" + medicine + "%");

        ResultSet detailRs = detailPstmt.executeQuery();

        while (detailRs.next()) {

      out.write("\r\n");
      out.write("<tr class=\"glanceSummary\">\r\n");
      out.write("    <td>");
      out.print( detailRs.getString("SalesDates") );
      out.write("</td>\r\n");
      out.write("    <td>");
      out.print( detailRs.getString("totalPrice") );
      out.write("</td>\r\n");
      out.write("    <td>");
      out.print( detailRs.getString("totalBuyingprice") );
      out.write("</td>\r\n");
      out.write("    <td>");
      out.print( detailRs.getString("margin") );
      out.write("</td>\r\n");
      out.write("    <td>");
      out.print( detailRs.getString("marginRate") );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");

        }

        detailRs.close();
        detailPstmt.close();

        /* ============================
           3. 월 합계
        ============================ */
        String summarySql =
            "SELECT " +
            " DATE_FORMAT(saleDate, '%Y-%m') AS SalesMonth, " +
            " FORMAT(SUM(CAST(price AS DECIMAL)), 0) AS totalPrice, " +
            " FORMAT(SUM(CAST(Buyingprice AS DECIMAL)), 0) AS totalBuyingprice, " +
            " FORMAT(SUM(CAST(price AS DECIMAL)) - SUM(CAST(Buyingprice AS DECIMAL)), 0) AS margin, " +
            " CONCAT(ROUND( " +
            "   (SUM(CAST(price AS DECIMAL)) - SUM(CAST(Buyingprice AS DECIMAL))) / " +
            "   NULLIF(SUM(CAST(price AS DECIMAL)), 0) * 100 " +
            " , 2), '%') AS marginRate " +
            "FROM SalesRecord" + idSortation + " " +
            "WHERE DATE_FORMAT(saleDate, '%Y-%m') = ? " +
            "AND medicineName LIKE ? " +
            "GROUP BY SalesMonth";

        PreparedStatement summaryPstmt = conn.prepareStatement(summarySql);
        summaryPstmt.setString(1, currentMonth);
        summaryPstmt.setString(2, "%" + medicine + "%");

        ResultSet summaryRs = summaryPstmt.executeQuery();

        if (summaryRs.next()) {

      out.write("\r\n");
      out.write("<tr class=\"group-summary\">\r\n");
      out.write("    <td>");
      out.print( summaryRs.getString("SalesMonth") );
      out.write(" 합계</td>\r\n");
      out.write("    <td>");
      out.print( summaryRs.getString("totalPrice") );
      out.write("</td>\r\n");
      out.write("    <td>");
      out.print( summaryRs.getString("totalBuyingprice") );
      out.write("</td>\r\n");
      out.write("    <td>");
      out.print( summaryRs.getString("margin") );
      out.write("</td>\r\n");
      out.write("    <td>");
      out.print( summaryRs.getString("marginRate") );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");

        }

        summaryRs.close();
        summaryPstmt.close();
    }

} catch (Exception e) {
    e.printStackTrace();
    response.setStatus(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
} finally {
    if (rs != null) try { rs.close(); } catch (Exception ignored) {}
    if (pstmt != null) try { pstmt.close(); } catch (Exception ignored) {}
}

      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

    try {
        if (conn != null && !conn.isClosed()) {
            conn.close();
        }
    } catch (Exception ignored) {}

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
