/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.34
 * Generated at: 2026-01-14 13:06:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;
import org.json.*;
import java.util.regex.*;
import java.sql.*;
import java.sql.*;

public final class getDatasUpdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/DBconnection.jsp", Long.valueOf(1768386619785L));
    _jspx_dependants.put("/sessionManager.jsp", Long.valueOf(1768386620471L));
    _jspx_dependants.put("/DBclose.jsp", Long.valueOf(1768386619783L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(8);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("java.util.regex");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("org.json");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("application/json; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");

String dbUser = (String) session.getAttribute("id");
String jdbcDriver = (String) session.getAttribute("dbName");
String dbPwd = (String) session.getAttribute("password");

if (dbUser == null || jdbcDriver == null || dbPwd == null) {
    response.sendRedirect("login.jsp");
    return;
}

Connection conn = null;

try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    conn = DriverManager.getConnection(jdbcDriver, dbUser, dbPwd);
} catch (Exception e) {
    e.printStackTrace();
}

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");

String dbName = (session != null) ? (String) session.getAttribute("dbName") : null;
String id = (session != null) ? (String) session.getAttribute("id") : null;
String idSortation = (session != null) ? (String) session.getAttribute("idSortation") : null;

if (id == null || dbName == null) {
    response.sendRedirect("login.jsp");
    return;
}
jdbcDriver = dbName;
ResultSet countRs = null;
PreparedStatement pstmt = null;

try{
	int pages = 1;
	int limit = 100;
	if (request.getParameter("page") != null) {
	    pages = Integer.parseInt(request.getParameter("page"));
	}
	int offset = (pages - 1) * limit;

	// 전체 행 개수
	PreparedStatement countStmt = conn.prepareStatement("SELECT COUNT(*) FROM testTable" + idSortation);
	countRs = countStmt.executeQuery();
	countRs.next();
	int totalRows = countRs.getInt(1);
	int totalPages = (int) Math.ceil((double) totalRows / limit);

	// 실제 데이터 조회
	String sql = "SELECT *, format(price, 0) AS realPrice FROM testTable" + idSortation +
	             " ORDER BY medicineName ASC, DeliveryDate ASC LIMIT ? OFFSET ?";
	pstmt = conn.prepareStatement(sql);
	pstmt.setInt(1, limit);
	pstmt.setInt(2, offset);
	ResultSet rs = pstmt.executeQuery();

	// HTML 조립
	StringBuilder html = new StringBuilder();

	while (rs.next()) {

	    // ----- HTML append (input 제거, 순수 텍스트) -----
	    html.append("<tr data-key='")
	        .append(rs.getString("medicineName")).append("|")
	        .append(rs.getString("DeliveryDate")).append("|")
	        .append(rs.getString("standard") == null ? "" : rs.getString("standard"))
	        .append("'>");

	    html.append("<td>").append(rs.getString("medicineName")).append("</td>");
	    html.append("<td>").append(rs.getString("DeliveryDate")).append("</td>");
	    html.append("<td>").append(rs.getString("inventory")).append("</td>");
	    html.append("<td>").append(rs.getString("realPrice")).append("</td>");
	    html.append("<td>").append(rs.getString("standard") == null ? "" : rs.getString("standard")).append("</td>");
	    html.append("<td>").append(rs.getString("kind")).append("</td>");
	    html.append("<td>").append(rs.getString("companyName")).append("</td>");
	    html.append("<td>").append(rs.getString("receiptDate")).append("</td>");
	    html.append("<td>").append(rs.getString("quantity")).append("</td>");
	    html.append("</tr>");
	}

	JSONObject result = new JSONObject();
	result.put("html", html.toString());
	result.put("totalPages", totalPages);
	out.print(result.toString());
}catch(Exception e){
	e.printStackTrace();
}finally{
	try{ if(countRs != null) countRs.close(); } catch(Exception ignore) {}
	try{ if(pstmt != null) pstmt.close(); } catch(Exception ignore) {}
}

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

    try {
        if (conn != null && !conn.isClosed()) {
            conn.close();
        }
    } catch (Exception ignored) {}

      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
