/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.34
 * Generated at: 2026-01-14 13:09:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;
import org.json.*;
import java.io.*;
import java.util.regex.*;
import java.sql.*;
import java.sql.*;

public final class getMedicineDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {


double getStandardFactor(String standard) {
    if (standard == null || standard.trim().isEmpty()) return 1.0;

    Matcher m = Pattern.compile("\\d+(\\.\\d+)?").matcher(standard);
    double result = 1.0;

    boolean found = false;

    while (m.find()) {
        found = true;
        result *= Double.parseDouble(m.group());
    }

    return found ? result : 1.0;
}

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/DBconnection.jsp", Long.valueOf(1768386619785L));
    _jspx_dependants.put("/sessionManager.jsp", Long.valueOf(1768386620471L));
    _jspx_dependants.put("/DBclose.jsp", Long.valueOf(1768386619783L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(10);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("java.util.regex");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("org.json");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");

String dbUser = (String) session.getAttribute("id");
String jdbcDriver = (String) session.getAttribute("dbName");
String dbPwd = (String) session.getAttribute("password");

if (dbUser == null || jdbcDriver == null || dbPwd == null) {
    response.sendRedirect("login.jsp");
    return;
}

Connection conn = null;

try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    conn = DriverManager.getConnection(jdbcDriver, dbUser, dbPwd);
} catch (Exception e) {
    e.printStackTrace();
}

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

String dbName = (String) session.getAttribute("dbName");
String id = (String) session.getAttribute("id");
String idSortation = (String) session.getAttribute("idSortation");

if (id == null || dbName == null) return;

jdbcDriver = dbName;

String medicineName = request.getParameter("medicineName");

PreparedStatement pstmt = null;
ResultSet rs = null;
double factor = 0.0;
double inventoryVal = 0.0;

try {
    String sql = 
        "SELECT SerialNumber, medicineName, inventory, DeliveryDate, receiptDate, kind,"
    + " format(Buyingprice,0) realBuying, format(price,0) realP, companyName, standard, quantity " +
        "FROM testTable" + idSortation + " WHERE medicineName = ? order by medicineName asc";
    pstmt = conn.prepareStatement(sql);
    pstmt.setString(1, medicineName);
    rs = pstmt.executeQuery();

    while (rs.next()) {


      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr class=\"leftEditRow\">\r\n");
      out.write("    <td><input type=\"text\" class=\"SerialNumber\" value=\"");
      out.print( rs.getString("SerialNumber") );
      out.write("\" readonly></td>\r\n");
      out.write("    <td><input type=\"text\" class=\"medicineName\" value=\"");
      out.print( rs.getString("medicineName") );
      out.write("\"></td>\r\n");
      out.write("    <td><input type=\"text\" class=\"Buyingprice\" value=\"");
      out.print( rs.getString("realBuying") );
      out.write("\"></td>\r\n");
      out.write("    <td><input type=\"text\" class=\"price\" value=\"");
      out.print( rs.getString("realP") );
      out.write("\"></td>\r\n");
      out.write("    <td><input type=\"text\" class=\"inventory\" value=\"");
      out.print( rs.getString("inventory") );
      out.write("\"></td>\r\n");
      out.write("    <td><input type=\"text\" class=\"quantity\" value=\"");
      out.print( rs.getString("quantity") );
      out.write("\"></td>\r\n");
      out.write("    <td><input type=\"text\" class=\"DeliveryDate\" value=\"");
      out.print( rs.getString("DeliveryDate") );
      out.write("\"></td>\r\n");
      out.write("    <td><input type=\"text\" class=\"receiptDate\" value=\"");
      out.print( rs.getString("receiptDate") );
      out.write("\"></td>\r\n");
      out.write("\r\n");
      out.write("    <td>\r\n");
      out.write("        <select class=\"kind\">\r\n");
      out.write("            <option value=\"건강기능식품\" ");
      out.print( "건강기능식품".equals(rs.getString("kind")) ? "selected" : "" );
      out.write(">건강기능식품</option>\r\n");
      out.write("            <option value=\"일반의약품\" ");
      out.print( "일반의약품".equals(rs.getString("kind")) ? "selected" : "" );
      out.write(">일반의약품</option>\r\n");
      out.write("            <option value=\"파스류\" ");
      out.print( "파스류".equals(rs.getString("kind")) ? "selected" : "" );
      out.write(">파스류</option>\r\n");
      out.write("            <option value=\"연고류\" ");
      out.print( "연고류".equals(rs.getString("kind")) ? "selected" : "" );
      out.write(">연고류</option>\r\n");
      out.write("            <option value=\"드링크류\" ");
      out.print( "드링크류".equals(rs.getString("kind")) ? "selected" : "" );
      out.write(">드링크류</option>\r\n");
      out.write("            <option value=\"비타민류\" ");
      out.print( "비타민류".equals(rs.getString("kind")) ? "selected" : "" );
      out.write(">비타민류</option>\r\n");
      out.write("            <option value=\"한약류\" ");
      out.print( "한약류".equals(rs.getString("kind")) ? "selected" : "" );
      out.write(">한약류</option>\r\n");
      out.write("            <option value=\"기타\" ");
      out.print( "기타".equals(rs.getString("kind")) ? "selected" : "" );
      out.write(">기타</option>\r\n");
      out.write("        </select>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td><input type=\"text\" class=\"companyName\" value=\"");
      out.print( rs.getString("companyName") );
      out.write("\"></td>\r\n");
      out.write("    <td><input type=\"text\" class=\"standard\" value=\"");
      out.print( rs.getString("standard") );
      out.write("\"></td>\r\n");
      out.write("</tr>\r\n");

    }
} catch (Exception e) {
    out.print("<tr><td colspan='10'>오류: " + e.getMessage() + "</td></tr>");
} finally {
    try { if (pstmt != null) pstmt.close(); } catch (Exception ignored) {}
    try { if (rs != null) rs.close(); } catch (Exception ignored) {}
}

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

    try {
        if (conn != null && !conn.isClosed()) {
            conn.close();
        }
    } catch (Exception ignored) {}

      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
