/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.34
 * Generated at: 2026-01-17 13:29:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;
import java.sql.*;

public final class index2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/DBconnection.jsp", Long.valueOf(1768386619785L));
    _jspx_dependants.put("/sessionManager.jsp", Long.valueOf(1768386620471L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");

String dbUser = (String) session.getAttribute("id");
String jdbcDriver = (String) session.getAttribute("dbName");
String dbPwd = (String) session.getAttribute("password");

if (dbUser == null || jdbcDriver == null || dbPwd == null) {
    response.sendRedirect("login.jsp");
    return;
}

Connection conn = null;

try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    conn = DriverManager.getConnection(jdbcDriver, dbUser, dbPwd);
} catch (Exception e) {
    e.printStackTrace();
}

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

String dbName = (session != null) ? (String) session.getAttribute("dbName") : null;
String id = (session != null) ? (String) session.getAttribute("id") : null;
String password = (session != null) ? (String) session.getAttribute("password") : null;

String idSortation = (session != null) ? (String) session.getAttribute("idSortation") : null; 
if (id == null || dbName == null) {
    response.sendRedirect("login.jsp");
    return;
}

jdbcDriver = dbName;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"stock/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"content\">\r\n");
      out.write("    <!-- Ajax로 본문이 들어올 자리 -->\r\n");
      out.write("</div>\r\n");
      out.write("	<div id=\"wrap\" class=\"index\">\r\n");
      out.write("		<header>\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("		</header>\r\n");
      out.write("		<form name=\"data\" method=\"post\" id=\"formTeg\" class=\"index-form\">\r\n");
      out.write("\r\n");
      out.write("			<div>\r\n");
      out.write("				<h1 class=\"index-title\">재고 목록</h1>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"filter index-filter\">\r\n");
      out.write("					<input type=\"text\" id=\"nameSearch\" class=\"index-search\" placeholder=\" 제품명을 입력하세요\">\r\n");
      out.write("					<input type=\"text\" id=\"nameSearch\" style=\"position: relative; top: 5%; width:250px;height: 40px;border-radius: 10px;\" placeholder=\" 제품명을 입력하세요\">\r\n");
      out.write("					<div class=\"filterButton index-filter-buttons\">\r\n");
      out.write("\r\n");
      out.write("						<button class=\"custom-btn btn-12\" data-value=\"1\">1개월 이내</button>\r\n");
      out.write("						<button class=\"custom-btn btn-12\" data-value=\"3\">3개월 이내</button>\r\n");
      out.write("						<button class=\"custom-btn btn-12\" data-value=\"6\">6개월 이내</button>\r\n");
      out.write("						<button class=\"custom-btn btn-12\" data-value=\"12\">1년 이내</button>\r\n");
      out.write("						<input type=\"button\" class=\"quantity\" value=\"주문목록\">\r\n");
      out.write("						<input type=\"button\" class=\"saveSale\" value=\"주문완료\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"ExcelDownload index-excel\">\r\n");
      out.write("						<button type=\"button\" class=\"downloadBtn btn green mini\" value=\"Excel 다운로드\">Excel 다운로드</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<table class=\"table_line indexTable index-table\">\r\n");
      out.write("				<colgroup>\r\n");
      out.write("					<col width=\"9%\">\r\n");
      out.write("					<col width=\"9%\">\r\n");
      out.write("					<col width=\"10%\">\r\n");
      out.write("					<col width=\"9%\">\r\n");
      out.write("					<col width=\"9%\">\r\n");
      out.write("					<col width=\"9%\">\r\n");
      out.write("					<col width=\"9%\">\r\n");
      out.write("					<col width=\"9%\">\r\n");
      out.write("					<col width=\"9%\">\r\n");
      out.write("					<col width=\"9%\">\r\n");
      out.write("					<col width=\"9%\">\r\n");
      out.write("				</colgroup>\r\n");
      out.write("				<thead class=\"index-thead\">\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>모두보기</th>\r\n");
      out.write("						<th>수정 / 삭제<br>\r\n");
      out.write("						<th>이름<span class=\"ascendingOrder nameAscendingOrder\">↑</span><span class=\"descendingOrder nameDescendingOrder\">↓</span></th>\r\n");
      out.write("						<th>유통기한<br>(유효기간)\r\n");
      out.write("						<th>주문 최소 수량</th>\r\n");
      out.write("						<th>실제 수량<span class=\"ascendingOrder invAscendingOrder\">↑</span><span class=\"ascendingOrder invDescendingOrder\">↓</span></th>\r\n");
      out.write("						<th>규격</th>\r\n");
      out.write("						<th>가격<span class=\"ascendingOrder priceAscendingOrder\">↑</span><span class=\"descendingOrder priceDescendingOrder\">↓</span></th>\r\n");
      out.write("						<th>회사명</th>\r\n");
      out.write("						<th>입고 날짜</th>\r\n");
      out.write("						<th>반품개시<br></th>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</thead>\r\n");
      out.write("				<tbody id=\"inventory_list\" class=\"index-tbody\">\r\n");
      out.write("\r\n");
      out.write("				</tbody>\r\n");
      out.write("			</table>\r\n");
      out.write("			<div id=\"pagination\" class=\"index-pagination\"></div>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("	<script src=\"jquery-3.7.1.min.js\"></script>\r\n");
      out.write("	<script src=\"script.js\"></script>\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/flatpickr\"></script>\r\n");
      out.write("	<script src=\"https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("	// ===== 전체 jQuery 통합 리팩토링 =====\r\n");
      out.write("	$(document).ready(function () {\r\n");
      out.write("	    initEvents();\r\n");
      out.write("	    initPagination();\r\n");
      out.write("	    autoClickTrigger();\r\n");
      out.write("	    showFirstToggleButton();\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	// --------------------------------------------\r\n");
      out.write("	// 기본 이벤트 및 액션 핸들러 통합\r\n");
      out.write("	// --------------------------------------------\r\n");
      out.write("function initEvents() {\r\n");
      out.write("\r\n");
      out.write("    // 주문 선택\r\n");
      out.write("    $(\"#wrap\").on(\"click\", \".isOrdered\", function () {\r\n");
      out.write("        $(this).closest(\"tr\").toggleClass(\"selectTr\");\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // 검색 focus\r\n");
      out.write("    $(\"#nameSearch\").hover(\r\n");
      out.write("        function () { $(this).addClass(\"searchFocus\"); },\r\n");
      out.write("        function () { $(this).removeClass(\"searchFocus\"); }\r\n");
      out.write("    );\r\n");
      out.write("\r\n");
      out.write("    // 반품 UI\r\n");
      out.write("    $(\"#inventory_list\").on(\"change\", \".returnProduct\", function () {\r\n");
      out.write("        $(this).closest(\"tr\").css(\"opacity\", $(this).val() === \"반품됨\" ? 0.5 : 1);\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // 수정 / 삭제\r\n");
      out.write("    $(\"#inventory_list\").on(\"click\", \".updateInfo\", (e) => handleRowEdit($(e.target).closest(\"tr\")));\r\n");
      out.write("    $(\"#inventory_list\").on(\"click\", \".deleteInfo\", (e) => handleRowDelete($(e.target).closest(\"tr\")));\r\n");
      out.write("\r\n");
      out.write("    // 정렬\r\n");
      out.write("    $(\".priceAscendingOrder\").click(() => sortTable(\"price\", true));\r\n");
      out.write("    $(\".priceDescendingOrder\").click(() => sortTable(\"price\", false));\r\n");
      out.write("    $(\".nameAscendingOrder\").click(() => sortTable(\"name\", true));\r\n");
      out.write("    $(\".nameDescendingOrder\").click(() => sortTable(\"name\", false));\r\n");
      out.write("    $(\".invAscendingOrder\").click(() => sortTable(\"inv\", true));\r\n");
      out.write("    $(\".invDescendingOrder\").click(() => sortTable(\"inv\", false));\r\n");
      out.write("\r\n");
      out.write("    // 수량\r\n");
      out.write("    $(\".quantity\").click(loadQuantityData);\r\n");
      out.write("\r\n");
      out.write("    // 주문완료\r\n");
      out.write("    $(\".saveSale\").click(processSaleOrder);\r\n");
      out.write("\r\n");
      out.write("    // 검색 Enter\r\n");
      out.write("    $(\"#nameSearch\").keydown(e => e.key === \"Enter\" && (e.preventDefault(), executeNameSearch()));\r\n");
      out.write("\r\n");
      out.write("    // ======= 문제였던 두개 추가한 부분 =======\r\n");
      out.write("\r\n");
      out.write("    // 개월 필터 버튼\r\n");
      out.write("    $(\".filter .filterButton .custom-btn\").on(\"click\", function (event) {\r\n");
      out.write("        event.preventDefault();\r\n");
      out.write("        const filterValue = parseInt($(this).data(\"value\"), 10);\r\n");
      out.write("\r\n");
      out.write("        $.post(\"filterData.jsp\", { filterValue }, function (response) {\r\n");
      out.write("            $(\"#inventory_list\").html(response);\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // 엑셀 다운로드 버튼\r\n");
      out.write("    $(\".downloadBtn\").on(\"click\", function () {\r\n");
      out.write("        const table = document.querySelector(\".table_line\");\r\n");
      out.write("        const workbook = XLSX.utils.table_to_book(table, { sheet: \"Sheet1\" });\r\n");
      out.write("        const t = new Date();\r\n");
      out.write("        XLSX.writeFile(workbook, `");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${t.getFullYear()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('.');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${t.getMonth() + 1}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('.');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${t.getDate()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".xlsx`);\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	// --------------------------------------------\r\n");
      out.write("	// 공통 AJAX 함수\r\n");
      out.write("	// --------------------------------------------\r\n");
      out.write("	function ajaxPost(url, data, onSuccess) {\r\n");
      out.write("	    $.ajax({\r\n");
      out.write("	        url,\r\n");
      out.write("	        type: \"POST\",\r\n");
      out.write("	        contentType: \"application/json; charset=UTF-8\",\r\n");
      out.write("	        data: JSON.stringify(data),\r\n");
      out.write("	        success: onSuccess,\r\n");
      out.write("	        error: (xhr, status, error) => console.error(url + \" Error:\", error)\r\n");
      out.write("	    });\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	// --------------------------------------------\r\n");
      out.write("	// 행 수정 및 삭제 핸들러\r\n");
      out.write("	// --------------------------------------------\r\n");
      out.write("function handleRowEdit(row) {\r\n");
      out.write("\r\n");
      out.write("	const medicineName = row.find(\"td:nth-child(3)\").text().replace(/\\s+/g, \"\").trim();\r\n");
      out.write("    const deliveryDate = row.find(\"td:nth-child(4)\").text().trim();\r\n");
      out.write("    const quantity = row.find(\"td:nth-child(7)\").text().trim();\r\n");
      out.write("\r\n");
      out.write("    alert(\"medicineName: \" + medicineName);\r\n");
      out.write("\r\n");
      out.write("    $.ajax({\r\n");
      out.write("        url: \"dataUpdate.jsp\",\r\n");
      out.write("        type: \"POST\",\r\n");
      out.write("        data: {\r\n");
      out.write("            secondData: medicineName,\r\n");
      out.write("            eighthData: deliveryDate,\r\n");
      out.write("            ninthData: quantity\r\n");
      out.write("        },\r\n");
      out.write("        dataType: \"text\",   // 서버가 JSON 문자열 주므로 text로 받고 직접 파싱\r\n");
      out.write("        success: function(res) {\r\n");
      out.write("            try {\r\n");
      out.write("                const json = (typeof res === \"string\") ? JSON.parse(res) : res;\r\n");
      out.write("\r\n");
      out.write("                if (json.result === \"ok\") {\r\n");
      out.write("                    window.location.href = \"editPage.jsp\";\r\n");
      out.write("                } else {\r\n");
      out.write("                    alert(\"실패: \" + (json.reason || \"unknown\"));\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("            } catch (e) {\r\n");
      out.write("                // JSON이 아닌 경우 (예: HTML, redirect 결과 등)\r\n");
      out.write("                console.log(\"JSON parse 실패, 원본 응답:\", res);\r\n");
      out.write("                window.location.href = \"editPage.jsp\";\r\n");
      out.write("            }\r\n");
      out.write("        },\r\n");
      out.write("        error: function(xhr, status, err) {\r\n");
      out.write("            console.error(\"AJAX ERROR\");\r\n");
      out.write("            console.error(\"status:\", status);\r\n");
      out.write("            console.error(\"code:\", xhr.status);\r\n");
      out.write("            console.error(\"response:\", xhr.responseText);\r\n");
      out.write("            alert(\"서버 통신 실패 (\" + xhr.status + \")\");\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	function handleRowDelete(row) {\r\n");
      out.write("	    if (!confirm(\"삭제하시겠습니까?\")) return;\r\n");
      out.write("\r\n");
      out.write("	    ajaxPost(\"datadelete.jsp\", [{\r\n");
      out.write("	        secondData: row.find(\"td:eq(3)\").text().trim(),\r\n");
      out.write("	        eighthData: row.find(\"td:eq(6)\").text().trim(),\r\n");
      out.write("	        ninthData: row.find(\"td:eq(4)\").text().trim()\r\n");
      out.write("	    }], () => row.remove());\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	// --------------------------------------------\r\n");
      out.write("	// 주문 체크된 항목 처리\r\n");
      out.write("	// --------------------------------------------\r\n");
      out.write("	function processSaleOrder() {\r\n");
      out.write("	    const checkedRows = [];\r\n");
      out.write("\r\n");
      out.write("	    $(\"#inventory_list tr\").each(function () {\r\n");
      out.write("	        const checkbox = $(this).find(\".isOrdered\");\r\n");
      out.write("	        if (checkbox.is(\":checked\")) {\r\n");
      out.write("	            checkedRows.push({\r\n");
      out.write("	                medicineName: $(this).find(\"td:eq(2)\").text().trim(),\r\n");
      out.write("	                DeliveryDate: $(this).find(\"td:eq(3)\").text().trim()\r\n");
      out.write("	            });\r\n");
      out.write("	        }\r\n");
      out.write("	    });\r\n");
      out.write("\r\n");
      out.write("	    if (checkedRows.length === 0) {\r\n");
      out.write("	        return alert(\"주문완료 처리할 제품을 선택하세요.\");\r\n");
      out.write("	    }\r\n");
      out.write("\r\n");
      out.write("	    ajaxPost(\"updateIsOrdered.jsp\", checkedRows, () => {\r\n");
      out.write("	        alert(\"주문완료로 처리되었습니다.\");\r\n");
      out.write("	        $(\".quantity\").click();\r\n");
      out.write("	    });\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	// --------------------------------------------\r\n");
      out.write("	// 정렬 함수 통합\r\n");
      out.write("	// --------------------------------------------\r\n");
      out.write("	function sortTable(type, ascending) {\r\n");
      out.write("	    const index = { price: 3, name: 1, inv: 4 }[type];\r\n");
      out.write("	    const rows = $(\".table_line tbody tr\").get();\r\n");
      out.write("\r\n");
      out.write("	    rows.sort((a, b) => {\r\n");
      out.write("	        const A = $(a).find(`td:eq(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${index}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")`).text().trim().toUpperCase();\r\n");
      out.write("	        const B = $(b).find(`td:eq(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${index}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")`).text().trim().toUpperCase();\r\n");
      out.write("	        const numeric = !isNaN(A) && !isNaN(B);\r\n");
      out.write("	        return ascending ? (numeric ? A - B : A.localeCompare(B))\r\n");
      out.write("	                         : (numeric ? B - A : B.localeCompare(A));\r\n");
      out.write("	    });\r\n");
      out.write("\r\n");
      out.write("	    $(\".table_line tbody\").append(rows);\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	// --------------------------------------------\r\n");
      out.write("	// 수량 변동 후 테이블 리로드\r\n");
      out.write("	// --------------------------------------------\r\n");
      out.write("	function loadQuantityData() {\r\n");
      out.write("	    $.post(\"quantityData.jsp\", function (response) {\r\n");
      out.write("	        $(\"#inventory_list\").html(response);\r\n");
      out.write("	        $(\"#inventory_list .isOrdered:checked\").closest(\"tr\").addClass(\"selectTr\");\r\n");
      out.write("	    });\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	// --------------------------------------------\r\n");
      out.write("	// 자동 실행\r\n");
      out.write("	// --------------------------------------------\r\n");
      out.write("	function autoClickTrigger() {\r\n");
      out.write("	    const params = new URLSearchParams(window.location.search);\r\n");
      out.write("	    if (params.get(\"autoClick\") === \"true\") $(\".quantity\").first().trigger(\"click\");\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	// --------------------------------------------\r\n");
      out.write("	// 제품명 검색 AJAX\r\n");
      out.write("	// --------------------------------------------\r\n");
      out.write("	function executeNameSearch() {\r\n");
      out.write("	    const keyword = $(\"#nameSearch\").val().trim();\r\n");
      out.write("	    if (keyword === \"\") return alert(\"검색어를 입력해 주세요.\");\r\n");
      out.write("\r\n");
      out.write("	    $.post(\"getData.jsp\", { nameSearch: keyword }, function (response) {\r\n");
      out.write("	        $(\"#inventory_list\").html(response);\r\n");
      out.write("	    });\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	// --------------------------------------------\r\n");
      out.write("	// 제품명 동일 그룹 토글 버튼\r\n");
      out.write("	// --------------------------------------------\r\n");
      out.write("	function showFirstToggleButton() {\r\n");
      out.write("	    const grouped = {};\r\n");
      out.write("\r\n");
      out.write("	    $(\"#inventory_list tr\").each(function () {\r\n");
      out.write("	        const name = $(this).find(\"td:eq(2)\").text();\r\n");
      out.write("	        const btn = $(this).find(\".toggle-details\");\r\n");
      out.write("\r\n");
      out.write("	        if (!grouped[name]) grouped[name] = [];\r\n");
      out.write("	        grouped[name].push($(this));\r\n");
      out.write("\r\n");
      out.write("	        if (grouped[name].length > 1) btn.hide();\r\n");
      out.write("	    });\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	// --------------------------------------------\r\n");
      out.write("	// 페이지네이션\r\n");
      out.write("	// --------------------------------------------\r\n");
      out.write("	function initPagination() {\r\n");
      out.write("	    const rowsPerPage = 50;\r\n");
      out.write("	    const rows = $(\"#inventory_list tr\").get();\r\n");
      out.write("	    const totalPages = Math.ceil(rows.length / rowsPerPage);\r\n");
      out.write("\r\n");
      out.write("	    function showPage(p) {\r\n");
      out.write("	        rows.forEach((row, i) => row.style.display = (i >= (p - 1) * rowsPerPage && i < p * rowsPerPage) ? \"\" : \"none\");\r\n");
      out.write("	        buildPaginationButtons(p);\r\n");
      out.write("	    }\r\n");
      out.write("\r\n");
      out.write("	    function buildPaginationButtons(p) {\r\n");
      out.write("	        const pag = $(\"#pagination\").empty();\r\n");
      out.write("	        for (let i = 1; i <= totalPages; i++) {\r\n");
      out.write("	            $(\"<button>\")\r\n");
      out.write("	                .text(i)\r\n");
      out.write("	                .toggleClass(\"activePage\", i === p)\r\n");
      out.write("	                .click(() => showPage(i))\r\n");
      out.write("	                .appendTo(pag);\r\n");
      out.write("	        }\r\n");
      out.write("	    }\r\n");
      out.write("	    showPage(1);\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
