/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.34
 * Generated at: 2026-01-14 12:47:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;
import java.sql.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/DBconnection.jsp", Long.valueOf(1768386619785L));
    _jspx_dependants.put("/sessionManager.jsp", Long.valueOf(1768386620471L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");

String dbUser = (String) session.getAttribute("id");
String jdbcDriver = (String) session.getAttribute("dbName");
String dbPwd = (String) session.getAttribute("password");

if (dbUser == null || jdbcDriver == null || dbPwd == null) {
    response.sendRedirect("login.jsp");
    return;
}

Connection conn = null;

try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    conn = DriverManager.getConnection(jdbcDriver, dbUser, dbPwd);
} catch (Exception e) {
    e.printStackTrace();
}

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

String dbName = (session != null) ? (String) session.getAttribute("dbName") : null;
String id = (session != null) ? (String) session.getAttribute("id") : null;
String password = (session != null) ? (String) session.getAttribute("password") : null;

/* out.println(password);
out.println(dbName);
out.println(id);
out.println(password); */

String idSortation = (session != null) ? (String) session.getAttribute("idSortation") : null;
if (id == null || dbName == null) {
	response.sendRedirect("login.jsp");
	return;
}

jdbcDriver = dbName;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel='stylesheet' href='stock/style.css'>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"informationUI\">\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "informationUI.jsp", out, false);
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"wrap\">\r\n");
      out.write("		<header>\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("		</header>\r\n");
      out.write("		<form action=\"index.jsp\" name=\"data\" method=\"post\" id=\"formTeg\">\r\n");
      out.write("			<h1>재고 목록</h1>\r\n");
      out.write("			<div class=\"filterLine\">\r\n");
      out.write("				<div id=\"pageControl\">\r\n");
      out.write("					<button id=\"prevPage\">이전</button>\r\n");
      out.write("					<span id=\"pageInfo\">1 / 1</span>\r\n");
      out.write("					<button id=\"nextPage\">다음</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"filter\">\r\n");
      out.write("					<input type=\"text\" id=\"nameSearch\" placeholder=\"제품명을 입력하세요\"><input\r\n");
      out.write("						type=\"month\" id=\"deliveryDateCh\">\r\n");
      out.write("					<div class=\"alert-container\">\r\n");
      out.write("						<div class=\"alert-ring\"></div>\r\n");
      out.write("						<div class=\"alert-ring\"></div>\r\n");
      out.write("						<div class=\"alert-ring\"></div>\r\n");
      out.write("						<div class=\"alert-center\">⚠</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<input type=\"button\" id=\"saveAll\" value=\"💾 전체 저장\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<input id=\"barcodeInput\" type='text' name=\"barcodeInput\"\r\n");
      out.write("				autofocus=\"autofocus\" autocomplete=\"off\" />\r\n");
      out.write("			<table class=\"table_line\">\r\n");
      out.write("				<thead>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>이름<span class=\"ascendingOrder nameAscendingOrder\">↑</span><span\r\n");
      out.write("							class=\"descendingOrder nameDescendingOrder\">↓</span></th>\r\n");
      out.write("						<th>유통기한<br>(유효기간)\r\n");
      out.write("						<th>실제 수량<span class=\"ascendingOrder invAscendingOrder\">↑</span><span\r\n");
      out.write("							class=\"ascendingOrder invDescendingOrder\">↓</span></th>\r\n");
      out.write("						<th>가격<span class=\"ascendingOrder priceAscendingOrder\">↑</span><span\r\n");
      out.write("							class=\"descendingOrder priceDescendingOrder\">↓</span></th>\r\n");
      out.write("						<th>규격</th>\r\n");
      out.write("						<th>수정 / 삭제<br> <!-- \r\n");
      out.write("						<th>즐겨찾기</th> -->\r\n");
      out.write("						<th>종류 <br> <select id=\"kindValue\">\r\n");
      out.write("								<option value=\"전체\" selected>전체</option>\r\n");
      out.write("								<option value=\"건강기능식품\">건강기능식품</option>\r\n");
      out.write("								<option value=\"일반의약품\">일반의약품</option>\r\n");
      out.write("								<option value=\"파스류\">파스류</option>\r\n");
      out.write("								<option value=\"연고류\">연고류</option>\r\n");
      out.write("								<option value=\"드링크류\">드링크류</option>\r\n");
      out.write("								<option value=\"비타민류\">비타민류</option>\r\n");
      out.write("								<option value=\"한약류\">한약류</option>\r\n");
      out.write("								<option value=\"기타\">기타</option>\r\n");
      out.write("						</select>\r\n");
      out.write("						</th>\r\n");
      out.write("						<th>회사명</th>\r\n");
      out.write("						<th>입고 날짜</th>\r\n");
      out.write("						<th>반품개시<br>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</thead>\r\n");
      out.write("				<tbody id=\"inventory_list\">\r\n");
      out.write("				</tbody>\r\n");
      out.write("			</table>\r\n");
      out.write("			<div id=\"pagination\"></div>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- 우클릭 했을 때 정보 확인 -->\r\n");
      out.write("	<div id=\"coordinates\">\r\n");
      out.write("		<span class=\"Respectively_saleRecord\">판매기록 보기</span> <span\r\n");
      out.write("			class=\"Respectively_payment\">재품정보 상세보기</span>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- 판매기록 보기의 팝업창 -->\r\n");
      out.write("	<div id=\"detailInfo_popup\"></div>\r\n");
      out.write("	<!-- 재품 상세정보 보기의 팝업창 -->\r\n");
      out.write("	<div id=\"paymentInto_popup\"></div>\r\n");
      out.write("	<script src=\"jquery-3.7.1.min.js\"></script>\r\n");
      out.write("	<script src=\"script.js\"></script>\r\n");
      out.write("	<!-- xlsx 라이브러리 로드 (CDN 사용) -->\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("let currentPage = 1;\r\n");
      out.write("let totalPages = 0;\r\n");
      out.write("let changedData = {};\r\n");
      out.write("let showReturnHidden = false;\r\n");
      out.write("let toggleStates = {};\r\n");
      out.write("\r\n");
      out.write("// 페이지 로드 후 실행\r\n");
      out.write("$(document).ready(function () {\r\n");
      out.write("    initLoad();\r\n");
      out.write("    bindEvents();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("/** 첫 로드시 1페이지 불러오기 **/\r\n");
      out.write("function initLoad() {\r\n");
      out.write("    loadPage(1, true);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/** ======================== 이벤트 바인딩 ======================== **/\r\n");
      out.write("function bindEvents() {\r\n");
      out.write("\r\n");
      out.write("    /** 숫자 3자리 콤마 */\r\n");
      out.write("    $(\"#wrap\").on(\"input\", \".price, .Buyingprice, .inventory\", function () {\r\n");
      out.write("        const val = $(this).val().replace(/[^0-9]/g, \"\");\r\n");
      out.write("        $(this).val(val.replace(/\\B(?=(\\d{3})+(?!\\d))/g, \",\"));\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    /** 수정 데이터 수집 */\r\n");
      out.write("    $(document).on(\"input\", \".editable\", function () {\r\n");
      out.write("        const key = $(this).closest(\"tr\").data(\"key\");\r\n");
      out.write("        const field = $(this).attr(\"name\");\r\n");
      out.write("        const value = $(this).val();\r\n");
      out.write("\r\n");
      out.write("        if (!changedData[key]) changedData[key] = {};\r\n");
      out.write("        changedData[key][field] = value;\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    /** 엔터 입력 시 바코드 submit */\r\n");
      out.write("    $(document).keydown(function (event) {\r\n");
      out.write("        if (event.key === \"Enter\" && $(\"#barcodeInput\").val()) {\r\n");
      out.write("            event.preventDefault();\r\n");
      out.write("            $('#formTeg').submit();\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    /** 저장 버튼 */\r\n");
      out.write("    $(\"#saveAll\").click(function () {\r\n");
      out.write("        if (!Object.keys(changedData).length) {\r\n");
      out.write("            alert(\"변경된 데이터가 없습니다.\");\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url: \"saveAll.jsp\",\r\n");
      out.write("            type: \"POST\",\r\n");
      out.write("            contentType: \"application/json\",\r\n");
      out.write("            data: JSON.stringify(changedData),\r\n");
      out.write("            success: () => {\r\n");
      out.write("                alert(\"저장 완료!\");\r\n");
      out.write("                loadPage(currentPage, false);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    /** 포커스 기반 행/열 강조 */\r\n");
      out.write("    $(\"#wrap\").on(\"focus\", \".table_line input\", handleFocus);\r\n");
      out.write("\r\n");
      out.write("    /** 방향키 이동 */\r\n");
      out.write("    $(\"#wrap .table_line\").on(\"keydown\", \"input\", arrowMove);\r\n");
      out.write("\r\n");
      out.write("    /** 마우스 hover 효과 */\r\n");
      out.write("    $(\"#wrap .table_line\").on(\"mouseover\", \"tr\", hoverRow)\r\n");
      out.write("                          .on(\"mouseout\", \"tr\", hoverRow);\r\n");
      out.write("\r\n");
      out.write("    /** 우클릭 상세메뉴 */\r\n");
      out.write("    $(\"#wrap .table_line\").on(\"contextmenu\", \"tr\", showContextMenu);\r\n");
      out.write("\r\n");
      out.write("    /** ESC → 설정창 토글 */\r\n");
      out.write("    $(document).keydown((e) => {\r\n");
      out.write("        if (e.key === \"Escape\") $(\"#coordinates\").hide();\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    /** 페이지네이션 */\r\n");
      out.write("    $(\"#nextPage\").click(() => { if (currentPage < totalPages) loadPage(currentPage + 1); });\r\n");
      out.write("    $(\"#prevPage\").click(() => { if (currentPage > 1) loadPage(currentPage - 1); });\r\n");
      out.write("\r\n");
      out.write("    /** 검색 필터 */\r\n");
      out.write("    $(\"#nameSearch\").on(\"input\", filterByName);\r\n");
      out.write("    $(\"#kindValue\").on(\"change\", filterByKind);\r\n");
      out.write("\r\n");
      out.write("    /** 반품 토글 */\r\n");
      out.write("    $('#toggleButton').click(toggleReturnRows);\r\n");
      out.write("\r\n");
      out.write("    /** 상세 팝업 닫기 */\r\n");
      out.write("    $(\"#detailInfo_popup, #paymentInto_popup\").on(\"click\", \".popupDown, .close-button\", hidePopup);\r\n");
      out.write("    $(\"#wrap .table_line #inventory_list\").on(\"click\", \"tr td input\", function(){\r\n");
      out.write("    	(this).select();\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    $(\"#wrap\").on(\"input\",\".table_line .deliveryDate, .table_line .receipDate\", function () {\r\n");
      out.write("        $(this).val(formatDateInput($(this).val()));\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/** ======================== 기능 함수 ======================== **/\r\n");
      out.write("function formatDateInput(value) {\r\n");
      out.write("    // 숫자만 추출\r\n");
      out.write("    let v = value.replace(/[^0-9]/g, \"\");\r\n");
      out.write("\r\n");
      out.write("    // 자리수 제한 (6자리)\r\n");
      out.write("    v = v.substring(0, 6);\r\n");
      out.write("\r\n");
      out.write("    // 자동 슬래시 삽입\r\n");
      out.write("    if (v.length >= 5) {\r\n");
      out.write("        v = v.replace(/(\\d{2})(\\d{2})(\\d{1,2})/, \"$1/$2/$3\");\r\n");
      out.write("    } else if (v.length >= 3) {\r\n");
      out.write("        v = v.replace(/(\\d{2})(\\d{1,2})/, \"$1/$2\");\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    return v;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function loadPage(page, updatePageInfo = true) {\r\n");
      out.write("    $.ajax({\r\n");
      out.write("        url: \"getDatas.jsp\",\r\n");
      out.write("        type: \"GET\",\r\n");
      out.write("        data: { page },\r\n");
      out.write("        dataType: \"json\",\r\n");
      out.write("        success: function (res) {\r\n");
      out.write("            $(\"#inventory_list\").html(res.html);\r\n");
      out.write("            currentPage = page;\r\n");
      out.write("            totalPages = res.totalPages;\r\n");
      out.write("            if (updatePageInfo) $(\"#pageInfo\").text(page + \" / \" + totalPages);\r\n");
      out.write("\r\n");
      out.write("            showFirstToggleButton(); // 재고 그룹 초기화\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function handleFocus() {\r\n");
      out.write("    $(\".focusRow, .focusCol, .focusCell\").removeClass(\"focusRow focusCol focusCell\");\r\n");
      out.write("\r\n");
      out.write("    const $tr = $(this).closest(\"tr\");\r\n");
      out.write("    const col = $(this).closest(\"td\").index();\r\n");
      out.write("\r\n");
      out.write("    $tr.addClass(\"focusRow\");\r\n");
      out.write("    $(\".table_line tbody tr\").each(function () {\r\n");
      out.write("        $(this).children(\"td\").eq(col).addClass(\"focusCol\");\r\n");
      out.write("    });\r\n");
      out.write("    $(this).closest(\"td\").addClass(\"focusCell\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function arrowMove(e) {\r\n");
      out.write("    const dir = { ArrowUp: -1, ArrowDown: 1 };\r\n");
      out.write("    const key = e.key;\r\n");
      out.write("    if (![\"ArrowUp\", \"ArrowDown\", \"ArrowLeft\", \"ArrowRight\"].includes(key)) return;\r\n");
      out.write("\r\n");
      out.write("    const td = $(this).closest(\"td\");\r\n");
      out.write("    const tr = $(this).closest(\"tr\");\r\n");
      out.write("    const col = td.index();\r\n");
      out.write("    let nextInput;\r\n");
      out.write("\r\n");
      out.write("    if (key === \"ArrowUp\" || key === \"ArrowDown\") {\r\n");
      out.write("        const nextTr = key === \"ArrowUp\" ? tr.prev() : tr.next();\r\n");
      out.write("        nextInput = nextTr.children(\"td\").eq(col).find(\"input\");\r\n");
      out.write("    } else {\r\n");
      out.write("        const add = key === \"ArrowLeft\" ? -1 : 1;\r\n");
      out.write("        nextInput = tr.children(\"td\").eq(col + add).find(\"input\");\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    if (nextInput?.length) {\r\n");
      out.write("        e.preventDefault();\r\n");
      out.write("        nextInput.focus().select();\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function hoverRow() {\r\n");
      out.write("    if (!$(\"#coordinates\").is(\":visible\")) $(this).toggleClass(\"selectDetail\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function showContextMenu(e) {\r\n");
      out.write("    e.preventDefault();\r\n");
      out.write("    const x = e.pageX, y = e.pageY;\r\n");
      out.write("    $(\"#coordinates\").css({ top: y + 10, left: x + 10 }).show();\r\n");
      out.write("    $(this).addClass(\"selectDetail\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function hidePopup() {\r\n");
      out.write("    $(\".selectDetail\").removeClass(\"selectDetail\");\r\n");
      out.write("    $(\"#coordinates\").hide();\r\n");
      out.write("    $(this).hide();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function filterByName() {\r\n");
      out.write("    const search = $(this).val().toLowerCase();\r\n");
      out.write("    $(\".table_line tbody tr\").each(function () {\r\n");
      out.write("        $(this).toggle($(this).find(\"td:eq(1)\").text().toLowerCase().includes(search));\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function filterByKind() {\r\n");
      out.write("    const val = $(this).val();\r\n");
      out.write("    if (val === \"전체\") return location.reload();\r\n");
      out.write("\r\n");
      out.write("    $(\".table_line tbody tr\").hide().filter(function () {\r\n");
      out.write("        return $(this).find(\"td:eq(5)\").text() === val;\r\n");
      out.write("    }).show();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function toggleReturnRows() {\r\n");
      out.write("    showReturnHidden = !showReturnHidden;\r\n");
      out.write("    $(\"#inventory_list tr\").each(function () {\r\n");
      out.write("        const txt = $(this).find(\"td:nth-child(11) button\").text();\r\n");
      out.write("        if (txt === \"반품됨\") $(this).toggle(!showReturnHidden);\r\n");
      out.write("    });\r\n");
      out.write("    $(\"#toggleText\").text(showReturnHidden ? \"반품 ON\" : \"반품 OFF\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function keyDetailAction(e) {\r\n");
      out.write("    const selected = $(\"#inventory_list tr.selectDetail\");\r\n");
      out.write("    if (!selected.length) return;\r\n");
      out.write("    if (e.key.toUpperCase() === \"D\") requestSaleRecord();\r\n");
      out.write("    if (e.key.toUpperCase() === \"E\") requestPaymentRecord();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function requestSaleRecord() {\r\n");
      out.write("    const val = $(\".selectDetail td:eq(1)\").text();\r\n");
      out.write("    $.post(\"Respectively_saleRecord.jsp\", { value: val }, function (res) {\r\n");
      out.write("        $(\"#detailInfo_popup\").html(res).show();\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function requestPaymentRecord() {\r\n");
      out.write("    const val = $(\".selectDetail td:eq(1)\").text();\r\n");
      out.write("    $.post(\"Respectively_payment.jsp\", { value: val }, function (res) {\r\n");
      out.write("        $(\"#paymentInto_popup\").html(res).show();\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/** 동일 제품 접기 기능 초기 적용 */\r\n");
      out.write("function showFirstToggleButton() {\r\n");
      out.write("    const rows = $(\"#inventory_list tr\").toArray();\r\n");
      out.write("    const group = {};\r\n");
      out.write("\r\n");
      out.write("    rows.forEach(row => {\r\n");
      out.write("        const name = row.cells[1].textContent;\r\n");
      out.write("        if (!group[name]) group[name] = [];\r\n");
      out.write("        group[name].push(row);\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // 첫 row에만 토글 버튼\r\n");
      out.write("    for (const name in group) {\r\n");
      out.write("        const arr = group[name];\r\n");
      out.write("        arr.forEach((r, i) => {\r\n");
      out.write("            const btn = $(r).find(\".toggle-details\");\r\n");
      out.write("            btn.toggle(i === 0);\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
