/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.34
 * Generated at: 2026-01-15 12:50:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;
import java.util.*;
import java.text.*;
import java.sql.*;
import java.sql.*;

public final class inventory_005fExhaustion_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/DBconnection.jsp", Long.valueOf(1768386619785L));
    _jspx_dependants.put("/sessionManager.jsp", Long.valueOf(1768386620471L));
    _jspx_dependants.put("/DBclose.jsp", Long.valueOf(1768386619783L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(8);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");

String dbUser = (String) session.getAttribute("id");
String jdbcDriver = (String) session.getAttribute("dbName");
String dbPwd = (String) session.getAttribute("password");

if (dbUser == null || jdbcDriver == null || dbPwd == null) {
    response.sendRedirect("login.jsp");
    return;
}

Connection conn = null;

try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    conn = DriverManager.getConnection(jdbcDriver, dbUser, dbPwd);
} catch (Exception e) {
    e.printStackTrace();
}

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

String dbName = (session != null) ? (String) session.getAttribute("dbName") : null;
String id = (session != null) ? (String) session.getAttribute("id") : null;
String password = (session != null) ? (String) session.getAttribute("password") : null;

/* out.println(password);
out.println(dbName);
out.println(id);
out.println(password); */

String idSortation = (session != null) ? (String) session.getAttribute("idSortation") : null;
if (id == null || dbName == null) {
	response.sendRedirect("login.jsp");
	return;
}

jdbcDriver = dbName;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Inventory Index</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"sale/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"sale-body\">\r\n");
      out.write("	<div id=\"warningBox\">\r\n");
      out.write("		<h3>🚨 재고 부족 경고</h3>\r\n");
      out.write("		<div id=\"warningList\"></div>\r\n");
      out.write("		<button id=\"closeWarning\">닫기</button>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"wrap\" class=\"wrap-container\">\r\n");
      out.write("		<header>\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("		</header>\r\n");
      out.write("		<input type=\"text\" id=\"SerialNumber\" name=\"SerialNumber\"\r\n");
      out.write("			autofocus=\"autofocus\"\r\n");
      out.write("			oninput=\"this.value=this.value.replace(/[^0-9]/g,'')\"\r\n");
      out.write("			autocomplete=\"off\">\r\n");
      out.write("\r\n");
      out.write("		<!-- 제목 -->\r\n");
      out.write("		<div class=\"sale-title-area\">\r\n");
      out.write("			<h1>제품 판매</h1>\r\n");
      out.write("			<button type=\"button\" id=\"downloadStatement\">거래명세표[F8]</button>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- 모든 테이블을 하나처럼 보이게 하기 위한 스타일 조정 -->\r\n");
      out.write("		<div id=\"data\" class=\"data layout-grid\">\r\n");
      out.write("			<div class=\"rightUI right-ui-area\">\r\n");
      out.write("				<div class=\"consumerInfo\">\r\n");
      out.write("					<div class=\"coolinput\">\r\n");
      out.write("						<label for=\"input\" class=\"text\">Name:</label> <input type=\"text\"\r\n");
      out.write("							placeholder=\"고객명을 입력해주세요[선택]\" name=\"input\" class=\"memberName\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<input type=\"text\" name=\"text\" placeholder=\"YY/MMM/DD\"\r\n");
      out.write("						class=\"scheduleDate\" pattern=\"\\d{2}/\\d{2}/\\d{2}\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- 첫 번째 테이블(헤더) -->\r\n");
      out.write("				<table class=\"table_line\">\r\n");
      out.write("					<colgroup>\r\n");
      out.write("						<col width=\"7%\">\r\n");
      out.write("						<col width=\"20%\">\r\n");
      out.write("						<col width=\"6%\">\r\n");
      out.write("						<col width=\"9%\">\r\n");
      out.write("						<col width=\"4%\">\r\n");
      out.write("						<col width=\"9%\">\r\n");
      out.write("						<col width=\"9%\">\r\n");
      out.write("					</colgroup>\r\n");
      out.write("					<thead>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th>제품코드</th>\r\n");
      out.write("							<th>제품명</th>\r\n");
      out.write("							<th>규격</th>\r\n");
      out.write("							<th>가격</th>\r\n");
      out.write("							<th>수량</th>\r\n");
      out.write("							<th>유통기한</th>\r\n");
      out.write("							<th>작업</th>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</thead>\r\n");
      out.write("				</table>\r\n");
      out.write("\r\n");
      out.write("				<!-- 두 번째 테이블 (상품 리스트) -->\r\n");
      out.write("				<div id=\"scrollTable\" class=\"scroll-table-area\">\r\n");
      out.write("					<table class=\"table_line sale-header-table\">\r\n");
      out.write("					<colgroup>\r\n");
      out.write("						<col width=\"7%\">\r\n");
      out.write("						<col width=\"20%\">\r\n");
      out.write("						<col width=\"6%\">\r\n");
      out.write("						<col width=\"9%\">\r\n");
      out.write("						<col width=\"4%\">\r\n");
      out.write("						<col width=\"9%\">\r\n");
      out.write("						<col width=\"9%\">\r\n");
      out.write("					</colgroup>\r\n");
      out.write("						<tbody id=\"table_body\">\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td style=\"display: none;\"><input type=\"text\"\r\n");
      out.write("									name=\"standard\" class=\"standard Calculation_standard\">\r\n");
      out.write("									<input type=\"text\" name=\"Buyingprice\"\r\n");
      out.write("									class=\"Buyingprice Calculation_Buyingprice\"\r\n");
      out.write("									oninput=\"this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\\..*)\\./g, '$1');\">\r\n");
      out.write("									<input type=\"text\" name=\"price\" class=\"price Calculation_price\"\r\n");
      out.write("									oninput=\"this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\\..*)\\./g, '$1');\"></td>\r\n");
      out.write("								<td><input type=\"text\" name=\"SerialNumber\"\r\n");
      out.write("									class=\"SerialNumber\" readonly></td>\r\n");
      out.write("								<td><input type=\"text\" name=\"medicineName\"\r\n");
      out.write("									class=\"medicineName\"></td>\r\n");
      out.write("								<td><input type=\"text\" name=\"standard\" id=\"standard\"\r\n");
      out.write("									class=\"standard\"></td>\r\n");
      out.write("								<td style=\"display:none;\"><input type=\"text\" name=\"Buyingprice\" id=\"Buyingprice\"\r\n");
      out.write("									class=\"Buyingprice input_Buyingprice\"\r\n");
      out.write("									oninput=\"this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\\..*)\\./g, '$1');\"></td>\r\n");
      out.write("								<td><input type=\"text\" name=\"price\" id=\"price\"\r\n");
      out.write("									class=\"price input_price\"\r\n");
      out.write("									oninput=\"this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\\..*)\\./g, '$1');\"></td>\r\n");
      out.write("								<td><input type=\"text\" name=\"inventory\" class=\"inventory\"\r\n");
      out.write("									oninput=\"this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\\..*)\\./g, '$1');\"></td>\r\n");
      out.write("								<td><input type=\"text\" name=\"DeliveryDate\"\r\n");
      out.write("									class=\"DeliveryDate\"\r\n");
      out.write("									oninput=\"this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\\..*)\\./g, '$1');\"\r\n");
      out.write("									readonly></td>\r\n");
      out.write("								<td>\r\n");
      out.write("									<button type=\"button\" onclick=\"removeRow(this)\">입력란 제거</button>\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</tbody>\r\n");
      out.write("					</table>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<!-- 추가 테이블들(총합계 및 판매 버튼 등) -->\r\n");
      out.write("				<table class=\"table_line footTable\">\r\n");
      out.write("					<tbody id=\"generalMedicine\">\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>할인 가격</td>\r\n");
      out.write("							<td><input type=\"text\" class=\"clientName\"></td>\r\n");
      out.write("							<td>일반의약품</td>\r\n");
      out.write("							<td><input type=\"text\" id=\"generalPrice\"\r\n");
      out.write("								oninput=\"this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\\..*)\\./g, '$1');\">\r\n");
      out.write("								원</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</tbody>\r\n");
      out.write("					<tbody id=\"preparations\">\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td colspan=\"2\">\r\n");
      out.write("								<div>\r\n");
      out.write("									<input type=\"button\" value=\"100\" class=\"discount-btn\">\r\n");
      out.write("									<input type=\"button\" value=\"500\" class=\"discount-btn\">\r\n");
      out.write("									<input type=\"button\" value=\"1000\" class=\"discount-btn\">\r\n");
      out.write("									<input type=\"button\" value=\"5000\" class=\"discount-btn\">\r\n");
      out.write("									<input type=\"button\" value=\"10000\" class=\"discount-btn\">\r\n");
      out.write("								</div>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>조제의약품</td>\r\n");
      out.write("							<td><input type=\"text\" id=\"medicinePrice\"\r\n");
      out.write("								oninput=\"this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\\..*)\\./g, '$1');\">\r\n");
      out.write("								원</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</tbody>\r\n");
      out.write("					<tbody id=\"dbInsert\">\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td colspan=\"2\">총합계</td>\r\n");
      out.write("							<td colspan=\"2\"><span id=\"totalPrice\">0</span>원</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td colspan=\"4\"><button type=\"button\" id=\"exhaustionInv\">판매</button></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</tbody>\r\n");
      out.write("				</table>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"leftUI left-ui-area\">\r\n");
      out.write("				<div class=\"herbalSet\">\r\n");
      out.write("					<table class=\"regularTable\">\r\n");
      out.write("						<colgroup>\r\n");
      out.write("							<col width=\"25%\">\r\n");
      out.write("							<col width=\"25%\">\r\n");
      out.write("							<col width=\"25%\">\r\n");
      out.write("							<col width=\"25%\">\r\n");
      out.write("						</colgroup>\r\n");
      out.write("						<thead>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<th colspan=\"4\">\r\n");
      out.write("									<div class=\"leftLid\">일반</div> 만들기\r\n");
      out.write("									<div class=\"rightLid\">세트</div>\r\n");
      out.write("								</th>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</thead>\r\n");
      out.write("						<tbody>\r\n");
      out.write("							<tr>\r\n");
      out.write("								");

								PreparedStatement pstmt1 = null;
								ResultSet rs1 = null;
								try {
									// 데이터 조회
									String sql = "SELECT setName FROM productSet" + idSortation;
									pstmt1 = conn.prepareStatement(sql);
									rs1 = pstmt1.executeQuery();
									int count = 0;
									while (rs1.next()) {
										String medicineName = rs1.getString("setName");

										if (count % 4 == 0) { // 4개마다 새로운 <tr> 시작
									if (count != 0) {
								
      out.write("\r\n");
      out.write("							</tr>\r\n");
      out.write("							");

							} // 이전 tr 닫기
							
      out.write("\r\n");
      out.write("							<tr>\r\n");
      out.write("								");

								}
								
      out.write("\r\n");
      out.write("								<td>");
      out.print(medicineName);
      out.write("</td>\r\n");
      out.write("								");

								count++;
								}
								if (count % 4 != 0) {
								
      out.write("\r\n");
      out.write("							</tr>\r\n");
      out.write("							");

							} // 마지막 tr 닫기
							
      out.write("\r\n");
      out.write("							");

							} catch (Exception e) {
							e.printStackTrace();
							} finally {
							try {
								if (pstmt1 != null)
									pstmt1.close();
							} catch (Exception ignored) {
							}
							try {
								if (rs1 != null)
									rs1.close();
							} catch (Exception ignored) {
							}
							}
							
      out.write("\r\n");
      out.write("						</tbody>\r\n");
      out.write("					</table>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"regularSet\">\r\n");
      out.write("					<!-- 					<div class=\"button\">\r\n");
      out.write("						<p class=\"btnText\">한약세트</p>\r\n");
      out.write("						<div class=\"btnTwo\">\r\n");
      out.write("							<p class=\"btnText2\">만들기</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div> -->\r\n");
      out.write("					<table class=\"regularTable\">\r\n");
      out.write("						<thead>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<th colspan=\"4\">\r\n");
      out.write("									<div class=\"leftLid\">단일</div> 만들기\r\n");
      out.write("									<div class=\"rightLid\">세트</div>\r\n");
      out.write("								</th>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</thead>\r\n");
      out.write("						<tbody>\r\n");
      out.write("							<tr>\r\n");
      out.write("								");

								PreparedStatement pstmt = null;
								ResultSet rs = null;
								try {
									String sql = "SELECT setName FROM regularSet" + idSortation;
									pstmt = conn.prepareStatement(sql);
									rs = pstmt.executeQuery();
									int count = 0;
									while (rs.next()) {
										String setName = rs.getString("setName");

										if (count % 4 == 0) { // 4개마다 새로운 <tr> 시작
									if (count != 0) {
								
      out.write("\r\n");
      out.write("							</tr>\r\n");
      out.write("							");

							} // 이전 tr 닫기
							
      out.write("\r\n");
      out.write("							<tr>\r\n");
      out.write("								");

								}
								
      out.write("\r\n");
      out.write("								<td>");
      out.print(setName);
      out.write("</td>\r\n");
      out.write("								");

								count++;
								}
								if (count % 4 != 0) {
								
      out.write("\r\n");
      out.write("							</tr>\r\n");
      out.write("							");

							} // 마지막 tr 닫기
							
      out.write("\r\n");
      out.write("							");

							} catch (Exception e) {
							e.printStackTrace();
							} finally {
							try {
								if (rs != null)
									rs.close();
							} catch (Exception ignored) {
							}
							try {
								if (pstmt != null)
									pstmt.close();
							} catch (Exception ignored) {
							}
							}
							
      out.write("\r\n");
      out.write("							");
      out.write('\r');
      out.write('\n');

    try {
        if (conn != null && !conn.isClosed()) {
            conn.close();
        }
    } catch (Exception ignored) {}

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("						</tbody>\r\n");
      out.write("					</table>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"popup\" class=\"popup-window\">\r\n");
      out.write("			<h3>검색 결과</h3>\r\n");
      out.write("			<table id=\"popup-table\" class=\"popup-table\">\r\n");
      out.write("				<colgroup>\r\n");
      out.write("					<col style=\"width: 600px\">\r\n");
      out.write("					<col style=\"width: 200px\">\r\n");
      out.write("					<col style=\"width: 100px\">\r\n");
      out.write("					<col style=\"width: 150px\">\r\n");
      out.write("					<col style=\"width: 150px\">\r\n");
      out.write("					<col style=\"width: 150px\">\r\n");
      out.write("					<col style=\"width: 150px\">\r\n");
      out.write("				</colgroup>\r\n");
      out.write("				<thead>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th style=\"border: 1px solid #ccc; padding: 5px;\">제품명</th>\r\n");
      out.write("						<th style=\"border: 1px solid #ccc; padding: 5px;\">회사명</th>\r\n");
      out.write("						<th style=\"border: 1px solid #ccc; padding: 5px;\">재고</th>\r\n");
      out.write("						<th style=\"border: 1px solid #ccc; padding: 5px;\">종류</th>\r\n");
      out.write("						<th style=\"border: 1px solid #ccc; padding: 5px;\">일련번호</th>\r\n");
      out.write("						<th style=\"border: 1px solid #ccc; padding: 5px;\">입고 날짜</th>\r\n");
      out.write("						<th style=\"border: 1px solid #ccc; padding: 5px;\">유통기한</th>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</thead>\r\n");
      out.write("				<tbody id=\"popup-content\"></tbody>\r\n");
      out.write("			</table>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"checkInv\" class=\"checkinv-box\">\r\n");
      out.write("		<h2>판매 제품 재확인</h2>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"medicineTable\">\r\n");
      out.write("		<table id=\"selTable\">\r\n");
      out.write("			<thead>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>제품번호</th>\r\n");
      out.write("					<th>제품명</th>\r\n");
      out.write("					<!-- <th>사입가</th> -->\r\n");
      out.write("					<th>판매가</th>\r\n");
      out.write("					<th>수량</th>\r\n");
      out.write("					<th>규격</th>\r\n");
      out.write("					<th>유통기한</th>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</thead>\r\n");
      out.write("			<tbody></tbody>\r\n");
      out.write("		</table>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"statementTable\"></div>\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdnjs.cloudflare.com/ajax/libs/xlsx-populate/1.21.0/xlsx-populate.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdnjs.cloudflare.com/ajax/libs/jszip/3.7.1/jszip.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/2.0.5/FileSaver.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("	\r\n");
      out.write("	$(document).ready(function() {\r\n");
      out.write("		$(document).on(\"click\", \"#checkInv .table_line.cloned td\",  function () {\r\n");
      out.write("			$(this).closest(\"tr\").toggleClass(\"checkList\");\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("		$(\"#warningBox\").on(\"click\", function(){\r\n");
      out.write("			location.href = \"index2.jsp?autoClick=true\";\r\n");
      out.write("		});\r\n");
      out.write("		window.showWarningBox = function (warnings) {\r\n");
      out.write("			  const box  = document.getElementById(\"warningBox\");\r\n");
      out.write("			  const list = document.getElementById(\"warningList\");\r\n");
      out.write("			  if (!box || !list) return;\r\n");
      out.write("\r\n");
      out.write("			  list.innerHTML = \"\";\r\n");
      out.write("\r\n");
      out.write("			  if (!warnings || warnings.length === 0) {\r\n");
      out.write("			    list.innerHTML = \"<div>✅ 모든 재고가 충분합니다.</div>\";\r\n");
      out.write("			  } else {\r\n");
      out.write("			    warnings.forEach(w => {\r\n");
      out.write("			      if (typeof w === \"string\") {\r\n");
      out.write("			        try {\r\n");
      out.write("			          w = JSON.parse(w);\r\n");
      out.write("			        } catch (err) {\r\n");
      out.write("			          console.warn(\"JSON 재파싱 실패:\", err, w);\r\n");
      out.write("			          return;\r\n");
      out.write("			        }\r\n");
      out.write("			      }\r\n");
      out.write("\r\n");
      out.write("			      const name = w.medicineName || w.medicine_name || w.medicine || \"(이름 없음)\";\r\n");
      out.write("			      const standard = w.standard || \"-\";\r\n");
      out.write("			      const realInv = w.realInv ?? \"?\";\r\n");
      out.write("			      const quantity = w.quantity ?? w.qty ?? w.Quantity ?? \"?\";\r\n");
      out.write("\r\n");
      out.write("			      // 👇 문자열 대신 안전하게 DOM 요소를 직접 생성\r\n");
      out.write("			      const div = document.createElement(\"div\");\r\n");
      out.write("			      const bold = document.createElement(\"b\");\r\n");
      out.write("			      bold.textContent = name;\r\n");
      out.write("\r\n");
      out.write("			      const text1 = document.createTextNode(` (");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${standard}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")`);\r\n");
      out.write("			      const br = document.createElement(\"br\");\r\n");
      out.write("			      const text2 = document.createTextNode(`남은 재고: `);\r\n");
      out.write("\r\n");
      out.write("			      const span = document.createElement(\"span\");\r\n");
      out.write("			      span.style.color = \"red\";\r\n");
      out.write("			      span.textContent = realInv;\r\n");
      out.write("\r\n");
      out.write("			      const text3 = document.createTextNode(` / 권장 수량: ` + quantity);\r\n");
      out.write("\r\n");
      out.write("			      div.appendChild(bold);\r\n");
      out.write("			      div.appendChild(text1);\r\n");
      out.write("			      div.appendChild(br);\r\n");
      out.write("			      div.appendChild(text2);\r\n");
      out.write("			      div.appendChild(span);\r\n");
      out.write("			      div.appendChild(text3);\r\n");
      out.write("\r\n");
      out.write("			      div.style.background = \"#fff\";\r\n");
      out.write("			      div.style.borderLeft = \"4px solid #ff6666\";\r\n");
      out.write("			      div.style.borderRadius = \"6px\";\r\n");
      out.write("			      div.style.marginBottom = \"10px\";\r\n");
      out.write("			      div.style.padding = \"8px\";\r\n");
      out.write("\r\n");
      out.write("			      list.appendChild(div);\r\n");
      out.write("			    });\r\n");
      out.write("			  }\r\n");
      out.write("\r\n");
      out.write("			  box.classList.add(\"show\");\r\n");
      out.write("\r\n");
      out.write("			  document.getElementById(\"closeWarning\").onclick = () => {\r\n");
      out.write("			    box.classList.remove(\"show\");\r\n");
      out.write("			    setTimeout(() => location.reload(), 600);\r\n");
      out.write("			  };\r\n");
      out.write("\r\n");
      out.write("			  setTimeout(() => {\r\n");
      out.write("			    if (box.classList.contains(\"show\")) {\r\n");
      out.write("			      box.classList.remove(\"show\");\r\n");
      out.write("			      setTimeout(() => location.reload(), 600);\r\n");
      out.write("			    }\r\n");
      out.write("			  }, 10000);\r\n");
      out.write("			};\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		if (Notification.permission !== \"granted\") {\r\n");
      out.write("			  Notification.requestPermission();\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("	 	document.addEventListener(\"input\", function (event) {\r\n");
      out.write("		    if (event.target.classList.contains(\"scheduleDate\")) {\r\n");
      out.write("		        let input = event.target.value.replace(/[^0-9]/g, \"\"); // 숫자 외 제거\r\n");
      out.write("		        let formatted = \"\";\r\n");
      out.write("\r\n");
      out.write("		        if (input.length > 2) {\r\n");
      out.write("		            formatted += input.substring(0, 2) + \"/\"; // 첫 번째 슬래시 추가\r\n");
      out.write("		        } else {\r\n");
      out.write("		            formatted += input;\r\n");
      out.write("		        }\r\n");
      out.write("\r\n");
      out.write("		        if (input.length > 4) {\r\n");
      out.write("		            formatted += input.substring(2, 4) + \"/\"; // 두 번째 슬래시 추가\r\n");
      out.write("		            formatted += input.substring(4, 6); // 나머지 추가\r\n");
      out.write("		        } else if (input.length > 2) {\r\n");
      out.write("		            formatted += input.substring(2); // 첫 슬래시 뒤 나머지 추가\r\n");
      out.write("		        }\r\n");
      out.write("		        event.target.value = formatted.slice(0, 8); // 최대 8자리 유지\r\n");
      out.write("		    }\r\n");
      out.write("		});\r\n");
      out.write("	 	\r\n");
      out.write("		$('#selTable').on(\"mouseover\", \"tbody tr\", function(){\r\n");
      out.write("		    const rows = $(\"#selTable tbody tr:visible\");\r\n");
      out.write("		    currentIndex = rows.index(this); // 현재 hover한 행의 인덱스를 기록\r\n");
      out.write("\r\n");
      out.write("		    // 강조 효과 적용\r\n");
      out.write("		    rows.removeClass(\"medicineHover\");\r\n");
      out.write("		    $(rows[currentIndex]).addClass(\"medicineHover\");\r\n");
      out.write("		});\r\n");
      out.write(" 		let selectedRowIndex = -1;\r\n");
      out.write("		let currentIndex = -1;\r\n");
      out.write("		$(document).on(\"keydown\", function(e){\r\n");
      out.write("			if($(\"#selTable\").is(\":visible\")){\r\n");
      out.write("	            const rows = $(\"#selTable tbody tr:visible\");\r\n");
      out.write("\r\n");
      out.write("	            if (e.key === \"ArrowDown\") { // ↓ 키\r\n");
      out.write("	                e.preventDefault();\r\n");
      out.write("	                if (currentIndex < rows.length - 1) {\r\n");
      out.write("	                	currentIndex++;\r\n");
      out.write("	                }\r\n");
      out.write("	            } else if (e.key === \"ArrowUp\") { // ↑ 키\r\n");
      out.write("	                e.preventDefault();\r\n");
      out.write("	                if (currentIndex > 0) {\r\n");
      out.write("	                	currentIndex--;\r\n");
      out.write("	                }\r\n");
      out.write("	            } else if (e.key === \"Enter\" && currentIndex >= 0) { // Enter 키로 선택된 행 처리\r\n");
      out.write("	                e.preventDefault();\r\n");
      out.write("	                const selectedRow = $(rows[currentIndex]); // 현재 강조된 행\r\n");
      out.write("	                selectedRow.click();\r\n");
      out.write("	            }\r\n");
      out.write("\r\n");
      out.write("	            // 강조 효과 업데이트\r\n");
      out.write("	            rows.removeClass(\"medicineHover\"); // 모든 행의 강조 제거\r\n");
      out.write("	            if (currentIndex >= 0) {\r\n");
      out.write("	                $(rows[currentIndex]).addClass(\"medicineHover\"); // 현재 선택된 행에 강조 추가\r\n");
      out.write("	            }\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		async function loadPatchedXlsx(path){\r\n");
      out.write("			  const buf = await fetch(encodeURI(path)).then(r => r.arrayBuffer());\r\n");
      out.write("			  const zip = await JSZip.loadAsync(buf);\r\n");
      out.write("			  return await zip.generateAsync({ type: \"arraybuffer\" });\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("		document.getElementById(\"downloadStatement\").addEventListener(\"click\", async () => {\r\n");
      out.write("			  const templatePath = \"거래명세표.xlsx\";\r\n");
      out.write("			  try {\r\n");
      out.write("			    const buf = await fetch(templatePath).then(r => r.arrayBuffer());\r\n");
      out.write("			    const workbook = await XlsxPopulate.fromDataAsync(buf);\r\n");
      out.write("			    const sheet = workbook.sheet(0);\r\n");
      out.write("			    const rows = document.querySelectorAll(\"#table_body tr\");\r\n");
      out.write("			    const startRow = 8;\r\n");
      out.write("\r\n");
      out.write("			    rows.forEach((tr, i) => {\r\n");
      out.write("			    	  const r = startRow + i; // 원래대로\r\n");
      out.write("\r\n");
      out.write("			    	  const get = cls => {\r\n");
      out.write("			    	    const el = tr.querySelector(\"input.\" + cls);\r\n");
      out.write("			    	    return el?.value?.trim() || \"\";\r\n");
      out.write("			    	  };\r\n");
      out.write("\r\n");
      out.write("			    	  sheet.cell(\"B\" + r).value(get(\"medicineName\"));\r\n");
      out.write("			    	  sheet.cell(\"E\" + r).value(+get(\"inventory\") || null);\r\n");
      out.write("			    	  sheet.cell(\"F\" + r).value(+get(\"input_price\") || null);\r\n");
      out.write("			    	});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			    const blob = await workbook.outputAsync();\r\n");
      out.write("			    const url = window.URL.createObjectURL(new Blob([blob]));\r\n");
      out.write("			    const a = document.createElement(\"a\");\r\n");
      out.write("			    a.href = url;\r\n");
      out.write("			    a.download = \"거래명세표_완성본.xlsx\";\r\n");
      out.write("			    a.click();\r\n");
      out.write("			    window.URL.revokeObjectURL(url);\r\n");
      out.write("			  } catch (err) {\r\n");
      out.write("			    console.error(\"❌ 다운로드 실패\", err);\r\n");
      out.write("			    alert(\"엑셀 생성 중 오류 발생: \" + err.message);\r\n");
      out.write("			  }\r\n");
      out.write("			});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		function openPopupSelect(list) {\r\n");
      out.write("		    const $tbody = $('#selTable tbody');\r\n");
      out.write("		    $tbody.empty();                               // 기존 행 제거\r\n");
      out.write("		    $.each(list, function (i, el) {\r\n");
      out.write("		        const $tr = $('<tr></tr>').append(\r\n");
      out.write("			        $('<td></td>').text(el.SerialNumber),\r\n");
      out.write("			        $('<td></td>').text(el.medicineName),\r\n");
      out.write("			        $('<td style=\"display:none;\"></td>').text(el.Buyingprice),\r\n");
      out.write("			        $('<td></td>').text(el.price),\r\n");
      out.write("			        $('<td></td>').text(el.inventory),\r\n");
      out.write("		            $('<td></td>').text(el.standard),\r\n");
      out.write("		            $('<td></td>').text(el.DeliveryDate)\r\n");
      out.write("		        );\r\n");
      out.write("		        $tr.on('click', function () {\r\n");
      out.write("		            fillInputs(el);	// 행 클릭 → 입력값 채우기\r\n");
      out.write("		            $('.medicineTable').hide();// 테이블 팝업 닫기(필요 시)\r\n");
      out.write("		            addRow();\r\n");
      out.write("		            calculateTotalPrice();\r\n");
      out.write("		        });\r\n");
      out.write("		        $tbody.append($tr);\r\n");
      out.write("		    });\r\n");
      out.write("		    $('.medicineTable').show();        // 레이어 팝업 표시\r\n");
      out.write("		}\r\n");
      out.write("		function focusRightInRow($row, $fromInput, offset = 1) {\r\n");
      out.write("			  // 보이는 td만 대상으로\r\n");
      out.write("			  const $tds = $row.children('td:visible');\r\n");
      out.write("			  const fromIdx = $fromInput.closest('td:visible').index();  // 여기서도 :visible\r\n");
      out.write("			  const targetIdx = fromIdx + offset;\r\n");
      out.write("\r\n");
      out.write("			  if (targetIdx < 0 || targetIdx >= $tds.length) return false;\r\n");
      out.write("\r\n");
      out.write("			  const $target = $tds.eq(targetIdx)\r\n");
      out.write("			    .find('input, select, textarea')\r\n");
      out.write("			    .filter(':visible:enabled')\r\n");
      out.write("			    .first();\r\n");
      out.write("\r\n");
      out.write("			  if ($target.length) {\r\n");
      out.write("			    $target.focus().select();\r\n");
      out.write("			    return true;\r\n");
      out.write("			  }\r\n");
      out.write("			  return false;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		// .medicineName에서 Enter를 눌렀을 때 제품 검색\r\n");
      out.write("		// .medicineName 에서 Enter\r\n");
      out.write("		$(\"#wrap\").on(\"keydown\", \".medicineName\", function (e) {\r\n");
      out.write("		    if (e.key !== \"Enter\") return;\r\n");
      out.write("		    e.preventDefault();\r\n");
      out.write("		    e.stopPropagation(); \r\n");
      out.write("		    e.stopImmediatePropagation();\r\n");
      out.write("		    const $input = $(this);\r\n");
      out.write("		    const keyword = $input.val().trim();\r\n");
      out.write("		    if (keyword === \"\") return;\r\n");
      out.write("		\r\n");
      out.write("		    const $currRow = $input.closest(\"tr\");   // 현재 행\r\n");
      out.write("		    let duplicated = false;\r\n");
      out.write("		    selectedRowIndex = $(this).closest(\"tr\").index();\r\n");
      out.write("		    // 현재 행을 제외하고 중복 확인\r\n");
      out.write("		    $(\"#table_body tr\").not($currRow).each(function () {\r\n");
      out.write("		        if ($(this).find(\".medicineName\").val().trim() === keyword) {\r\n");
      out.write("		            const $inv = $(this).find(\".inventory\");\r\n");
      out.write("		            const now = parseInt($inv.val() || 0, 10);\r\n");
      out.write("		            $inv.val(now + 1);                   // 재고 +1\r\n");
      out.write("		            duplicated = true;\r\n");
      out.write("		            return false;                        // break\r\n");
      out.write("		        }\r\n");
      out.write("		    });\r\n");
      out.write("		\r\n");
      out.write("		    if (duplicated) {\r\n");
      out.write("		        calculateTotalPrice();\r\n");
      out.write("		        return;                                 // 더 할 일 없음\r\n");
      out.write("		    }\r\n");
      out.write("		    $.ajax({\r\n");
      out.write("		        url: 'updateMedicineByName.jsp',\r\n");
      out.write("		        type: 'POST',\r\n");
      out.write("		        dataType: 'json',\r\n");
      out.write("		        data: { medicineName: keyword },\r\n");
      out.write("		        success: function (res) {\r\n");
      out.write("		        	console.log(res);\r\n");
      out.write("		            if ($.isEmptyObject(res)) {          // 결과 0\r\n");
      out.write("		            	  addRow();\r\n");
      out.write("		            	  setTimeout(() => {\r\n");
      out.write("		            	    const ok = focusRightInRow($currRow, $input, 1);\r\n");
      out.write("		            	    if (!ok) {\r\n");
      out.write("		            	      const $fallback = $currRow\r\n");
      out.write("		            	        .find('input, select, textarea')\r\n");
      out.write("		            	        .filter(':visible:enabled')\r\n");
      out.write("		            	        .not($input)\r\n");
      out.write("		            	        .first();\r\n");
      out.write("		            	      if ($fallback.length) $fallback.focus();\r\n");
      out.write("		            	    }\r\n");
      out.write("		            	  }, 0);\r\n");
      out.write("		            	  return;\r\n");
      out.write("		            }\r\n");
      out.write("		            if (res.items) {                     // 규격 ≥ 2\r\n");
      out.write("		            	openPopupSelect(res.items);      // 팝업에서 선택 → fillInputs 호출\r\n");
      out.write("		                return;\r\n");
      out.write("		            }\r\n");
      out.write("		            fillInputs(res);                     // 규격 1개\r\n");
      out.write("		            addRow();\r\n");
      out.write("		            calculateTotalPrice();\r\n");
      out.write("		            const ok = focusRightInRow($currRow, $input, 1);\r\n");
      out.write("            	    if (!ok) {\r\n");
      out.write("	            	      const $fallback = $currRow\r\n");
      out.write("	            	        .find('input, select, textarea')\r\n");
      out.write("	            	        .filter(':visible:enabled')\r\n");
      out.write("	            	        .not($input)\r\n");
      out.write("	            	        .first();\r\n");
      out.write("	            	      if ($fallback.length) $fallback.focus();\r\n");
      out.write("	            	    }\r\n");
      out.write("		        },\r\n");
      out.write("		        error: function (xhr, _, err) {\r\n");
      out.write("		            console.error('AJAX 오류:', err, xhr.responseText);\r\n");
      out.write("		            alert('서버 오류가 발생했습니다.');\r\n");
      out.write("		        }\r\n");
      out.write("		    });\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		//$(\"#checkInv\").draggable();\r\n");
      out.write("		let discountTotal = 0; // 누적 할인 금액\r\n");
      out.write("\r\n");
      out.write("		// 🔹 버튼 클릭 시 할인 금액 추가\r\n");
      out.write("		$(\".discount-btn\").on(\"click\", function () {\r\n");
      out.write("		    let discountAmount = parseFloat($(this).val().replace(/,/g, \"\")); // 버튼의 value 값 (숫자로 변환)\r\n");
      out.write("		    let inputDiscount = parseFloat($(\".clientName\").val().replace(/,/g, \"\")) || 0; // 현재 input 값\r\n");
      out.write("\r\n");
      out.write("		    if (!isNaN(discountAmount)) {\r\n");
      out.write("		        // 할인 금액 누적\r\n");
      out.write("		        discountTotal += discountAmount;\r\n");
      out.write("		        inputDiscount += discountAmount;\r\n");
      out.write("\r\n");
      out.write("		        // 값 업데이트\r\n");
      out.write("		        $(\".clientName\").val(inputDiscount.toLocaleString()); // 누적 할인 금액\r\n");
      out.write("		    }\r\n");
      out.write("\r\n");
      out.write("		    // 최종 가격 업데이트\r\n");
      out.write("		    calculateTotalPrice();\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		// 🔹 input 값이 변경될 때 자동 업데이트\r\n");
      out.write("		$(\".clientName\").on(\"input\", function () {\r\n");
      out.write("		    calculateTotalPrice(); // 할인 값이 변할 때마다 자동으로 업데이트\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		// 🔹 총 가격 & 할인 적용된 가격 계산\r\n");
      out.write("		function calculateTotalPrice() {\r\n");
      out.write("		    let totalPrice = 0; // 최종 계산값\r\n");
      out.write("\r\n");
      out.write("		    // #table_body의 각 행을 반복하여 총 가격 계산\r\n");
      out.write("		    $(\"#table_body tr\").each(function () {\r\n");
      out.write("		        let price = parseFloat($(this).find(\"#price\").val()) || 0; // 가격\r\n");
      out.write("		        let inventory = parseFloat($(this).find(\".inventory\").val()) || 0; // 재고 수량\r\n");
      out.write("\r\n");
      out.write("		        totalPrice += price * inventory;\r\n");
      out.write("		    });\r\n");
      out.write("\r\n");
      out.write("		    // 할인 금액 가져오기\r\n");
      out.write("		    let discountTotal = parseFloat($(\".clientName\").val().replace(/,/g, \"\")) || 0;\r\n");
      out.write("\r\n");
      out.write("		    // 할인 적용된 최종 가격 계산\r\n");
      out.write("		    let updatedTotalPrice = totalPrice - discountTotal;\r\n");
      out.write("\r\n");
      out.write("		    // totalPrice가 0 이하로 내려가지 않도록 제한\r\n");
      out.write("		    if (updatedTotalPrice < 0) {\r\n");
      out.write("		        updatedTotalPrice = 0;\r\n");
      out.write("		    }\r\n");
      out.write("\r\n");
      out.write("		    // 결과 반영 (숫자 포맷 적용)\r\n");
      out.write("		    $(\"#totalPrice\").text(updatedTotalPrice.toLocaleString()); // 남은 가격\r\n");
      out.write("		    $(\"#generalPrice\").val(totalPrice.toLocaleString()); // 총 가격\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		// 🔹 재고가 변할 때 `#generalPrice` 업데이트\r\n");
      out.write("		function updateGeneralPrice() {\r\n");
      out.write("		    let totalGeneralPrice = 0;\r\n");
      out.write("\r\n");
      out.write("		    // #table_body의 각 행을 반복하여 총 가격 계산\r\n");
      out.write("		    $(\"#table_body tr\").each(function () {\r\n");
      out.write("		        let price = parseFloat($(this).find(\"#price\").val()) || 0; // 가격\r\n");
      out.write("		        let inventory = parseFloat($(this).find(\"#inventory\").val()) || 0; // 재고 개수\r\n");
      out.write("\r\n");
      out.write("		        totalGeneralPrice += price * inventory;\r\n");
      out.write("		    });\r\n");
      out.write("\r\n");
      out.write("		    // 총 가격을 #generalPrice에 업데이트\r\n");
      out.write("		    $(\"#generalPrice\").val(totalGeneralPrice.toLocaleString()); // 숫자 포맷 적용\r\n");
      out.write("\r\n");
      out.write("		    // 할인 금액 적용하여 totalPrice 업데이트\r\n");
      out.write("		    let discountTotal = parseFloat($(\".clientName\").val().replace(/,/g, \"\")) || 0;\r\n");
      out.write("		    let updatedTotalPrice = totalGeneralPrice - discountTotal;\r\n");
      out.write("\r\n");
      out.write("		    // totalPrice가 0 이하로 내려가지 않도록 제한\r\n");
      out.write("		    if (updatedTotalPrice < 0) {\r\n");
      out.write("		        updatedTotalPrice = 0;\r\n");
      out.write("		    }\r\n");
      out.write("\r\n");
      out.write("		    // totalPrice 업데이트\r\n");
      out.write("		    $(\"#totalPrice\").text(updatedTotalPrice.toLocaleString());\r\n");
      out.write("		}\r\n");
      out.write("		// 🔹 페이지 로드 시 원래 totalPrice 저장\r\n");
      out.write("		$(document).ready(function () {\r\n");
      out.write("		    let originalTotal = parseFloat($(\"#totalPrice\").text().replace(/,/g, \"\")) || 0;\r\n");
      out.write("		    $(\"#totalPrice\").attr(\"data-original\", originalTotal); // data-original 속성에 저장\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		document.querySelector(\"#table_body\").addEventListener(\"keydown\", function(event) {\r\n");
      out.write("		    if (\r\n");
      out.write("		        event.key === \"Enter\" &&\r\n");
      out.write("		        !event.target.classList.contains(\"medicineName\")\r\n");
      out.write("		    ) {\r\n");
      out.write("		        event.preventDefault();\r\n");
      out.write("		        $(\"#SerialNumber\").focus();\r\n");
      out.write("		    }\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		function addCommas(number) {\r\n");
      out.write("		    return number.toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, \",\");\r\n");
      out.write("		}\r\n");
      out.write("		document.addEventListener(\"keydown\", function(event) {\r\n");
      out.write("		    if (event.key === \"!\") { // 바코드가 \"!\"로 시작하면\r\n");
      out.write("		        event.preventDefault(); // 기본 입력 방지\r\n");
      out.write("		        document.getElementById(\"SerialNumber\").focus(); // #SerialNumber로 포커스 이동\r\n");
      out.write("		    }\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		function setInputs(data){\r\n");
      out.write("		    var lastRow = $(\"#table_body tr:last-child\");\r\n");
      out.write("		    lastRow.find(\".medicineName\").val(data.medicineName);\r\n");
      out.write("		    lastRow.find(\".Buyingprice\").val(data.Buyingprice);\r\n");
      out.write("		    lastRow.find(\".price\").val(data.price);\r\n");
      out.write("		    lastRow.find(\".inventory\").val(data.inventory);\r\n");
      out.write("		    lastRow.find(\".SerialNumber\").val(\"한약세트\");\r\n");
      out.write("		}\r\n");
      out.write("		function setInputd(data){\r\n");
      out.write("		    var lastRow = $(\"#table_body tr:last-child\");\r\n");
      out.write("		    lastRow.find(\".medicineName\").val(data.setName);\r\n");
      out.write("		    lastRow.find(\".Buyingprice\").val(data.Buyingprice);\r\n");
      out.write("		    lastRow.find(\".price\").val(data.price);\r\n");
      out.write("		    lastRow.find(\".inventory\").val(data.inventory);\r\n");
      out.write("		    lastRow.find(\".SerialNumber\").val(\"일반세트\");\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		let isInside = false;  // 패널이 닫히지 않도록 하는 플래그\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		//세트 만들기 클리커\r\n");
      out.write(" 		$(\".herbalSet thead tr th\").on(\"click\", function(){\r\n");
      out.write(" 			location.href='setMake.jsp';  \r\n");
      out.write(" 		});\r\n");
      out.write(" 		$(\".regularSet thead tr th\").on(\"click\", function(){\r\n");
      out.write(" 			location.href='setMake2.jsp';  \r\n");
      out.write(" 		});\r\n");
      out.write("		\r\n");
      out.write("		//한약세트 클릭 이벤트들\r\n");
      out.write("$(\".leftUI .regularSet .regularTable tr td\").on(\"click\", function() {\r\n");
      out.write("    var clickName = $(this).text(); // 클릭한 td의 텍스트\r\n");
      out.write("    console.log(\"클릭한 이름:\", clickName);\r\n");
      out.write("\r\n");
      out.write("    $.ajax({\r\n");
      out.write("        url: \"regularAddPrice.jsp\", // JSP 경로\r\n");
      out.write("        method: \"POST\",\r\n");
      out.write("        data: { clickName: clickName }, // 서버에 전달할 데이터\r\n");
      out.write("        success: function(response) {\r\n");
      out.write("            console.log(\"AJAX Response:\", response); // 응답 확인\r\n");
      out.write("\r\n");
      out.write("            try {\r\n");
      out.write("                var jsonData = typeof response === \"string\" ? JSON.parse(response) : response;\r\n");
      out.write("                var medicineName = jsonData.setName;\r\n");
      out.write("\r\n");
      out.write("                var found = false;\r\n");
      out.write("\r\n");
      out.write("                var targetName = $.trim(jsonData.medicineName || jsonData.setName || clickName);\r\n");
      out.write("\r\n");
      out.write("                $(\"#scrollTable .table_line tr\").each(function () {\r\n");
      out.write("                  var $medicineInput  = $(this).find(\".medicineName\"); // input\r\n");
      out.write("                  var $inventoryInput = $(this).find(\".inventory\");    // input\r\n");
      out.write("                  if (!$medicineInput.length || !$inventoryInput.length) return;\r\n");
      out.write("\r\n");
      out.write("                  var rowMedicineName = $.trim($medicineInput.val() || \"\"); // input value만\r\n");
      out.write("                  if (rowMedicineName === targetName) {\r\n");
      out.write("                    var currentInventory = parseInt($inventoryInput.val(), 10);\r\n");
      out.write("                    if (isNaN(currentInventory)) currentInventory = 0;\r\n");
      out.write("                    $inventoryInput.val(currentInventory + 1);\r\n");
      out.write("                    found = true;\r\n");
      out.write("                    return false; // break\r\n");
      out.write("                  }\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                if (!found) {\r\n");
      out.write("                    setInputs(jsonData); // 데이터 입력 함수 호출\r\n");
      out.write("                    addRow();\r\n");
      out.write("                }\r\n");
      out.write("                calculateTotalPrice(); // 총 가격 다시 계산\r\n");
      out.write("            } catch (e) {\r\n");
      out.write("                console.error(\"JSON parsing error:\", e, response);\r\n");
      out.write("            }\r\n");
      out.write("        },\r\n");
      out.write("        error: function(xhr, status, error) {\r\n");
      out.write("            console.error(\"AJAX request failed:\", xhr.status, xhr.responseText);\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		//일반세트 클릭 이벤트들\r\n");
      out.write("		$(\".leftUI .herbalSet .regularTable tr td\").on(\"click\", function() {\r\n");
      out.write("    		var clickName = $(this).text(); // 클릭한 td의 텍스트\r\n");
      out.write("    		$.ajax({\r\n");
      out.write("    	    	url: \"herbaAddPrice.jsp\", // JSP 경로\r\n");
      out.write("    	    	method: \"POST\",\r\n");
      out.write("    	    	data: { clickName: clickName }, // 서버에 전달할 데이터\r\n");
      out.write("    	    	success: function(response) {\r\n");
      out.write("    	    	    console.log(\"AJAX Response:\", response); // 응답 내용 확인\r\n");
      out.write("    	    	    try {\r\n");
      out.write("    	                var jsonData = typeof response === \"string\" ? JSON.parse(response) : response;\r\n");
      out.write("    	                var medicineName = jsonData.setName.trim();\r\n");
      out.write("						console.log(medicineName);\r\n");
      out.write("    	                var found = false;\r\n");
      out.write("\r\n");
      out.write("    	                $(\"#scrollTable .table_line tr\").each(function(index) {\r\n");
      out.write("    	                    var $medicineInput = $(this).find(\".medicineName\"); // 2번째 td 안의 input\r\n");
      out.write("    	                    var $inventoryInput = $(this).find(\".inventory\"); // 6번째 td 안의 input\r\n");
      out.write("    	                    console.log($medicineInput);\r\n");
      out.write("    	                    console.log($inventoryInput);\r\n");
      out.write("\r\n");
      out.write("    	                    if ($medicineInput.length && $inventoryInput.length) {\r\n");
      out.write("    	                        var rowMedicineName = $medicineInput.val().trim();\r\n");
      out.write("\r\n");
      out.write("    	                        if (rowMedicineName === medicineName) {\r\n");
      out.write("    	                            var currentInventory = parseInt($inventoryInput.val().trim(), 10) || 0;\r\n");
      out.write("\r\n");
      out.write("    	                            $inventoryInput.val(currentInventory + 1); // inventory +1\r\n");
      out.write("    	                            found = true;\r\n");
      out.write("    	                            return false; // `each` 루프 중지\r\n");
      out.write("    	                        }\r\n");
      out.write("    	                    }\r\n");
      out.write("    	                });\r\n");
      out.write("\r\n");
      out.write("    	                if (!found) {\r\n");
      out.write("    	                	setInputd(jsonData); // 데이터 입력 함수 호출\r\n");
      out.write("    	                    addRow();\r\n");
      out.write("    	                }\r\n");
      out.write("    	                calculateTotalPrice(); // 총 가격 다시 계산\r\n");
      out.write("    	            } catch (e) {\r\n");
      out.write("    	                console.error(\"JSON parsing error:\", e, response);\r\n");
      out.write("    	            }\r\n");
      out.write("    	        },\r\n");
      out.write("    	        error: function(xhr, status, error) {\r\n");
      out.write("    	            console.error(\"AJAX request failed:\", xhr.status, xhr.responseText);\r\n");
      out.write("    	        }\r\n");
      out.write("		    });\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		// 조제의약품 가격이 변경될 때마다 총 가격을 다시 계산\r\n");
      out.write("		$(\"#medicinePrice\").on(\"input\", function() {\r\n");
      out.write("		    var medicinePrice = parseFloat($(this).val()) || 0; // 입력된 가격을 가져오고, NaN일 경우 0으로 설정\r\n");
      out.write("		    var totalPrice = 0;\r\n");
      out.write("\r\n");
      out.write("		    // #table_body의 각 행을 반복하여 총 가격 계산\r\n");
      out.write("		    $(\"#table_body tr\").each(function() {\r\n");
      out.write("		        var price = parseFloat($(this).find(\".price\").val());\r\n");
      out.write("		        var inventory = parseFloat($(this).find(\".inventory\").val());\r\n");
      out.write("		        \r\n");
      out.write("		        // 재고가 있는 경우 총 가격을 계산\r\n");
      out.write("		        if (!isNaN(price) && !isNaN(inventory)) {\r\n");
      out.write("		            totalPrice += price * inventory;\r\n");
      out.write("		        }\r\n");
      out.write("		    });\r\n");
      out.write("\r\n");
      out.write("		    // 새로운 총 가격에 medicinePrice를 더함\r\n");
      out.write("		    totalPrice += medicinePrice; // medicinePrice가 총 가격에 포함됨\r\n");
      out.write("\r\n");
      out.write("		    // 총 가격을 업데이트\r\n");
      out.write("		    $(\"#totalPrice\").text(totalPrice); // 소수점 2자리까지 표시\r\n");
      out.write("		    //$(\"#generalPrice\").val(totalPrice.toFixed(2)); // #generalPrice도 업데이트\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		// input 요소의 값이 변경될 때마다 총 가격 계산\r\n");
      out.write("		$(document).on(\"input\", \"#table_body input\", calculateTotalPrice);\r\n");
      out.write("\r\n");
      out.write("		var typingTimer; // 타이머 변수\r\n");
      out.write("		var doneTypingInterval = 500; // 0.2초 (200ms)\r\n");
      out.write("\r\n");
      out.write("		var typingTimer; // 전역 변수로 선언하여 타이머를 추적\r\n");
      out.write("\r\n");
      out.write("		$(\"#SerialNumber\").on(\"keyup\", function(event) {\r\n");
      out.write("		    var inputValue = $(this).val(); // 입력된 값\r\n");
      out.write("\r\n");
      out.write("		    // 타이머를 리셋하여 이전 타이머가 남지 않도록 합니다\r\n");
      out.write("		    clearTimeout(typingTimer);\r\n");
      out.write("\r\n");
      out.write("		    if (event.keyCode === 13) { // Enter 키 감지\r\n");
      out.write("		        processInput(inputValue);\r\n");
      out.write("		    } else {\r\n");
      out.write("		        // 0.3초 후 자동으로 Enter 키 동작 실행\r\n");
      out.write("		        typingTimer = setTimeout(function() {\r\n");
      out.write("		            if (inputValue !== \"\") {\r\n");
      out.write("		                processInput(inputValue);\r\n");
      out.write("		            }\r\n");
      out.write("		        }, doneTypingInterval);\r\n");
      out.write("		    }\r\n");
      out.write("\r\n");
      out.write("		    function processInput(inputValue) {\r\n");
      out.write("		        var inventoryIncreased = false; // inventory가 증가되었는지 여부를 나타내는 변수\r\n");
      out.write("\r\n");
      out.write("		        if (inputValue == \"\") {\r\n");
      out.write("		            return false;\r\n");
      out.write("		        }\r\n");
      out.write("\r\n");
      out.write("		        for (var i = 0; i < $(\"#table_body tr\").length; i++) {\r\n");
      out.write("		            if (inputValue === $(\"#table_body tr\").eq(i).find(\".SerialNumber\").val()) {\r\n");
      out.write("		                var currentValue = parseFloat($(\"#table_body tr\").eq(i).find(\".inventory\").val());\r\n");
      out.write("		                var priceValue = parseInt($(\"#table_body tr\").eq(i).find(\"#price\").val());\r\n");
      out.write("		                $(\"#table_body tr\").eq(i).find(\".inventory\").val(currentValue + 1);\r\n");
      out.write("		                inventoryIncreased = true;\r\n");
      out.write("\r\n");
      out.write("		                // 가격(price) 가져오기\r\n");
      out.write("		                var price = parseFloat($(\"#table_body tr\").eq(i).find(\"#price\").val());\r\n");
      out.write("		                // 기존의 총 가격 가져오기\r\n");
      out.write("		                var totalPrice = parseFloat($(\"#totalPrice\").text());\r\n");
      out.write("		                // 새로운 총 가격 계산하여 설정\r\n");
      out.write("		                $(\"#generalPrice\").val(totalPrice + price);\r\n");
      out.write("		                $(\"#totalPrice\").text(totalPrice + price);\r\n");
      out.write("\r\n");
      out.write("		                $(\"#SerialNumber\").val('');\r\n");
      out.write("		                break;\r\n");
      out.write("		            }\r\n");
      out.write("		        }\r\n");
      out.write("\r\n");
      out.write("		        if (!inventoryIncreased) {\r\n");
      out.write("		            $.ajax({\r\n");
      out.write("		                url: \"updateDatabase.jsp\",\r\n");
      out.write("		                method: \"POST\",\r\n");
      out.write("		                data: {\r\n");
      out.write("		                    serialNumber: inputValue\r\n");
      out.write("		                },\r\n");
      out.write("		                success: function(response) {\r\n");
      out.write("		                    if (response && response.SerialNumber) {\r\n");
      out.write("		                        fillInputs(response);\r\n");
      out.write("		                        addRow();\r\n");
      out.write("		                        $(\"#SerialNumber\").val('');\r\n");
      out.write("		                        calculateTotalPrice();\r\n");
      out.write("		                    } else {\r\n");
      out.write("		                        console.log(\"데이터가 없습니다.\");\r\n");
      out.write("		                        $(\"#SerialNumber\").val('');\r\n");
      out.write("		                    }\r\n");
      out.write("		                },\r\n");
      out.write("		                error: function(xhr, status, error) {\r\n");
      out.write("		                    console.error(\"AJAX request failed:\", status, error);\r\n");
      out.write("		                }\r\n");
      out.write("		            });\r\n");
      out.write("		        }\r\n");
      out.write("		        calculateTotalPrice(); // 총 가격 계산\r\n");
      out.write("		    }\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("	});\r\n");
      out.write("	// 방향키 & Enter 이동 로직 (팝업 + 입력 테이블 통합)\r\n");
      out.write("$(document).on(\"keydown\", \"input\", function (e) {\r\n");
      out.write("  const $currentInput = $(this);\r\n");
      out.write("  const $currentTd = $currentInput.closest(\"td:visible\");\r\n");
      out.write("  const $currentTr = $currentInput.closest(\"tr:visible\");\r\n");
      out.write("\r\n");
      out.write("  const $visibleTds = $currentTr.children(\"td:visible\");\r\n");
      out.write("  const visColIndex = $visibleTds.index($currentTd);\r\n");
      out.write("\r\n");
      out.write("  let $targetInput = $();\r\n");
      out.write("\r\n");
      out.write("  if(!$(\"#selTable\").is(\":visible\")){\r\n");
      out.write("	  if (e.key === \"ArrowUp\") {\r\n");
      out.write("	    const $targetTr = $currentTr.prevAll(\"tr:visible\").first();\r\n");
      out.write("	    if ($targetTr.length) {\r\n");
      out.write("	      $targetInput = $targetTr.children(\"td:visible\").eq(visColIndex)\r\n");
      out.write("	        .find(\"input:visible:enabled\").first();\r\n");
      out.write("	    }\r\n");
      out.write("	  } else if (e.key === \"ArrowDown\") {\r\n");
      out.write("	    const $tbody    = $currentTr.parent();\r\n");
      out.write("	    const $lastTr   = $tbody.children(\"tr:visible\").last();\r\n");
      out.write("	    const $targetTr = $currentTr.nextAll(\"tr:visible\").first();\r\n");
      out.write("\r\n");
      out.write("	    if ($targetTr.length) {\r\n");
      out.write("	      if ($targetTr.is($lastTr)) {\r\n");
      out.write("	        // 👉 마지막 행이면 .medicineName으로 이동\r\n");
      out.write("	        $targetInput = $targetTr.find(\"input.medicineName:visible:enabled\").first();\r\n");
      out.write("	      } else {\r\n");
      out.write("	        $targetInput = $targetTr.children(\"td:visible\").eq(visColIndex)\r\n");
      out.write("	          .find(\"input:visible:enabled\").first();\r\n");
      out.write("	      }\r\n");
      out.write("	    }\r\n");
      out.write("	  } else if (e.key === \"ArrowLeft\") {\r\n");
      out.write("	    const el = $currentInput.get(0);\r\n");
      out.write("	    if (el.selectionStart === 0 && visColIndex > 0) {\r\n");
      out.write("	      $targetInput = $visibleTds.eq(visColIndex - 1)\r\n");
      out.write("	        .find(\"input:visible:enabled\").first();\r\n");
      out.write("	    }\r\n");
      out.write("	  } else if (e.key === \"ArrowRight\") {\r\n");
      out.write("	    const el = $currentInput.get(0);\r\n");
      out.write("	    if (el.selectionEnd === el.value.length && visColIndex < $visibleTds.length - 1) {\r\n");
      out.write("	      $targetInput = $visibleTds.eq(visColIndex + 1)\r\n");
      out.write("	        .find(\"input:visible:enabled\").first();\r\n");
      out.write("	    }\r\n");
      out.write("	  } else if (e.key === \"Enter\") {\r\n");
      out.write("	    const $targetTr = $currentTr.nextAll(\"tr:visible\").first();\r\n");
      out.write("	    if ($targetTr.length) {\r\n");
      out.write("	      $targetInput = $targetTr.children(\"td:visible\").eq(visColIndex)\r\n");
      out.write("	        .find(\"input:visible:enabled\").first();\r\n");
      out.write("	    }\r\n");
      out.write("	  } else {\r\n");
      out.write("	    return;\r\n");
      out.write("	  }\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	  \r\n");
      out.write("\r\n");
      out.write("  if ($targetInput.length) {\r\n");
      out.write("    e.preventDefault();\r\n");
      out.write("    $(\"input\").removeClass(\"inputCheckStyle\");\r\n");
      out.write("    $targetInput.addClass(\"inputCheckStyle\").focus().select();\r\n");
      out.write("  }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	$(document).on('keydown', function(event) {\r\n");
      out.write("\r\n");
      out.write("		if ((event.ctrlKey && (event.key === 's' || event.key === 'S')) || event.keyCode == 122) {\r\n");
      out.write("	        event.preventDefault();\r\n");
      out.write("	        $(\"#exhaustionInv\").click(); // #exhaustionInv 버튼의 클릭 이벤트 트리거\r\n");
      out.write("	    }\r\n");
      out.write("	    if(event.keyCode == 122){\r\n");
      out.write("	        event.preventDefault();\r\n");
      out.write("	        $(\"#exhaustionInv\").click();\r\n");
      out.write("	    }\r\n");
      out.write("		if(event.keyCode == 118){\r\n");
      out.write("	        event.preventDefault();\r\n");
      out.write("	        window.location.href=\"inventory_Exhaustion.jsp\";\r\n");
      out.write("	    }\r\n");
      out.write("		if(event.keyCode == 116){\r\n");
      out.write("	        event.preventDefault();\r\n");
      out.write("	    }\r\n");
      out.write("	    if (event.keyCode === 32) {\r\n");
      out.write("\r\n");
      out.write("	        // ✅ 입력 중일 땐 막지 않는다\r\n");
      out.write("	        if ($(event.target).is(\"input, textarea\")) return;\r\n");
      out.write("\r\n");
      out.write("	        event.preventDefault();\r\n");
      out.write("\r\n");
      out.write("	        // 여기서만 checkInv 열기\r\n");
      out.write("	        if ($(\"#checkInv\").is(\":visible\")) return;\r\n");
      out.write("\r\n");
      out.write("	        $(\"#checkInv\").show();\r\n");
      out.write("	        $(\"#checkInv\").stop().animate({ width: \"80vw\", height: \"85vh\" }, 500);\r\n");
      out.write("\r\n");
      out.write("	        setTimeout(function () {\r\n");
      out.write("	            if ($(\"#checkInv\").find(\".cloned\").length === 0) {\r\n");
      out.write("	            	var $cloneTable = $(\".table_line.copyTable\").clone(true);\r\n");
      out.write("	            	$cloneTable.find(\"#table_body\").removeAttr(\"id\");\r\n");
      out.write("	            	$cloneTable.addClass(\"cloned\");\r\n");
      out.write("	            	$(\"#checkInv\").append($cloneTable);\r\n");
      out.write("	            }\r\n");
      out.write("	        }, 500);\r\n");
      out.write("	    }\r\n");
      out.write("		if(event.keyCode == 27){\r\n");
      out.write("			event.preventDefault();\r\n");
      out.write("			if($(\"#checkInv\").is(\":visible\")){\r\n");
      out.write("				if($(\"#checkInv\").find(\".table_line tr\").length != $(\"#checkInv\").find(\".checkList\").length){\r\n");
      out.write("					if(!confirm(\"확인되지 않은 제품이 있습니다. 계속 진행하시겠습니까?\")){\r\n");
      out.write("						return false;\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("	            $(\"#checkInv\").stop().animate({\r\n");
      out.write("	                width: \"1vw\"\r\n");
      out.write("	            }, 500); // 0.5초 동안 너비 확장\r\n");
      out.write("	            $(\"#checkInv\").animate({\r\n");
      out.write("	            	height:\"1vh\"\r\n");
      out.write("	            }, 500);\r\n");
      out.write("	            setTimeout(function(){\r\n");
      out.write("	            	$(\"#checkInv\").hide();\r\n");
      out.write("	            	$(\"#checkInv\").find(\".table_line\").fadeOut();\r\n");
      out.write("	            	$(\"#checkInv\").find(\".cloned\").remove();\r\n");
      out.write("	            }, 500);				\r\n");
      out.write("			}\r\n");
      out.write("			if($(\".medicineTable\").is(\":visible\")){\r\n");
      out.write("				$(\".medicineTable\").hide();\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("	});	\r\n");
      out.write("	\r\n");
      out.write("	function addCommas(number) {\r\n");
      out.write("	    return number.toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, \",\");\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function fillInputs(data) {\r\n");
      out.write("	    var lastRow = $(\"#table_body tr:last-child\");\r\n");
      out.write("	    lastRow.find(\".SerialNumber\").val(data.SerialNumber);\r\n");
      out.write("	    lastRow.find(\".medicineName\").val(data.medicineName);\r\n");
      out.write("	    lastRow.find(\".Buyingprice\").val(data.Buyingprice);\r\n");
      out.write("	    lastRow.find(\".price\").val(data.price);\r\n");
      out.write("	    lastRow.find(\".inventory\").val('1');\r\n");
      out.write("	    lastRow.find(\".kind\").val(data.kind);\r\n");
      out.write("	    lastRow.find(\".standard\").val(data.standard);\r\n");
      out.write("	    lastRow.find(\".receiptDate\").val(data.receiptDate);\r\n");
      out.write("	    lastRow.find(\".DeliveryDate\").val(data.DeliveryDate);\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function addRow() {\r\n");
      out.write("	    var lastRow = $(\"#table_body tr:last-child\").clone();\r\n");
      out.write("	    lastRow.find('input[type=\"text\"]').val('');\r\n");
      out.write("	    lastRow.find('select').val('');\r\n");
      out.write("	    $(\"#table_body\").append(lastRow);\r\n");
      out.write("	    const $box = $(\"#scrollTable\");\r\n");
      out.write("	    $box.scrollTop($box[0].scrollHeight);\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function removeRow(button) {\r\n");
      out.write("	    if ($(\"#wrap .table_line tr\").length <= 4) {\r\n");
      out.write("	        return false;\r\n");
      out.write("	    }\r\n");
      out.write("	    var row = $(button).closest(\"tr\");\r\n");
      out.write("	    if (row.is(':last-child')) {\r\n");
      out.write("	        return false;\r\n");
      out.write("	    }\r\n");
      out.write("	    var price = parseFloat(row.find(\"#price\").val());\r\n");
      out.write("	    let inventory = parseFloat(row.find(\".inventory\").val());\r\n");
      out.write("	    var totalPrice = parseFloat($(\"#totalPrice\").text());\r\n");
      out.write("	    var generalPrice = parseFloat($(\"#generalPrice\").val());\r\n");
      out.write("\r\n");
      out.write("	    // 해당 행의 가격 * 수량을 총 가격과 일반의약품 가격에서 빼기\r\n");
      out.write("	    totalPrice -= price * inventory;\r\n");
      out.write("	    generalPrice -= price * inventory;\r\n");
      out.write("\r\n");
      out.write("	    // 행을 제거\r\n");
      out.write("	    row.remove();\r\n");
      out.write("\r\n");
      out.write("	    // 변경된 총 가격과 일반의약품 가격을 업데이트\r\n");
      out.write("	    $(\"#totalPrice\").text(totalPrice);\r\n");
      out.write("	    $(\"#generalPrice\").val(generalPrice);\r\n");
      out.write("\r\n");
      out.write("	    // 총 가격이 0 미만으로 떨어지지 않도록 처리\r\n");
      out.write("	    if (totalPrice < 0) {\r\n");
      out.write("	        $(\"#totalPrice\").text(\"0\");\r\n");
      out.write("	    }\r\n");
      out.write("	    if (generalPrice < 0) {\r\n");
      out.write("	        $(\"#generalPrice\").val(\"0\");\r\n");
      out.write("	    }\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	$(\"#exhaustionInv\").on(\"click\", function() {\r\n");
      out.write("	    if($(\"#wrap #data #scrollTable .table_line #table_body tr\").length <= 1){\r\n");
      out.write("	        alert(\"판매 제품을 스캔하세요\");\r\n");
      out.write("	        return false;\r\n");
      out.write("	    }\r\n");
      out.write("	    \r\n");
      out.write("	    var rowData = [];\r\n");
      out.write("	    $(\"#table_body tr\").each(function() {\r\n");
      out.write("	        const name = $(this).find(\".medicineName\").val();\r\n");
      out.write("	        const inv = $(this).find(\".inventory\").val();\r\n");
      out.write("	        if (!name || inv === \"\" || inv === null) return;  // ✅ 비어있는 tr만 제외\r\n");
      out.write("\r\n");
      out.write("	        const row = {\r\n");
      out.write("	          serialNumber: $(this).find(\".SerialNumber\").val(),\r\n");
      out.write("	          medicineName: name,\r\n");
      out.write("	          Buyingprice: $(this).find(\".Buyingprice\").val(),\r\n");
      out.write("	          price: $(this).find(\".input_price\").val().trim(),\r\n");
      out.write("	          inventory: inv,\r\n");
      out.write("	          kind: $(this).find(\".kind\").val(),\r\n");
      out.write("	          standard: $(this).find(\"#standard\").val(),\r\n");
      out.write("	          receiptDate: $(this).find(\".receiptDate\").val(),\r\n");
      out.write("	          deliveryDate: $(this).find(\".DeliveryDate\").val(),\r\n");
      out.write("	          memberName: $(\".memberName\").val(),\r\n");
      out.write("	        };\r\n");
      out.write("	        rowData.push(row);\r\n");
      out.write("	    });\r\n");
      out.write("\r\n");
      out.write("	    // 메타데이터 추가\r\n");
      out.write("	    var medicinePrice = $(\"#medicinePrice\").val();\r\n");
      out.write("	    var generalPrice = $(\"#generalPrice\").val();\r\n");
      out.write("	    var discounted = $(\".clientName\").val();\r\n");
      out.write("	    var scheduleDate = $(\".scheduleDate\").val();\r\n");
      out.write("	    rowData.push({ \r\n");
      out.write("	        generalPrice: generalPrice, \r\n");
      out.write("	        medicinePrice: medicinePrice, \r\n");
      out.write("	        discounted: discounted, \r\n");
      out.write("	        scheduleDate: scheduleDate\r\n");
      out.write("	    });\r\n");
      out.write("\r\n");
      out.write("	    // AJAX 요청\r\n");
      out.write("	    $.ajax({\r\n");
      out.write("	        url: \"statistics.jsp\",\r\n");
      out.write("	        method: \"POST\",\r\n");
      out.write("	        contentType: \"application/json\",\r\n");
      out.write("	        data: JSON.stringify(rowData),\r\n");
      out.write("	        dataType: \"json\"\r\n");
      out.write("	      })\r\n");
      out.write("	      .done(function (res) {\r\n");
      out.write("	    	  try {\r\n");
      out.write("	    	    if (typeof res === \"string\") res = JSON.parse(res);\r\n");
      out.write("	    	    if (typeof res.warnings === \"string\") res.warnings = JSON.parse(res.warnings);\r\n");
      out.write("	    	  } catch (e) {\r\n");
      out.write("	    	    console.warn(\"응답 파싱 실패:\", e);\r\n");
      out.write("	    	  }\r\n");
      out.write("\r\n");
      out.write("	    	  console.log(\"✅ 서버 응답 구조 확인:\", res);\r\n");
      out.write("\r\n");
      out.write("	    	  if (res.result === \"success\") {\r\n");
      out.write("	    	    if (res.warnings && res.warnings.length > 0) {\r\n");
      out.write("	    	      alert(\"⚠ 재고 부족 항목이 있습니다!\");\r\n");
      out.write("	    	      showWarningBox(res.warnings);\r\n");
      out.write("	    	      console.log(\"까꿍\");\r\n");
      out.write("	    	      console.log(res.warnings);\r\n");
      out.write("	    	    } else {\r\n");
      out.write("	    	      alert(\"✅ 판매 완료: 모든 재고 정상 차감\");\r\n");
      out.write("	    	      setTimeout(() => location.reload(), 1000);\r\n");
      out.write("	    	    }\r\n");
      out.write("	    	  } else {\r\n");
      out.write("	    	    alert(\"❌ 서버 오류: \" + res.message);\r\n");
      out.write("	    	  }\r\n");
      out.write("	    	})\r\n");
      out.write("	    });\r\n");
      out.write("    // 페이지 로드 시 초기 총 가격 계산\r\n");
      out.write("    updateGeneralPrice();\r\n");
      out.write("\r\n");
      out.write("    // 입력 요소의 값이 변경될 때마다 총 가격 업데이트\r\n");
      out.write("    $(document).on(\"input\", \"#table_body input\", function() {\r\n");
      out.write("        updateGeneralPrice();\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    $(\".plusBtn\").click(function() {\r\n");
      out.write("        var medicineName = $(this).closest('td').find('input[name=\"medicineName\"]').val();\r\n");
      out.write("        console.log(\"Requesting data for medicineName:\", medicineName); // 디버깅 메시지 추가\r\n");
      out.write("        var inventoryIncreased = false; // Inventory increase flag\r\n");
      out.write("\r\n");
      out.write("        $(\"#table_body tr\").each(function() {\r\n");
      out.write("            if (medicineName === $(this).find(\".medicineName\").val()) {\r\n");
      out.write("                var currentValue = parseFloat($(this).find(\".inventory\").val());\r\n");
      out.write("                $(this).find(\".inventory\").val(currentValue + 1);\r\n");
      out.write("                \r\n");
      out.write("                // Update the total price\r\n");
      out.write("                calculateTotalPrice();\r\n");
      out.write("                \r\n");
      out.write("                inventoryIncreased = true;\r\n");
      out.write("                return false; // Break out of the each loop\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        if (!inventoryIncreased) {\r\n");
      out.write("            // Use AJAX to get data and add a new row\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                type: 'POST',\r\n");
      out.write("                url: 'updateMedicineCount.jsp',\r\n");
      out.write("                data: {\r\n");
      out.write("                    medicineName: medicineName\r\n");
      out.write("                },\r\n");
      out.write("                success: function(response) {\r\n");
      out.write("                    console.log(\"Response from server:\", response); // 디버깅 메시지 추가\r\n");
      out.write("                    if (response && response.data) {\r\n");
      out.write("                        insertRowAboveLast(response.data); // 테이블에 새로운 행 추가\r\n");
      out.write("                        calculateTotalPrice(); // 총 가격 재계산\r\n");
      out.write("                    } else {\r\n");
      out.write("                        console.log(\"데이터가 없습니다.\" + medicineName);\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                error: function(xhr, status, error) {\r\n");
      out.write("                    console.error(\"AJAX 요청 실패:\", status, error);\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("    $(\".plus2Btn\").click(function() {\r\n");
      out.write("        var medicineName = $(this).closest('td').find('input[name=\"medicineName\"]').val();\r\n");
      out.write("        console.log(\"Requesting data for medicineName:\", medicineName); // 디버깅 메시지 추가\r\n");
      out.write("        var inventoryIncreased = false; // Inventory increase flag\r\n");
      out.write("\r\n");
      out.write("        $(\"#table_body tr\").each(function() {\r\n");
      out.write("            if (medicineName === $(this).find(\".medicineName\").val()) {\r\n");
      out.write("                var currentValue = parseFloat($(this).find(\".inventory\").val());\r\n");
      out.write("                $(this).find(\".inventory\").val(currentValue + 1);\r\n");
      out.write("                \r\n");
      out.write("                // Update the total price\r\n");
      out.write("                calculateTotalPrice();\r\n");
      out.write("                \r\n");
      out.write("                inventoryIncreased = true;\r\n");
      out.write("                return false; // Break out of the each loop\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        if (!inventoryIncreased) {\r\n");
      out.write("            // Use AJAX to get data and add a new row\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                type: 'POST',\r\n");
      out.write("                url: 'updateVitalCount.jsp',\r\n");
      out.write("                data: {\r\n");
      out.write("                    medicineName: medicineName\r\n");
      out.write("                },\r\n");
      out.write("                success: function(response) {\r\n");
      out.write("                    console.log(\"Response from server:\", response); // 디버깅 메시지 추가\r\n");
      out.write("                    if (response && response.data) {\r\n");
      out.write("                        insertRowAboveLast(response.data); // 테이블에 새로운 행 추가\r\n");
      out.write("                        calculateTotalPrice(); // 총 가격 재계산\r\n");
      out.write("                    } else {\r\n");
      out.write("                        console.log(\"데이터가 없습니다.\" + medicineName);\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                error: function(xhr, status, error) {\r\n");
      out.write("                    console.error(\"AJAX 요청 실패:\", status, error);\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // Function to insert a new row above the last row\r\n");
      out.write("    function insertRowAboveLast(data) {\r\n");
      out.write("        var lastRow = $(\"#table_body tr:last-child\");\r\n");
      out.write("        var newRow = lastRow.clone();\r\n");
      out.write("        newRow.find('#Buyingprice').val(data.Buyingprice);\r\n");
      out.write("        newRow.find('#price').val(data.price);\r\n");
      out.write("        newRow.find('#standard').val(data.standard);\r\n");
      out.write("        lastRow.before(newRow);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    // 팝업 외부 클릭 시 닫기\r\n");
      out.write("    $(document).on(\"click\", function (e) {\r\n");
      out.write("        if (!$(e.target).closest(\"#checkInv\").length) {\r\n");
      out.write("			if($(\"#checkInv\").find(\".table_line tr\").length != $(\"#checkInv\").find(\".checkList\").length){\r\n");
      out.write("				if(!confirm(\"확인되지 않은 제품이 있습니다. 계속 진행하시겠습니까?\")){\r\n");
      out.write("					return false;\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("            $(\"#checkInv\").stop().animate({\r\n");
      out.write("                width: \"1vw\"\r\n");
      out.write("            }, 500); // 0.5초 동안 너비 확장\r\n");
      out.write("            $(\"#checkInv\").animate({\r\n");
      out.write("            	height:\"1vh\"\r\n");
      out.write("            }, 500);\r\n");
      out.write("            setTimeout(function(){\r\n");
      out.write("            	$(\"#checkInv\").hide();\r\n");
      out.write("            	$(\"#checkInv\").find(\".table_line\").fadeOut();\r\n");
      out.write("            	$(\"#checkInv\").find(\".cloned\").remove();\r\n");
      out.write("            }, 500);\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    document.addEventListener(\"keydown\", function(event) {\r\n");
      out.write("        // 이벤트가 발생한 요소가 .standard이고, Enter 키가 눌렸는지 확인\r\n");
      out.write("        if (event.target.classList.contains(\"standard\") && event.key === \"Enter\") {\r\n");
      out.write("            const standardInput = event.target; // 현재 .standard 요소\r\n");
      out.write("            const row = standardInput.closest(\"tr\"); // 현재 요소의 부모 행 가져오기\r\n");
      out.write("\r\n");
      out.write("            // 현재 행에서 필요한 요소들 찾기\r\n");
      out.write("            const calculationStandard = row.querySelector(\".Calculation_standard\");\r\n");
      out.write("            const buyingPriceInput = row.querySelector(\"#Buyingprice\"); // #Buyingprice\r\n");
      out.write("            const priceInput = row.querySelector(\"#price\"); // #price\r\n");
      out.write("            const calculationBuyingPrice = row.querySelector(\".Calculation_Buyingprice\");\r\n");
      out.write("            const calculationPrice = row.querySelector(\".Calculation_price\");\r\n");
      out.write("\r\n");
      out.write("            // 필수 요소 확인\r\n");
      out.write("            if (!calculationStandard || !calculationBuyingPrice || !calculationPrice) {\r\n");
      out.write("                console.error(\"필수 요소가 누락되었습니다.\");\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // 데이터 가져오기\r\n");
      out.write("            const originalStandardValue = parseFloat(calculationStandard.value) || 1; // .Calculation_standard 값\r\n");
      out.write("            const newStandardValue = parseFloat(standardInput.value) || 0; // 새로 입력된 .standard 값\r\n");
      out.write("            const baseBuyingPrice = parseFloat(calculationBuyingPrice.value) || 0; // .Calculation_BuyingPrice 값\r\n");
      out.write("            const basePrice = parseFloat(calculationPrice.value) || 0; // .Calculation_price 값\r\n");
      out.write("\r\n");
      out.write("            // 비율 계산\r\n");
      out.write("            const ratio = newStandardValue / originalStandardValue;\r\n");
      out.write("\r\n");
      out.write("            // 디버깅: 비율 확인\r\n");
      out.write("            console.log(\"계산된 비율:\", ratio);\r\n");
      out.write("\r\n");
      out.write("            // 새로운 값 계산\r\n");
      out.write("            const newBuyingPrice = (baseBuyingPrice * ratio); // 소수점 2자리 고정\r\n");
      out.write("            const newPrice = (basePrice * ratio);\r\n");
      out.write("\r\n");
      out.write("            // 값 업데이트 (text 형식으로 입력)\r\n");
      out.write("            buyingPriceInput.value = newBuyingPrice.toString(); // #Buyingprice에 새로운 값 입력\r\n");
      out.write("            priceInput.value = newPrice.toString(); // #price에 새로운 값 입력\r\n");
      out.write("\r\n");
      out.write("            // 값 변경 디버깅\r\n");
      out.write("            console.log(\"새 BuyingPrice:\", newBuyingPrice);\r\n");
      out.write("            console.log(\"새 Price:\", newPrice);\r\n");
      out.write("\r\n");
      out.write("            // Enter 키 기본 동작 방지\r\n");
      out.write("            event.preventDefault();\r\n");
      out.write("\r\n");
      out.write("            // 값이 변경된 후 총 가격 업데이트\r\n");
      out.write("            updateGeneralPrice();\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("  </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
