/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.34
 * Generated at: 2026-01-16 11:47:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;
import java.util.*;
import java.text.*;
import java.sql.*;
import java.sql.*;

public final class priceRecord_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/DBconnection.jsp", Long.valueOf(1768386619785L));
    _jspx_dependants.put("/sessionManager.jsp", Long.valueOf(1768386620471L));
    _jspx_dependants.put("/DBclose.jsp", Long.valueOf(1768386619783L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(8);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");

String dbUser = (String) session.getAttribute("id");
String jdbcDriver = (String) session.getAttribute("dbName");
String dbPwd = (String) session.getAttribute("password");

if (dbUser == null || jdbcDriver == null || dbPwd == null) {
    response.sendRedirect("login.jsp");
    return;
}

Connection conn = null;

try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    conn = DriverManager.getConnection(jdbcDriver, dbUser, dbPwd);
} catch (Exception e) {
    e.printStackTrace();
}

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

String dbName = (session != null) ? (String) session.getAttribute("dbName") : null;
String id = (session != null) ? (String) session.getAttribute("id") : null;
String password = (session != null) ? (String) session.getAttribute("password") : null;

/* out.println(password);
out.println(dbName);
out.println(id);
out.println(password); */

String idSortation = (session != null) ? (String) session.getAttribute("idSortation") : null; if (id == null || dbName == null) {
	response.sendRedirect("login.jsp");
	return;
}

jdbcDriver = dbName;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Sales Record</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"record/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"wrap\">\r\n");
      out.write("		<header>\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("		</header>\r\n");
      out.write("\r\n");
      out.write("		<h1 class=\"title\">결제 내역</h1>\r\n");
      out.write("		<div class=\"filter_line\">\r\n");
      out.write("			<div>\r\n");
      out.write("				<input type=\"date\" class=\"startDate selectDate\" id=\"startDate\">\r\n");
      out.write("				<input type=\"date\" class=\"endDate\" id=\"endDate\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div>\r\n");
      out.write("				<input type=\"text\" id=\"searchName\" placeholder=\"이름 검색\">\r\n");
      out.write("				<input type=\"text\" id=\"searchPhone\" placeholder=\"전화번호 검색\">\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- 테이블과 사이드 패널을 포함하는 컨테이너 -->\r\n");
      out.write("		<div id=\"content\">\r\n");
      out.write("			<!-- 테이블 컨테이너 -->\r\n");
      out.write("			<div id=\"tableContainer\">\r\n");
      out.write("				<table class=\"table_line\">\r\n");
      out.write("					<colgroup>\r\n");
      out.write("						<col style=\"width: 50%;\">\r\n");
      out.write("						<col style=\"width: 50%;\">\r\n");
      out.write("					</colgroup>\r\n");
      out.write("					<thead>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th>일자/시간</th>\r\n");
      out.write("							<th>수정 / 삭제</th>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</thead>\r\n");
      out.write("					<tbody id=\"inventory_list\">\r\n");
      out.write("						");

						PreparedStatement pstmt = null;
						ResultSet rs = null;
						try {
							request.setCharacterEncoding("UTF-8");

							String sql = "SELECT A.saleDate AS Dates FROM SalesRecord"  + idSortation + "  A " + "JOIN priceRecord"  + idSortation + "  B ON A.saleDate = B.saleDate";

							pstmt = conn.prepareStatement(sql);
							rs = pstmt.executeQuery();

							int count = 0;
							while (rs.next()) {
								String saleDate = rs.getString("Dates");
								count++;
						
      out.write("\r\n");
      out.write("						<tr data-date=\"");
      out.print(rs.getString("Dates"));
      out.write("\">\r\n");
      out.write("							<td>");
      out.print(saleDate);
      out.write("</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<button class=\"updateBtn custom-btn btn-16\">수정</button>\r\n");
      out.write("								<button class=\"deleteBtn custom-btn btn-16\">삭제</button>\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						");

						}
						if (count == 0) {
						
      out.write("\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td colspan=\"2\">데이터가 없습니다.</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						");

						}
						} catch (Exception e) {
							e.printStackTrace();
							out.println("<tr><td colspan='2'>오류 발생: " + e.getMessage() + "</td></tr>");
						} finally {
				            try { if (rs != null) rs.close(); } catch (Exception ignored) {}
				            try { if (pstmt != null) pstmt.close(); } catch (Exception ignored) {}
						}
						
      out.write("\r\n");
      out.write("						");
      out.write('\r');
      out.write('\n');

    try {
        if (conn != null && !conn.isClosed()) {
            conn.close();
        }
    } catch (Exception ignored) {}

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("					</tbody>\r\n");
      out.write("\r\n");
      out.write("				</table>\r\n");
      out.write("				<ul class=\"pagination\"></ul>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- 사이드 패널 -->\r\n");
      out.write("			<div id=\"sidePanel\">\r\n");
      out.write("				<div id=\"panel_content\"></div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<script src=\"jquery-3.7.1.min.js\"></script>\r\n");
      out.write("	<script src=\"script.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("        function showSidePanel(saleDate) {\r\n");
      out.write("            var xhr = new XMLHttpRequest();\r\n");
      out.write("            xhr.open(\"POST\", \"detailRecord2.jsp?saleDate=\" + saleDate, true);\r\n");
      out.write("            xhr.onreadystatechange = function() {\r\n");
      out.write("                if (xhr.readyState == 4 && xhr.status == 200) {\r\n");
      out.write("                    var panelContent = document.getElementById(\"panel_content\");\r\n");
      out.write("                    panelContent.innerHTML = xhr.responseText;\r\n");
      out.write("                } else if (xhr.readyState == 4) {\r\n");
      out.write("                    console.error(\"AJAX request failed with status \" + xhr.status);\r\n");
      out.write("                }\r\n");
      out.write("            };\r\n");
      out.write("            xhr.send();\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        $(document).ready(function() {\r\n");
      out.write("        	setDefaultDateFilter();\r\n");
      out.write("        	\r\n");
      out.write("        	let now = new Date();\r\n");
      out.write("            let today = now.toISOString().split('T')[0];\r\n");
      out.write("\r\n");
      out.write("            now.setDate(now.getDate() - 1);\r\n");
      out.write("            let yesterday = now.toISOString().split('T')[0];\r\n");
      out.write("\r\n");
      out.write("            $(\"#startDate\").val(yesterday);\r\n");
      out.write("            $(\"#endDate\").val(today);\r\n");
      out.write("            \r\n");
      out.write("            var numPerPage = 10;\r\n");
      out.write("            var currentPage = 1;\r\n");
      out.write("            var selectedRowIndex = -1;\r\n");
      out.write("            \r\n");
      out.write("            document.addEventListener('keydown', function(e) {\r\n");
      out.write("                let $startDate = $(\"#startDate\");\r\n");
      out.write("                let $endDate = $(\"#endDate\");\r\n");
      out.write("\r\n");
      out.write("                // `#startDate`나 `#endDate` 둘 중 하나라도 `.selectDate` 클래스가 있어야 동작\r\n");
      out.write("                if (!$startDate.hasClass(\"selectDate\") && !$endDate.hasClass(\"selectDate\")) return;\r\n");
      out.write("\r\n");
      out.write("                if (e.keyCode == 37) { // 왼쪽 방향키 (-1일)\r\n");
      out.write("                    e.preventDefault();\r\n");
      out.write("\r\n");
      out.write("                    if ($startDate.hasClass(\"selectDate\")) {\r\n");
      out.write("                        let dateInputStart = new Date($startDate.val());\r\n");
      out.write("                        dateInputStart.setDate(dateInputStart.getDate() - 1);\r\n");
      out.write("                        let resultDateS = dateInputStart.toISOString().split(\"T\")[0];\r\n");
      out.write("\r\n");
      out.write("                        if (dateInputStart > new Date($endDate.val())) return false;\r\n");
      out.write("                        $startDate.val(resultDateS);\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    if ($endDate.hasClass(\"selectDate\")) {\r\n");
      out.write("                        let dateInputEnd = new Date($endDate.val());\r\n");
      out.write("                        dateInputEnd.setDate(dateInputEnd.getDate() - 1);\r\n");
      out.write("                        let resultDateE = dateInputEnd.toISOString().split(\"T\")[0];\r\n");
      out.write("\r\n");
      out.write("                        if (dateInputEnd < new Date($startDate.val())) return false;\r\n");
      out.write("                        $endDate.val(resultDateE);\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                if (e.keyCode == 39) { // 오른쪽 방향키 (+1일)\r\n");
      out.write("                    e.preventDefault();\r\n");
      out.write("\r\n");
      out.write("                    if ($startDate.hasClass(\"selectDate\")) {\r\n");
      out.write("                        let dateInputStart = new Date($startDate.val());\r\n");
      out.write("                        dateInputStart.setDate(dateInputStart.getDate() + 1);\r\n");
      out.write("                        let resultDateS = dateInputStart.toISOString().split(\"T\")[0];\r\n");
      out.write("\r\n");
      out.write("                        if (dateInputStart > new Date($endDate.val())) return false;\r\n");
      out.write("                        $startDate.val(resultDateS);\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    if ($endDate.hasClass(\"selectDate\")) {\r\n");
      out.write("                        let dateInputEnd = new Date($endDate.val());\r\n");
      out.write("                        dateInputEnd.setDate(dateInputEnd.getDate() + 1);\r\n");
      out.write("                        let resultDateE = dateInputEnd.toISOString().split(\"T\")[0];\r\n");
      out.write("\r\n");
      out.write("                        if (dateInputEnd < new Date($startDate.val())) return false;\r\n");
      out.write("                        $endDate.val(resultDateE);\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("                // 날짜 변경 후 필터 적용\r\n");
      out.write("                filterRows();\r\n");
      out.write("\r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("         	// 전역 변수로 `dateChange` 선언\r\n");
      out.write("            let dateChange = \"0\";\r\n");
      out.write("\r\n");
      out.write("            document.addEventListener('keydown', function(e) {\r\n");
      out.write("            	e.preventDefault();\r\n");
      out.write("                if (e.keyCode == 25) { // 방향키 아래(40)\r\n");
      out.write("                    if (dateChange == \"0\") {\r\n");
      out.write("                        $(\"#startDate\").removeClass(\"selectDate\");\r\n");
      out.write("                        $(\"#endDate\").addClass(\"selectDate\");\r\n");
      out.write("                        dateChange = \"1\"; // ✅ 값 변경 (전역 변수이므로 유지됨)\r\n");
      out.write("                    } else {\r\n");
      out.write("                        $(\"#endDate\").removeClass(\"selectDate\");\r\n");
      out.write("                        $(\"#startDate\").addClass(\"selectDate\");\r\n");
      out.write("                        dateChange = \"0\"; // ✅ 값 변경\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("                // 날짜 변경 후 필터 적용\r\n");
      out.write("                filterRows();\r\n");
      out.write("            });\r\n");
      out.write("            function filterRows() {\r\n");
      out.write("                let startDate = $('#startDate').val();\r\n");
      out.write("                let endDate = $('#endDate').val();\r\n");
      out.write("\r\n");
      out.write("                $.ajax({\r\n");
      out.write("                    url: \"filterSalesRecord.jsp\",\r\n");
      out.write("                    type: \"GET\",\r\n");
      out.write("                    data: {\r\n");
      out.write("                        startDate: startDate,\r\n");
      out.write("                        endDate: endDate\r\n");
      out.write("                    },\r\n");
      out.write("                    success: function(response) {\r\n");
      out.write("                        $(\"#inventory_list\").html(response); // ✅ 받은 HTML을 바로 삽입\r\n");
      out.write("                        updatePagination();\r\n");
      out.write("                        showPage(1);\r\n");
      out.write("                    },\r\n");
      out.write("                    error: function(xhr, status, error) {\r\n");
      out.write("                        console.error(\"AJAX 필터링 오류:\", error);\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            filterRows();\r\n");
      out.write("\r\n");
      out.write("            // 날짜 필터, 검색 필터 변경 시 실행\r\n");
      out.write("            $('#startDate, #endDate, #searchName, #searchPhone').on('input', function() {\r\n");
      out.write("                filterRows();\r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("            function showPage(page) {\r\n");
      out.write("                var allRows = $('#inventory_list tr');\r\n");
      out.write("                allRows.hide(); // 전체 숨김\r\n");
      out.write("                allRows.slice((page - 1) * numPerPage, page * numPerPage).show();\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            function updatePagination() {\r\n");
      out.write("                var numRows = $('#inventory_list tr').length;\r\n");
      out.write("                var numPages = Math.ceil(numRows / numPerPage);\r\n");
      out.write("                $('.pagination').empty();\r\n");
      out.write("\r\n");
      out.write("                if (numPages <= 1) return;\r\n");
      out.write("\r\n");
      out.write("                for (let i = 1; i <= numPages; i++) {\r\n");
      out.write("                    let pageBtn = $('<li>' + i + '</li>');\r\n");
      out.write("                    if (i === 1) pageBtn.addClass('active');\r\n");
      out.write("                    pageBtn.on('click', function () {\r\n");
      out.write("                        changePage(i);\r\n");
      out.write("                    });\r\n");
      out.write("                    $('.pagination').append(pageBtn);\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            var selectedRowIndex = -1;\r\n");
      out.write("\r\n");
      out.write("            function setSelectedRow(index) {\r\n");
      out.write("                var visibleRows = $('#inventory_list tr:visible');\r\n");
      out.write("                \r\n");
      out.write("                if (index < 0 || index >= visibleRows.length) return;\r\n");
      out.write("\r\n");
      out.write("                selectedRowIndex = index;\r\n");
      out.write("                visibleRows.removeClass('recordList'); // 기존 선택된 행 초기화\r\n");
      out.write("                visibleRows.eq(index).addClass('recordList'); // 새로운 행 선택\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            function changePage(newPage) {\r\n");
      out.write("                currentPage = newPage;\r\n");
      out.write("                showPage(currentPage);\r\n");
      out.write("                setSelectedRow((currentPage - 1) * numPerPage);\r\n");
      out.write("                $('.pagination li').removeClass('active');\r\n");
      out.write("                $('.pagination li').eq(currentPage - 1).addClass('active');\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            $(document).on('click', '.pagination li', function() {\r\n");
      out.write("                var pageIndex = $(this).index();\r\n");
      out.write("                changePage(pageIndex + 1);\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            $('#inventory_list').on('click', 'tr', function() {\r\n");
      out.write("                var saleDate = $(this).data('date');\r\n");
      out.write("                $(this).addClass('recordList').siblings().removeClass('recordList');\r\n");
      out.write("                showSidePanel(saleDate);\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            $(document).on('keydown', function(e) {\r\n");
      out.write("            	 if(e.keyCode == 116){\r\n");
      out.write("                 	e.preventDefault();\r\n");
      out.write("                 } if(e.keyCode == 118){\r\n");
      out.write("                 	e.preventDefault();\r\n");
      out.write("                 	location.reload();\r\n");
      out.write("                 }\r\n");
      out.write("                var visibleRows = $('#inventory_list tr:visible');\r\n");
      out.write("                var totalRows = visibleRows.length;\r\n");
      out.write("                var totalPages = Math.ceil(totalRows / numPerPage);\r\n");
      out.write("                if (totalRows === 0) return;\r\n");
      out.write("\r\n");
      out.write("                if (e.key === 'ArrowDown') {\r\n");
      out.write("                    e.preventDefault();\r\n");
      out.write("                    if (selectedRowIndex === -1) {\r\n");
      out.write("                        setSelectedRow(0);\r\n");
      out.write("                    } else {\r\n");
      out.write("                        var newIndex = selectedRowIndex + 1;\r\n");
      out.write("                        if (newIndex >= totalRows) {\r\n");
      out.write("                            newIndex = 0;\r\n");
      out.write("                            changePage(1);\r\n");
      out.write("                        } else if (newIndex >= currentPage * numPerPage) {\r\n");
      out.write("                            changePage(currentPage + 1);\r\n");
      out.write("                        }\r\n");
      out.write("                        setSelectedRow(newIndex);\r\n");
      out.write("                    }\r\n");
      out.write("            		$('#inventory_list tr:visible').eq(selectedRowIndex).click();\r\n");
      out.write("                } if (e.key === 'ArrowUp') {\r\n");
      out.write("                    e.preventDefault();\r\n");
      out.write("                    if (selectedRowIndex === -1) {\r\n");
      out.write("                        setSelectedRow(0);\r\n");
      out.write("                    } else {\r\n");
      out.write("                        var newIndex = selectedRowIndex - 1;\r\n");
      out.write("                        if (newIndex < 0) {\r\n");
      out.write("                            newIndex = totalRows - 1;\r\n");
      out.write("                            changePage(totalPages);\r\n");
      out.write("                        } else if (newIndex < (currentPage - 1) * numPerPage) {\r\n");
      out.write("                            changePage(currentPage - 1);\r\n");
      out.write("                        }\r\n");
      out.write("                        setSelectedRow(newIndex);\r\n");
      out.write("                    }\r\n");
      out.write("                    $('#inventory_list tr:visible').eq(selectedRowIndex).click();\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            function setDefaultDateFilter() {\r\n");
      out.write("                var today = new Date().toISOString().split('T')[0]; // ISO 문자열의 날짜 부분만 추출\r\n");
      out.write("                $('#startDate').val(today);\r\n");
      out.write("                $('#endDate').val(today);\r\n");
      out.write("                filterRows(); // 페이지 로딩 시 필터링 적용\r\n");
      out.write("                updatePagination(); // 페이지네이션 업데이트\r\n");
      out.write("                showPage(currentPage); // 현재 페이지 표시\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            $('#searchName, #searchPhone, #startDate, #endDate').on('input', function() {\r\n");
      out.write("                currentPage = 1; // 필터링 후 페이지를 첫 페이지로 이동\r\n");
      out.write("                filterRows(); // 필터링 적용\r\n");
      out.write("                updatePagination(); // 페이지네이션 업데이트\r\n");
      out.write("                showPage(currentPage); // 현재 페이지 표시\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            setDefaultDateFilter(); // 페이지 로딩 시 기본 날짜 필터 설정\r\n");
      out.write("        });\r\n");
      out.write("       \r\n");
      out.write("        $(document).on(\"click\", \".updateBtn\", function (e) {\r\n");
      out.write("        	  e.preventDefault();\r\n");
      out.write("\r\n");
      out.write("        	  const $tr = $(this).closest(\"tr\");\r\n");
      out.write("        	  const saleDate = $tr.data(\"date\"); // <tr data-date=\"...\"> 값 사용\r\n");
      out.write("\r\n");
      out.write("        	  if (!saleDate) {\r\n");
      out.write("        	    alert(\"선택된 행의 일자 정보를 찾을 수 없습니다.\");\r\n");
      out.write("        	    return;\r\n");
      out.write("        	  }\r\n");
      out.write("\r\n");
      out.write("        	  if (confirm(saleDate + \" 데이터를 수정하시겠습니까?\")) {\r\n");
      out.write("        	    $.ajax({\r\n");
      out.write("        	      url: \"checkSaleDate.jsp\",\r\n");
      out.write("        	      type: \"POST\",\r\n");
      out.write("        	      data: { saleDate: saleDate },\r\n");
      out.write("        	      success: function (res) {\r\n");
      out.write("        	        let data;\r\n");
      out.write("        	        try { data = typeof res === \"string\" ? JSON.parse(res) : res; }\r\n");
      out.write("        	        catch { data = {}; }\r\n");
      out.write("\r\n");
      out.write("        	        if (data.exists) {\r\n");
      out.write("        	          alert(\"해당 날짜의 데이터를 수정합니다.\");\r\n");
      out.write("        	          // encodeURIComponent 제거\r\n");
      out.write("        	          location.href = \"checkSaleDate.jsp?saleDate=\" + saleDate;\r\n");
      out.write("        	        } else {\r\n");
      out.write("        	          alert(\"해당 날짜에 데이터가 없습니다.\");\r\n");
      out.write("        	        }\r\n");
      out.write("        	      },\r\n");
      out.write("        	      error: function (xhr, status, err) {\r\n");
      out.write("        	        console.error(err);\r\n");
      out.write("        	        alert(\"수정 확인 중 오류가 발생했습니다.\");\r\n");
      out.write("        	      }\r\n");
      out.write("        	    });\r\n");
      out.write("        	  } else {\r\n");
      out.write("        	    alert(\"수정이 취소되었습니다.\");\r\n");
      out.write("        	  }\r\n");
      out.write("        	});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        $(document).on(\"click\",\".deleteBtn\", function(event){\r\n");
      out.write("        		event.preventDefault();\r\n");
      out.write("\r\n");
      out.write("        	  const $tr = $(this).closest(\"tr\");\r\n");
      out.write("        	  const saleDate = $tr.data(\"date\");\r\n");
      out.write("\r\n");
      out.write("        	  if (!saleDate) {\r\n");
      out.write("        	    alert(\"선택된 행의 일자 정보를 찾을 수 없습니다.\");\r\n");
      out.write("        	    return;\r\n");
      out.write("        	  }\r\n");
      out.write("\r\n");
      out.write("        	  if (confirm(saleDate + \" 데이터를 삭제하시겠습니까?\")) {\r\n");
      out.write("        		  $.ajax({\r\n");
      out.write("        			  url: \"deleteSaleDate.jsp\",\r\n");
      out.write("        			  type: \"POST\",\r\n");
      out.write("        			  data: { saleDate: saleDate },\r\n");
      out.write("        			  success: function (res) {\r\n");
      out.write("        			    var data = typeof res === \"string\" ? JSON.parse(res) : res;\r\n");
      out.write("        			    if (data.ok) {\r\n");
      out.write("        			      alert(\r\n");
      out.write("        			        \"재고 복귀 \" + data.updated + \"건 / 삭제(Sales:\" +\r\n");
      out.write("        			        data.deletedSales + \", Client:\" + data.deletedClient + \") 완료\"\r\n");
      out.write("        			      );\r\n");
      out.write("        			      $tr.remove();\r\n");
      out.write("        			      if (typeof filterRows === \"function\") filterRows();\r\n");
      out.write("        			    } else {\r\n");
      out.write("        			      alert(\"삭제 실패: \" + (data.error || \"알 수 없는 오류\"));\r\n");
      out.write("        			    }\r\n");
      out.write("        			  },\r\n");
      out.write("        			  error: function () { alert(\"통신 오류\"); }\r\n");
      out.write("        			});\r\n");
      out.write("\r\n");
      out.write("        	  } else {\r\n");
      out.write("        	    alert(\"삭제가 취소되었습니다.\");\r\n");
      out.write("        	  }\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
