/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.34
 * Generated at: 2026-01-14 13:06:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;
import java.sql.*;

public final class Product_005fRegistration_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/DBconnection.jsp", Long.valueOf(1768386619785L));
    _jspx_dependants.put("/sessionManager.jsp", Long.valueOf(1768386620471L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");

String dbUser = (String) session.getAttribute("id");
String jdbcDriver = (String) session.getAttribute("dbName");
String dbPwd = (String) session.getAttribute("password");

if (dbUser == null || jdbcDriver == null || dbPwd == null) {
    response.sendRedirect("login.jsp");
    return;
}

Connection conn = null;

try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    conn = DriverManager.getConnection(jdbcDriver, dbUser, dbPwd);
} catch (Exception e) {
    e.printStackTrace();
}

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

String dbName = (session != null) ? (String) session.getAttribute("dbName") : null;
String id = (session != null) ? (String) session.getAttribute("id") : null;
String password = (session != null) ? (String) session.getAttribute("password") : null;

String idSortation = (session != null) ? (String) session.getAttribute("idSortation") : null;
if (id == null || dbName == null) {
	response.sendRedirect("login.jsp");
	return;
}

jdbcDriver = dbName;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>바코드 스캔</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"stock/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"wrap\" class=\"Registration\">\r\n");
      out.write("		<header>\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("		</header>\r\n");
      out.write("		<h1>재고 수량 입력</h1>\r\n");
      out.write("		<form action=\"./testTableStore.jsp\" name=\"data\" method=\"post\"\r\n");
      out.write("			id=\"formTeg\" onsubmit=\"return medicine()\">\r\n");
      out.write("			<div class=\"sectionScroll\">\r\n");
      out.write("				<table class=\"headTable\">\r\n");
      out.write("					<colgroup>\r\n");
      out.write("						<col width=\"150px;\">\r\n");
      out.write("						<col width=\"360px;\">\r\n");
      out.write("						<col width=\"300px;\">\r\n");
      out.write("						<col width=\"120px;\">\r\n");
      out.write("						<col width=\"120px;\">\r\n");
      out.write("						<col width=\"130px;\">\r\n");
      out.write("						<col width=\"150px;\">\r\n");
      out.write("						<col width=\"130px;\">\r\n");
      out.write("						<col width=\"150px;\">\r\n");
      out.write("						<col width=\"150px;\">\r\n");
      out.write("						<col width=\"150px;\">\r\n");
      out.write("						<col width=\"110px;\">\r\n");
      out.write("						<col width=\"100px;\">\r\n");
      out.write("					</colgroup>\r\n");
      out.write("					<thead>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th>제품코드<br></th>\r\n");
      out.write("							<th>제품명</th>\r\n");
      out.write("							<th>작업</th>\r\n");
      out.write("							<th>유통기한</th>\r\n");
      out.write("							<th>입고 날짜</th>\r\n");
      out.write("							<th>종류</th>\r\n");
      out.write("							<th>주문최소수량</th>\r\n");
      out.write("							<th>입고 수량</th>\r\n");
      out.write("							<th>판매가격</th>\r\n");
      out.write("							<th>사입가격</th>\r\n");
      out.write("							<th>회사명</th>\r\n");
      out.write("							<th>규격</th>\r\n");
      out.write("							<th>삭제</th>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</thead>\r\n");
      out.write("				</table>\r\n");
      out.write("				<table id=\"table_input\">\r\n");
      out.write("					<colgroup>\r\n");
      out.write("						<col width=\"150px;\">\r\n");
      out.write("						<col width=\"360px;\">\r\n");
      out.write("						<col width=\"300px;\">\r\n");
      out.write("						<col width=\"120px;\">\r\n");
      out.write("						<col width=\"120px;\">\r\n");
      out.write("						<col width=\"130px;\">\r\n");
      out.write("						<col width=\"150px;\">\r\n");
      out.write("						<col width=\"130px;\">\r\n");
      out.write("						<col width=\"150px;\">\r\n");
      out.write("						<col width=\"150px;\">\r\n");
      out.write("						<col width=\"150px;\">\r\n");
      out.write("						<col width=\"110px;\">\r\n");
      out.write("						<col width=\"100px;\">\r\n");
      out.write("					</colgroup>\r\n");
      out.write("					<tbody class=\"tableBody\">\r\n");
      out.write("						<tr class=\"insertTR\">\r\n");
      out.write("							<td><input type=\"text\" name=\"SerialNumber[]\"\r\n");
      out.write("								class=\"SerialNumber\" placeholder=\"일련번호 입력\" autocomplete=\"off\"\r\n");
      out.write("								autocomplete=\"off\"\r\n");
      out.write("								oninput=\"this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\\..*)\\./g, '$1');\"></td>\r\n");
      out.write("							<td><input type=\"text\" name=\"medicineName[]\"\r\n");
      out.write("								class=\"medicineName\" autocomplete=\"off\"></td>\r\n");
      out.write("							<td class=\"boxList\"><label class=\"serial\"><input\r\n");
      out.write("									type=\"checkbox\" class=\"serialClick\" value=\"1\">일련번호\r\n");
      out.write("									없음&nbsp;</label> <label class=\"delivery\"><input type=\"checkbox\"\r\n");
      out.write("									class=\"deliveryClick\" value=\"2\">유통기한 없음</label></td>\r\n");
      out.write("							<td><input type=\"text\" name=\"DeliveryDate[]\"\r\n");
      out.write("								class=\"DeliveryDate\" placeholder=\"yy/mm/dd\"\r\n");
      out.write("								pattern=\"\\d{2}/\\d{2}/\\d{2}\" required autocomplete=\"off\"></td>\r\n");
      out.write("							<td><input type=\"date\" name=\"receiptDate[]\"\r\n");
      out.write("								class=\"receiptDate\" autocomplete=\"off\"></td>\r\n");
      out.write("							<td><select name=\"kind[]\" class=\"kind\">\r\n");
      out.write("									<option class=\"kindVal\" value=\"건강기능식품\">건강기능식품</option>\r\n");
      out.write("									<option class=\"kindVal\" value=\"일반의약품\">일반의약품</option>\r\n");
      out.write("									<option class=\"kindVal\" value=\"파스류\">파스류</option>\r\n");
      out.write("									<option class=\"kindVal\" value=\"연고류\">연고류</option>\r\n");
      out.write("									<option class=\"kindVal\" value=\"드링크류\">드링크류</option>\r\n");
      out.write("									<option class=\"kindVal\" value=\"비타민류\">비타민류</option>\r\n");
      out.write("									<option class=\"kindVal\" value=\"한약류\">한약류</option>\r\n");
      out.write("									<option class=\"kindVal\" value=\"기타\">기타</option>\r\n");
      out.write("							</select></td>\r\n");
      out.write("							<td><input type=\"text\" name=\"inventory[]\" class=\"inventory\"\r\n");
      out.write("								autocomplete=\"off\"></td>\r\n");
      out.write("							<td><input type=\"text\" name=\"quantity[]\" class=\"quantity\"\r\n");
      out.write("								autocomplete=\"off\"></td>\r\n");
      out.write("							<td><input type=\"text\" name=\"price[]\" class=\"price\"\r\n");
      out.write("								autocomplete=\"off\"></td>\r\n");
      out.write("							<td><input type=\"text\" name=\"Buyingprice[]\"\r\n");
      out.write("								class=\"Buyingprice\" autocomplete=\"off\"></td>\r\n");
      out.write("							<td><input type=\"text\" name=\"companyName[]\"\r\n");
      out.write("								class=\"companyName\" autocomplete=\"off\"></td>\r\n");
      out.write("							<td><input type=\"text\" name=\"standard[]\" class=\"standard\"\r\n");
      out.write("								autocomplete=\"off\"></td>\r\n");
      out.write("							<td><input type=\"button\" class=\"deleteTR\" value=\"─\"></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</tbody>\r\n");
      out.write("				</table>\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("		<!-- 검색 팝업을 표시할 div -->\r\n");
      out.write("		<!-- 검색 결과 팝업창 -->\r\n");
      out.write("		<div id=\"popup\">\r\n");
      out.write("			<h3>검색 결과</h3>\r\n");
      out.write("			<div class=\"closeMedicine\">닫기 X</div>\r\n");
      out.write("			<table id=\"popup-table\">\r\n");
      out.write("				<colgroup>\r\n");
      out.write("					<col style=\"width: 550px\">\r\n");
      out.write("					<col style=\"width: 200px\">\r\n");
      out.write("					<col style=\"width: 100px\">\r\n");
      out.write("					<col style=\"width: 150px\">\r\n");
      out.write("					<col style=\"width: 200px\">\r\n");
      out.write("					<col style=\"width: 150px\">\r\n");
      out.write("					<col style=\"width: 150px\">\r\n");
      out.write("					<col style=\"width: 100px\">\r\n");
      out.write("					<col style=\"width: 100px\">\r\n");
      out.write("				</colgroup>\r\n");
      out.write("				<thead>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>제품명</th>\r\n");
      out.write("						<th>회사명</th>\r\n");
      out.write("						<th>재고</th>\r\n");
      out.write("						<th>종류</th>\r\n");
      out.write("						<th>일련번호</th>\r\n");
      out.write("						<th>입고 날짜</th>\r\n");
      out.write("						<th>유통기한</th>\r\n");
      out.write("						<th>사입가</th>\r\n");
      out.write("						<th>판매가</th>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</thead>\r\n");
      out.write("			</table>\r\n");
      out.write("			<table>\r\n");
      out.write("				<colgroup>\r\n");
      out.write("					<col style=\"width: 550px\">\r\n");
      out.write("					<col style=\"width: 200px\">\r\n");
      out.write("					<col style=\"width: 100px\">\r\n");
      out.write("					<col style=\"width: 150px\">\r\n");
      out.write("					<col style=\"width: 200px\">\r\n");
      out.write("					<col style=\"width: 150px\">\r\n");
      out.write("					<col style=\"width: 150px\">\r\n");
      out.write("					<col style=\"width: 100px\">\r\n");
      out.write("					<col style=\"width: 100px\">\r\n");
      out.write("				</colgroup>\r\n");
      out.write("				<tbody id=\"popup-content\"></tbody>\r\n");
      out.write("			</table>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<script src=\"jquery-3.7.1.min.js\"></script>\r\n");
      out.write("	<script src=\"script.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("	$(document).ready(function () {\r\n");
      out.write("		$(\"#wrap .serial .serialClick\").on(\"click\", function(){\r\n");
      out.write("		    const isChecked = $(this).is(\":checked\");\r\n");
      out.write("		    const $SerialNumber = $(this).closest(\".insertTR\").find(\".SerialNumber\");\r\n");
      out.write("		    \r\n");
      out.write("		    if (isChecked) {\r\n");
      out.write("		        $SerialNumber.val(\"1\");\r\n");
      out.write("		        $SerialNumber.prop(\"readOnly\", true);\r\n");
      out.write("		        $SerialNumber.addClass(\"readInput\");\r\n");
      out.write("		    } else {\r\n");
      out.write("		        $SerialNumber.prop(\"readOnly\", false);\r\n");
      out.write("		        $SerialNumber.val(\"\");\r\n");
      out.write("		        $SerialNumber.removeClass(\"readInput\");\r\n");
      out.write("		    }\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$(\"#wrap .delivery .deliveryClick\").on(\"click\", function(){\r\n");
      out.write("		    const isChecked = $(this).is(\":checked\");\r\n");
      out.write("		    const $deliveryDate = $(this).closest(\".insertTR\").find(\".DeliveryDate\");\r\n");
      out.write("		    \r\n");
      out.write("		    if (isChecked) {\r\n");
      out.write("		        $deliveryDate.val(\"99/12/31\");\r\n");
      out.write("		        $deliveryDate.prop(\"readOnly\", true);\r\n");
      out.write("		        $deliveryDate.addClass(\"readInput\");\r\n");
      out.write("		    } else {\r\n");
      out.write("		        $deliveryDate.prop(\"readOnly\", false);\r\n");
      out.write("		        $deliveryDate.val(\"\");\r\n");
      out.write("		        $deliveryDate.removeClass(\"readInput\");\r\n");
      out.write("		    }\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		$(\"#popup .closeMedicine\").on(\"click\", function(){\r\n");
      out.write("			$(\"#popup\").hide();\r\n");
      out.write("		});\r\n");
      out.write("		function addNewRowWithToday() {\r\n");
      out.write("		    const $firstRow = $(\"#table_input .insertTR:first\").clone(); // 첫 행 복제\r\n");
      out.write("		    const todayDate = new Date().toISOString().split('T')[0];\r\n");
      out.write("		    $firstRow.find(\".receiptDate\").val(todayDate);\r\n");
      out.write("		    $firstRow.find(\"input[type=text]\").val('');\r\n");
      out.write("		    $firstRow.removeClass(\"focusRow\");\r\n");
      out.write("		    $(\"#table_input .tableBody\").append($firstRow);\r\n");
      out.write("		}\r\n");
      out.write("		$(\"#wrap .tableBody\").on(\"click\",\".deleteTR\", function(){\r\n");
      out.write("			if($(\"#wrap #table_input .insertTR\").length == 1){\r\n");
      out.write("				return false;\r\n");
      out.write("			}else{\r\n");
      out.write("				$(this).closest(\"tr\").remove();\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		$(\"#wrap\").on(\"focus\", \"#table_input input\", function () {\r\n");
      out.write("		    // 모든 tr/td에서 클래스 제거\r\n");
      out.write("		    $(\"#table_input tbody tr\").removeClass(\"focusRow\");\r\n");
      out.write("		    $(\"#table_input tbody td\").removeClass(\"focusCol focusCell\");\r\n");
      out.write("\r\n");
      out.write("		    // 포커스된 input의 tr에 클래스 추가 (행 강조)\r\n");
      out.write("		    const $tr = $(this).closest(\"tr\");\r\n");
      out.write("		    $tr.addClass(\"focusRow\");\r\n");
      out.write("\r\n");
      out.write("		    // 포커스된 td의 index 구하기\r\n");
      out.write("		    const $td = $(this).closest(\"td\");\r\n");
      out.write("		    const colIndex = $td.index();\r\n");
      out.write("\r\n");
      out.write("		    // 같은 열에 있는 모든 td에 클래스 추가 (열 강조)\r\n");
      out.write("		    $(\"#table_input tbody tr\").each(function () {\r\n");
      out.write("		        $(this).children(\"td\").eq(colIndex).addClass(\"focusCol\");\r\n");
      out.write("		    });\r\n");
      out.write("\r\n");
      out.write("		    // 자기 자신(td)은 교차점이니까 별도 강조\r\n");
      out.write("		    $td.addClass(\"focusCell\");\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		// 천 단위 쉼표 자동 적용 - 모든 tr에 동작\r\n");
      out.write("		$(\"#wrap #formTeg\").on(\"input\", \".price, .Buyingprice, .inventory\", function(){\r\n");
      out.write("		    let value = $(this).val().replace(/[^0-9]/g, \"\"); // 숫자만\r\n");
      out.write("		    if (value) {\r\n");
      out.write("		        let formatted = value.replace(/\\B(?=(\\d{3})+(?!\\d))/g, \",\");\r\n");
      out.write("		        $(this).val(formatted);\r\n");
      out.write("		    }\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("        // 키보드 '+' 키를 자동으로 입력 (Keypad '+')\r\n");
      out.write("        let plusEvent = new KeyboardEvent('keydown', {\r\n");
      out.write("            key: '+',\r\n");
      out.write("            code: 'NumpadAdd',\r\n");
      out.write("            keyCode: 107, // 숫자 키패드 + 키 코드\r\n");
      out.write("            which: 107,\r\n");
      out.write("            bubbles: true\r\n");
      out.write("        });\r\n");
      out.write("		//바코드 스캔 자료\r\n");
      out.write("		document.addEventListener(\"keydown\", function(event) {\r\n");
      out.write("			  if (event.key === '+') {   // + 키 감지\r\n");
      out.write("				event.preventDefault();  // 원래 + 입력 방지\r\n");
      out.write("				// ! 키 이벤트를 인위적으로 생성\r\n");
      out.write("				const exclamationEvent = new KeyboardEvent('keydown', {\r\n");
      out.write("				     key: '!',\r\n");
      out.write("				     code: 'Digit1',   // Shift + 1 의 조합이므로 Digit1\r\n");
      out.write("				     shiftKey: true,\r\n");
      out.write("				     bubbles: true\r\n");
      out.write("				});\r\n");
      out.write("				// 문서 전체로 이벤트 전파\r\n");
      out.write("				document.dispatchEvent(exclamationEvent);\r\n");
      out.write("			}\r\n");
      out.write("		    if (event.key === \"!\") { // 바코드가 \"!\"로 시작하면\r\n");
      out.write("		        event.preventDefault();\r\n");
      out.write("	            // 현재 포커스된 요소에 이벤트를 강제로 발생\r\n");
      out.write("	            document.activeElement.dispatchEvent(plusEvent);\r\n");
      out.write("	            addNewRowWithToday();\r\n");
      out.write("	            $(\".insertTR:eq(-2)\").find(\"td .SerialNumber\").focus();\r\n");
      out.write("		    }\r\n");
      out.write("		});\r\n");
      out.write("		document.getElementById(\"logoutButton\").addEventListener(\"click\", function() {\r\n");
      out.write("            window.location.href = \"logout.jsp\"; // 로그아웃 JSP로 리다이렉트\r\n");
      out.write("        });\r\n");
      out.write("		\r\n");
      out.write("	    let currentRowIndex = -1; // 현재 선택된 행의 인덱스 초기화\r\n");
      out.write("	    let currentRow; // 현재 선택된 행을 추적할 변수 추가\r\n");
      out.write("\r\n");
      out.write("	    // 검색 입력 시 Ajax 요청\r\n");
      out.write("	    $(\"#table_input\").on(\"keydown\", \".insertTR .medicineName\", function (e) {\r\n");
      out.write("	        if (e.key === \"Enter\") { // Enter 키 감지\r\n");
      out.write("	            e.preventDefault(); // 폼 제출 방지\r\n");
      out.write("	            let medicineName = $(this).val();\r\n");
      out.write("\r\n");
      out.write("	            // 현재 포커스가 있는 행을 추적\r\n");
      out.write("	            currentRow = $(this).closest('tr'); // 현재 입력 필드가 속한 행\r\n");
      out.write("\r\n");
      out.write("	            if (medicineName.trim() !== \"\") {\r\n");
      out.write("	                // Ajax 요청\r\n");
      out.write("	                $.ajax({\r\n");
      out.write("	                    url: \"productMedicine.jsp\", // 데이터 검색 JSP\r\n");
      out.write("	                    method: \"POST\",\r\n");
      out.write("	                    data: { medicineName: medicineName }, // LIKE 검색 조건\r\n");
      out.write("	                    success: function (response) {\r\n");
      out.write("	                        $(\"#popup-content\").html(response); // 결과를 테이블에 표시\r\n");
      out.write("	                        $(\"#popup\").show(); // 팝업 표시\r\n");
      out.write("	                        currentRowIndex = -1;\r\n");
      out.write("	                    },\r\n");
      out.write("	                    error: function () {\r\n");
      out.write("	                        return false;\r\n");
      out.write("	                    }\r\n");
      out.write("	                });\r\n");
      out.write("	            }\r\n");
      out.write("	        }\r\n");
      out.write("	    });\r\n");
      out.write("\r\n");
      out.write("	    // 팝업 외부 클릭 시 닫기\r\n");
      out.write("	    $(document).on(\"click\", function (e) {\r\n");
      out.write("	        if (!$(e.target).closest(\"#popup, .medicineName\").length) {\r\n");
      out.write("	            $(\"#popup\").hide();\r\n");
      out.write("	        }\r\n");
      out.write("	    });\r\n");
      out.write("\r\n");
      out.write("	    // 테이블 행 클릭 시 데이터 입력\r\n");
      out.write("	    $(document).on(\"click\", \".result-row\", function () {\r\n");
      out.write("	        let data = $(this).data(); // 선택된 데이터 가져오기\r\n");
      out.write("\r\n");
      out.write("	        // 입력 필드에 값 채우기\r\n");
      out.write("	        populateFields(data);\r\n");
      out.write("	    });\r\n");
      out.write("\r\n");
      out.write("		$('#popup').on(\"mouseover\", \"tbody tr\", function(){\r\n");
      out.write("			  const rows = $('#popup-content tr:visible');\r\n");
      out.write("			  currentRowIndex = rows.index(this);\r\n");
      out.write("			  rows.removeClass('medicineHover');\r\n");
      out.write("			  $(this).addClass('medicineHover');\r\n");
      out.write("		});\r\n");
      out.write("		let selectedRowIndex = -1;\r\n");
      out.write("	    // 키보드 이벤트 처리 (방향키 및 Enter 키)\r\n");
      out.write("		$(document).on('keydown', function (e) {\r\n");
      out.write("			if (!$('#popup').is(':visible')) return;\r\n");
      out.write("			if($(\"#popup\").is(\":visible\")){\r\n");
      out.write("				if(e.keyCode === 27){\r\n");
      out.write("					e.preventDefault();\r\n");
      out.write("					$('#popup').hide();\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			const rows = $('#popup-content tr:visible');\r\n");
      out.write("			if (!rows.length) return;\r\n");
      out.write("			if (e.key === 'ArrowDown') {\r\n");
      out.write("				e.preventDefault();\r\n");
      out.write("			if (currentRowIndex < rows.length - 1) currentRowIndex++;\r\n");
      out.write("			} else if (e.key === 'ArrowUp') {\r\n");
      out.write("				e.preventDefault();\r\n");
      out.write("			if (currentRowIndex > 0) currentRowIndex--;\r\n");
      out.write("			} else if (e.key === 'Enter' && currentRowIndex >= 0) {\r\n");
      out.write("				e.preventDefault();\r\n");
      out.write("				$(rows[currentRowIndex]).trigger('click'); // 기존 클릭 로직 재사용\r\n");
      out.write("			} else {\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			rows.removeClass('medicineHover');\r\n");
      out.write("			if (currentRowIndex >= 0) {\r\n");
      out.write("		    	$(rows[currentRowIndex]).addClass('medicineHover');\r\n");
      out.write("		    	// 강조행이 가려졌다면 살짝만 보이게 스크롤\r\n");
      out.write("		    	rows[currentRowIndex].scrollIntoView({block: 'nearest'});\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("	    // 입력 필드에 데이터 채우기\r\n");
      out.write("	    function populateFields(data) {\r\n");
      out.write("	        // 현재 선택된 행에만 값 채우기\r\n");
      out.write("	        currentRow.find(\".medicineName\").val(data.medicinename);\r\n");
      out.write("	        currentRow.find(\".companyName\").val(data.companyname);\r\n");
      out.write("	        currentRow.find(\".standard\").val(data.standard);\r\n");
      out.write("	        currentRow.find(\".kind\").val(data.kind);\r\n");
      out.write("	        currentRow.find(\".inventory\").val(data.inventory);\r\n");
      out.write("	        currentRow.find(\".SerialNumber\").val(data.serialnumber);\r\n");
      out.write("	        currentRow.find(\".DeliveryDate\").val(data.deliverydate);\r\n");
      out.write("	        currentRow.find(\".Buyingprice\").val(data.buyingprice);\r\n");
      out.write("	        currentRow.find(\".price\").val(data.price);\r\n");
      out.write("\r\n");
      out.write("	        $(\"#popup\").hide(); // 팝업 숨기기\r\n");
      out.write("	        currentRow.find(\".DeliveryDate\").focus(); // 입력 필드에 포커스 이동\r\n");
      out.write("	    }\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	document.addEventListener('keydown', (event) => {\r\n");
      out.write("	    //console.log(`Key: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${event.key}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(", ASCII Code: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${event.keyCode}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`);\r\n");
      out.write("	    // - 키를 누르면 맨 아래 리스트가 삭제\r\n");
      out.write("		if (event.keyCode == 109) { // '-' 키\r\n");
      out.write("	event.preventDefault();\r\n");
      out.write("	const $rows = $(\"#table_input .insertTR\");\r\n");
      out.write("\r\n");
      out.write("	if ($rows.length > 1) {\r\n");
      out.write("		$rows.last().remove(); // 마지막 행 제거\r\n");
      out.write("	} else {\r\n");
      out.write("		alert(\"더 이상 삭제할 수 없습니다.\");\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("	    \r\n");
      out.write("\r\n");
      out.write("		if (event.keyCode === 106){\r\n");
      out.write("			event.preventDefault();\r\n");
      out.write("			alert(\"데이터가 저장되었습니다.\");\r\n");
      out.write("			$(\"#formTeg\").submit();\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("	    // + 버튼을 누르면 리스트가 하나 새로 추가\r\n");
      out.write("if (event.keyCode == 107) {\r\n");
      out.write("    event.preventDefault();\r\n");
      out.write("\r\n");
      out.write("    addNewRowWithToday();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("	});\r\n");
      out.write(" 	document.addEventListener(\"input\", function (event) {\r\n");
      out.write("	    if (event.target.classList.contains(\"DeliveryDate\")) {\r\n");
      out.write("	        let input = event.target.value.replace(/[^0-9]/g, \"\"); // 숫자 외 제거\r\n");
      out.write("	        let formatted = \"\";\r\n");
      out.write("\r\n");
      out.write("	        if (input.length > 2) {\r\n");
      out.write("	            formatted += input.substring(0, 2) + \"/\"; // 첫 번째 슬래시 추가\r\n");
      out.write("	        } else {\r\n");
      out.write("	            formatted += input;\r\n");
      out.write("	        }\r\n");
      out.write("\r\n");
      out.write("	        if (input.length > 4) {\r\n");
      out.write("	            formatted += input.substring(2, 4) + \"/\"; // 두 번째 슬래시 추가\r\n");
      out.write("	            formatted += input.substring(4, 6); // 나머지 추가\r\n");
      out.write("	        } else if (input.length > 2) {\r\n");
      out.write("	            formatted += input.substring(2); // 첫 슬래시 뒤 나머지 추가\r\n");
      out.write("	        }\r\n");
      out.write("	        event.target.value = formatted.slice(0, 8); // 최대 8자리 유지\r\n");
      out.write("	    }\r\n");
      out.write("	});\r\n");
      out.write(" 	document.addEventListener(\"keydown\", function (event) {\r\n");
      out.write("	    // Enter 키와 PageDown 키 감지\r\n");
      out.write("	    if (event.keyCode === 34) {\r\n");
      out.write("	        event.preventDefault(); // 기본 동작 방지\r\n");
      out.write("\r\n");
      out.write("	        const currentInput = event.target;\r\n");
      out.write("\r\n");
      out.write("	        // 현재 input의 부모 td 요소 찾기\r\n");
      out.write("	        const currentTd = currentInput.closest(\"td\");\r\n");
      out.write("	        if (!currentTd) return; // td가 없으면 종료\r\n");
      out.write("\r\n");
      out.write("	        // 현재 td의 이전 형제 td 찾기\r\n");
      out.write("	        const prevTd = currentTd.previousElementSibling;\r\n");
      out.write("\r\n");
      out.write("	        // 이전 td에 input 요소가 있는지 확인 후 포커스 이동\r\n");
      out.write("	        if (prevTd) {\r\n");
      out.write("	            const prevInput = prevTd.querySelector(\"input\");\r\n");
      out.write("	            if (prevInput) {\r\n");
      out.write("	                prevInput.focus();\r\n");
      out.write("	            }\r\n");
      out.write("	        }\r\n");
      out.write("	    }\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	document.addEventListener(\"keydown\", function(event) {\r\n");
      out.write("	    // Enter 키 확인\r\n");
      out.write("	    if (event.key === \"Enter\") {\r\n");
      out.write("	        const currentInput = document.activeElement;\r\n");
      out.write("\r\n");
      out.write("	        // .SerialNumber는 제외\r\n");
      out.write("	        if (currentInput.classList.contains(\"SerialNumber\")) {\r\n");
      out.write("	            return; // SerialNumber 필드는 기본 동작 유지\r\n");
      out.write("	        }\r\n");
      out.write("\r\n");
      out.write("	        // 현재 입력 필드의 부모 <td>에서 다음 <td>를 찾음\r\n");
      out.write("	        const nextTd = currentInput.closest(\"td\").nextElementSibling;\r\n");
      out.write("	        if (nextTd) {\r\n");
      out.write("	            const nextInput = nextTd.querySelector(\"input, select\"); // 다음 <td> 안의 input 또는 select 찾기\r\n");
      out.write("	            if (nextInput) {\r\n");
      out.write("	                event.preventDefault(); // 기본 Enter 키 동작 방지\r\n");
      out.write("	                nextInput.focus(); // 다음 입력 필드로 포커스 이동\r\n");
      out.write("	            }\r\n");
      out.write("	        } else {\r\n");
      out.write("	            // 마지막 필드인 경우 추가적인 동작(필요 시 구현)\r\n");
      out.write("	            event.preventDefault();\r\n");
      out.write("	        }\r\n");
      out.write("	    }\r\n");
      out.write("	});\r\n");
      out.write("	// 방향키로 행 이동\r\n");
      out.write("document.addEventListener(\"keydown\", function(event) {\r\n");
      out.write("    // 위쪽(ArrowUp)과 아래쪽(ArrowDown) 키만 처리\r\n");
      out.write("    if (event.key === \"ArrowDown\" || event.key === \"ArrowUp\") {\r\n");
      out.write("        event.preventDefault(); // 기본 화살표 동작 방지\r\n");
      out.write("\r\n");
      out.write("        const currentInput = event.target; // 현재 포커스된 input 요소\r\n");
      out.write("        const currentTd = currentInput.closest(\"td\"); // 현재 input이 속한 td\r\n");
      out.write("        const currentTr = currentTd.closest(\"tr\"); // 현재 td가 속한 tr\r\n");
      out.write("        const currentTable = currentTr.closest(\"table\"); // 현재 tr이 속한 table\r\n");
      out.write("\r\n");
      out.write("        let targetTd; // 이동할 대상 td를 변수로 설정\r\n");
      out.write("\r\n");
      out.write("        // 방향키에 따른 이동\r\n");
      out.write("        if (event.key === \"ArrowDown\") {\r\n");
      out.write("            const targetTr = currentTr.nextElementSibling; // 다음 행\r\n");
      out.write("            if (targetTr) {\r\n");
      out.write("                targetTd = targetTr.children[currentTd.cellIndex]; // 현재 td의 같은 위치\r\n");
      out.write("            } else {\r\n");
      out.write("                // 마지막 행일 경우 첫 번째 행으로 이동\r\n");
      out.write("                const firstRow = currentTable.querySelector(\"tbody tr:first-child\");\r\n");
      out.write("                targetTd = firstRow.children[currentTd.cellIndex];\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        else if (event.key === \"ArrowUp\") {\r\n");
      out.write("            const targetTr = currentTr.previousElementSibling; // 이전 행\r\n");
      out.write("            if (targetTr) {\r\n");
      out.write("                targetTd = targetTr.children[currentTd.cellIndex]; // 현재 td의 같은 위치\r\n");
      out.write("            } else {\r\n");
      out.write("                // 첫 번째 행일 경우 마지막 행으로 이동\r\n");
      out.write("                const lastRow = currentTable.querySelector(\"tbody tr:last-child\");\r\n");
      out.write("                targetTd = lastRow.children[currentTd.cellIndex];\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // 이동할 td가 존재하면, 해당 td의 input 요소로 포커스 이동\r\n");
      out.write("        if (targetTd) {\r\n");
      out.write("            const targetInput = targetTd.querySelector(\"input\"); // 대상 td의 input 요소 찾기\r\n");
      out.write("            if (targetInput) {\r\n");
      out.write("                targetInput.focus(); // 해당 input 요소에 포커스 이동\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // 좌우 방향키 (ArrowLeft, ArrowRight)에 대한 처리를 하지 않음\r\n");
      out.write("    else if (event.key === \"ArrowLeft\" || event.key === \"ArrowRight\") {\r\n");
      out.write("        event.preventDefault(); // 좌우 키 동작 방지\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("	 	// SerialNumber에서 Enter 키 입력 시 데이터 가져오기\r\n");
      out.write("$(\"#wrap #table_input\").on(\"keypress\", \".SerialNumber\", function(event) {\r\n");
      out.write("    if (event.which == 13) {  // Enter 키를 감지\r\n");
      out.write("        var currentRow = $(this).closest(\"tr\");  // 현재 행을 찾음\r\n");
      out.write("        var serialNumber = $(this).val();  // 입력된 serialNumber\r\n");
      out.write("\r\n");
      out.write("        // AJAX 요청\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            type: \"POST\",\r\n");
      out.write("            url: \"fetchDataFromDB.jsp\",  // 데이터를 가져올 서버 파일 경로\r\n");
      out.write("            data: { serialNumber: serialNumber },\r\n");
      out.write("            dataType: \"json\",  // 응답을 JSON 형식으로 받음\r\n");
      out.write("            success: function(response) {\r\n");
      out.write("                if (response.error) {\r\n");
      out.write("                    alert(response.error);  // 오류가 있으면 알림 표시\r\n");
      out.write("                } else {\r\n");
      out.write("                    // 서버 응답으로 현재 행의 값을 설정\r\n");
      out.write("                    currentRow.find(\".medicineName\").val(response.medicineName);\r\n");
      out.write("                    currentRow.find(\".DeliveryDate\").val(response.DeliveryDate);\r\n");
      out.write("                    currentRow.find(\".inventory\").val(response.inventory);\r\n");
      out.write("                    currentRow.find(\".price\").val(response.price);\r\n");
      out.write("                    currentRow.find(\".kind\").val(response.kind);\r\n");
      out.write("                    currentRow.find(\".Buyingprice\").val(response.Buyingprice);\r\n");
      out.write("                    currentRow.find(\".companyName\").val(response.companyName);\r\n");
      out.write("                    currentRow.find(\".standard\").val(response.standard);\r\n");
      out.write("                    currentRow.find(\".quantity\").val(response.quantity);\r\n");
      out.write("\r\n");
      out.write("                    // DeliveryDate 값을 설정하고 포커스\r\n");
      out.write("                    var deliveryDateInput = currentRow.find(\".DeliveryDate\");\r\n");
      out.write("                    deliveryDateInput.val(response.DeliveryDate).focus(); // 값 설정 후 포커스\r\n");
      out.write("                }\r\n");
      out.write("            },\r\n");
      out.write("            error: function(xhr, status, error) {\r\n");
      out.write("                console.error(\"AJAX 요청 에러:\", error);  // 요청 에러 처리\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        event.preventDefault(); // 기본 Enter 동작 방지\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("	    $(\"#wrap #table_input\").on(\"keypress\", \".DeliveryDate\", function(event) {\r\n");
      out.write("	        var inputField = $(this);\r\n");
      out.write("	        if (!inputField.data(\"cleared\")) {\r\n");
      out.write("	            // 기존 값 삭제\r\n");
      out.write("	            inputField.val(\"\");\r\n");
      out.write("	            inputField.data(\"cleared\", true); // 값을 한번만 삭제하도록 설정\r\n");
      out.write("	        }\r\n");
      out.write("	    });\r\n");
      out.write("\r\n");
      out.write("	    // 포커스가 취소되면 상태 초기화\r\n");
      out.write("	    $(\"#wrap #table_input\").on(\"blur\", \".DeliveryDate\", function() {\r\n");
      out.write("	        $(this).data(\"cleared\", false); // 다시 입력 시 기존 값 삭제 가능\r\n");
      out.write("	    });\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	$(document).on('keydown', function(event) {\r\n");
      out.write("	    if (event.ctrlKey && (event.key === 's' || event.key === 'S')) {\r\n");
      out.write("	        event.preventDefault();\r\n");
      out.write("	        $('#formTeg').submit();\r\n");
      out.write("	    }\r\n");
      out.write("	    if(event.keyCode == 118){\r\n");
      out.write("	        event.preventDefault();\r\n");
      out.write("	        window.location.href=\"Product_Registration.jsp\";\r\n");
      out.write("	    }\r\n");
      out.write("	    if(event.keyCode == 122){\r\n");
      out.write("	        event.preventDefault();\r\n");
      out.write("	        $('#formTeg').submit();\r\n");
      out.write("	    }\r\n");
      out.write("	    if(event.keyCode == 116){\r\n");
      out.write("	        event.preventDefault();\r\n");
      out.write("	    }\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		function medicine() {		// 입력란 변수\r\n");
      out.write("			var $SerialNumber = $(\"#table_input .SerialNumber\");\r\n");
      out.write("			var $medicineName = $(\"#table_input .medicineName\");\r\n");
      out.write("			var $Buyingprice = $(\"#table_input .Buyingprice\");\r\n");
      out.write("			var $price = $(\"#table_input .price\");\r\n");
      out.write("			var $inventory = $(\"#table_input .inventory\");\r\n");
      out.write("			var $companyName = $(\"#table_input .companyName\");\r\n");
      out.write("			var $standard = $(\"#table_input .standard\");\r\n");
      out.write("			var $receiptDate = $(\"#table_input .receiptDate\");\r\n");
      out.write("			var $DeliveryDate = $(\"#table_input .DeliveryDate\");\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		    // , 제거\r\n");
      out.write("		    $(\"#wrap #table_input\").find(\".price, .inventory, .Buyingprice\").each(function () {\r\n");
      out.write("		        let cleanVal = $(this).val().replace(/,/g, \"\");\r\n");
      out.write("		        $(this).val(cleanVal);\r\n");
      out.write("		    });\r\n");
      out.write("\r\n");
      out.write("		    return true;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		$(\"#wrap #table_input .receiptDate\").val(new Date().toISOString().split('T')[0]);\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
