/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.34
 * Generated at: 2026-01-16 12:22:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;
import java.util.regex.*;
import java.sql.*;
import java.sql.*;

public final class productMedicine_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/DBconnection.jsp", Long.valueOf(1768386619785L));
    _jspx_dependants.put("/sessionManager.jsp", Long.valueOf(1768386620471L));
    _jspx_dependants.put("/DBclose.jsp", Long.valueOf(1768386619783L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("java.util.regex");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");

String dbUser = (String) session.getAttribute("id");
String jdbcDriver = (String) session.getAttribute("dbName");
String dbPwd = (String) session.getAttribute("password");

if (dbUser == null || jdbcDriver == null || dbPwd == null) {
    response.sendRedirect("login.jsp");
    return;
}

Connection conn = null;

try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    conn = DriverManager.getConnection(jdbcDriver, dbUser, dbPwd);
} catch (Exception e) {
    e.printStackTrace();
}

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");

String dbName = (session != null) ? (String) session.getAttribute("dbName") : null;
String id = (session != null) ? (String) session.getAttribute("id") : null;
String password = (session != null) ? (String) session.getAttribute("password") : null;

String idSortation = (session != null) ? (String) session.getAttribute("idSortation") : null; if (id == null || dbName == null) {
    response.sendRedirect("login.jsp");
    return;
}

jdbcDriver = dbName;

      out.write("\r\n");
      out.write("\r\n");

String medicineName = request.getParameter("medicineName");
PreparedStatement pstmt = null;
ResultSet rs = null;

boolean hasResult = false;

try {
    String sql = "SELECT medicineName, companyName, standard, kind, inventory, serialNumber, " +
                 "receiptDate, deliveryDate, FORMAT(buyingprice, 0) AS buyingprice," + 
    			 " FORMAT(price, 0) AS price " +
                 "FROM testTable"  + idSortation + "  WHERE medicineName LIKE ?";
    pstmt = conn.prepareStatement(sql);
    pstmt.setString(1, "%" + medicineName + "%");
    rs = pstmt.executeQuery();

      out.write("\r\n");
      out.write("\r\n");

while (rs.next()) {
    hasResult = true;

      out.write("\r\n");
      out.write("<tr class='result-row' style='cursor: pointer;'\r\n");
      out.write("    data-medicinename='");
      out.print( rs.getString("medicineName") );
      out.write("'\r\n");
      out.write("    data-companyname='");
      out.print( rs.getString("companyName") );
      out.write("'\r\n");
      out.write("    data-standard='");
      out.print( rs.getString("standard") );
      out.write("'\r\n");
      out.write("    data-inventory='");
      out.print( rs.getString("inventory") );
      out.write("'\r\n");
      out.write("    data-kind='");
      out.print( rs.getString("kind") );
      out.write("'\r\n");
      out.write("    data-serialnumber='");
      out.print( rs.getString("serialNumber") );
      out.write("'\r\n");
      out.write("    data-receiptdate='");
      out.print( rs.getString("receiptDate") );
      out.write("'\r\n");
      out.write("    data-deliverydate='");
      out.print( rs.getString("deliveryDate") );
      out.write("'\r\n");
      out.write("    data-buyingprice='");
      out.print( rs.getString("buyingprice") );
      out.write("'\r\n");
      out.write("    data-price='");
      out.print( rs.getString("price") );
      out.write("'>\r\n");
      out.write("    <td style='border: 1px solid #ccc; padding: 5px;'>");
      out.print( rs.getString("medicineName") );
      out.write("</td>\r\n");
      out.write("    <td style='border: 1px solid #ccc; padding: 5px;'>");
      out.print( rs.getString("companyName") );
      out.write("</td>\r\n");
      out.write("    <td style='border: 1px solid #ccc; padding: 5px;'>");
      out.print( rs.getString("inventory") );
      out.write("</td>\r\n");
      out.write("    <td style='border: 1px solid #ccc; padding: 5px;'>");
      out.print( rs.getString("kind") );
      out.write("</td>\r\n");
      out.write("    <td style='border: 1px solid #ccc; padding: 5px;'>");
      out.print( rs.getString("serialNumber") );
      out.write("</td>\r\n");
      out.write("    <td style='border: 1px solid #ccc; padding: 5px;'>");
      out.print( rs.getString("receiptDate") );
      out.write("</td>\r\n");
      out.write("    <td style='border: 1px solid #ccc; padding: 5px;'>");
      out.print( rs.getString("deliveryDate") );
      out.write("</td>\r\n");
      out.write("    <td style='border: 1px solid #ccc; padding: 5px;'>");
      out.print( rs.getString("buyingprice") );
      out.write("</td>\r\n");
      out.write("    <td style='border: 1px solid #ccc; padding: 5px;'>");
      out.print( rs.getString("price") );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
 if (!hasResult) { 
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("    <td colspan=\"9\" style=\"text-align: center; padding: 10px;\">검색 결과가 없습니다.</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");

} catch (Exception e) {
    e.printStackTrace();
} finally {
    try { if (rs != null) rs.close(); } catch (Exception ignored) {}
    try { if (pstmt != null) pstmt.close(); } catch (Exception ignored) {}
}

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

    try {
        if (conn != null && !conn.isClosed()) {
            conn.close();
        }
    } catch (Exception ignored) {}

      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
