/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.34
 * Generated at: 2026-01-14 13:39:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;
import org.json.*;
import java.io.*;
import java.util.regex.*;
import java.sql.*;
import java.sql.*;

public final class saveLeftList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {


// 숫자 정리
String clean(String v) {
    if (v == null) return null;
    return v.replaceAll("[^0-9.]", "");
}

// 날짜 변환
String normalize(String date) {
    if (date == null || date.trim().isEmpty()) return null;
    date = date.trim().replace("/", "-");

    if (date.matches("^20\\d{2}-\\d{2}-\\d{2}$"))
        return date;

    if (date.matches("^\\d{2}-\\d{2}-\\d{2}$")) {
        String[] p = date.split("-");
        return "20" + p[0] + "-" + p[1] + "-" + p[2];
    }

    return date;
}

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/DBconnection.jsp", Long.valueOf(1768386619785L));
    _jspx_dependants.put("/sessionManager.jsp", Long.valueOf(1768386620471L));
    _jspx_dependants.put("/DBclose.jsp", Long.valueOf(1768386619783L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(10);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("java.util.regex");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("org.json");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("application/json; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");

String dbUser = (String) session.getAttribute("id");
String jdbcDriver = (String) session.getAttribute("dbName");
String dbPwd = (String) session.getAttribute("password");

if (dbUser == null || jdbcDriver == null || dbPwd == null) {
    response.sendRedirect("login.jsp");
    return;
}

Connection conn = null;

try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    conn = DriverManager.getConnection(jdbcDriver, dbUser, dbPwd);
} catch (Exception e) {
    e.printStackTrace();
}

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String idSortation = (String) session.getAttribute("idSortation");
jdbcDriver = (String) session.getAttribute("dbName");

BufferedReader br = request.getReader();
StringBuilder sb = new StringBuilder();
String line;
while ((line = br.readLine()) != null) sb.append(line);

JSONArray arr = new JSONArray(sb.toString());

if (arr.length() == 0) {
    out.print("{\"result\":\"error\",\"msg\":\"empty list\"}");
    return;
}

String medicineName = arr.getJSONObject(0).getString("medicineName");
PreparedStatement delP = null;
PreparedStatement insP = null;


try {
    conn.setAutoCommit(false);

    /* -------------------------------------
       STEP 1) 기존 데이터 전체 삭제
    -------------------------------------- */
    String delSql = "DELETE FROM testTable" + idSortation + " WHERE SerialNumber=?";
    delP = conn.prepareStatement(delSql);

    for (int i = 0; i < arr.length(); i++) {
        String sn = arr.getJSONObject(i).getString("SerialNumber");

        if (sn == null || sn.trim().isEmpty()) continue;

        delP.setString(1, sn);
        delP.addBatch();
    }

    delP.executeBatch();
    delP.close();

    /* -------------------------------------
       STEP 2) JSON 데이터 전체 INSERT
    -------------------------------------- */
    String insSql =
        "INSERT INTO testTable" + idSortation +
        " (SerialNumber, medicineName, inventory, quantity, DeliveryDate, receiptDate, kind, Buyingprice, price, companyName, standard) " +
        "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

    insP = conn.prepareStatement(insSql);

    for (int i = 0; i < arr.length(); i++) {
        JSONObject row = arr.getJSONObject(i);

        String sn = row.getString("SerialNumber");
        String name = row.getString("medicineName");
        String std = row.getString("standard");

        // 날짜정리
        String dDate = normalize(row.getString("DeliveryDate"));
        String rDate = normalize(row.getString("receiptDate"));

        // 숫자정리
        String buying = clean(row.getString("Buyingprice"));
        String price = clean(row.getString("price"));

        insP.setString(1, sn);
        insP.setString(2, name);
        insP.setString(3, row.getString("inventory"));
        insP.setString(4, clean(row.getString("quantity")));
        insP.setString(5, dDate);
        insP.setString(6, rDate);
        insP.setString(7, row.getString("kind"));
        insP.setString(8, buying);
        insP.setString(9, price);
        insP.setString(10, row.getString("companyName"));
        insP.setString(11, std);

        insP.addBatch();
    }

    insP.executeBatch();
    conn.commit();

    out.print("{\"result\":\"ok\"}");

} catch (Exception e) {
    conn.rollback();
    out.print("{\"result\":\"error\", \"msg\":\"" + e.getMessage() + "\"}");
}finally{
	try{ if(delP != null) delP.close(); } catch(Exception ignore) {}
	try{ if(insP != null) insP.close(); } catch(Exception ignore) {}
}

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

    try {
        if (conn != null && !conn.isClosed()) {
            conn.close();
        }
    } catch (Exception ignored) {}

      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
