/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.34
 * Generated at: 2026-01-14 10:38:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;
import java.sql.*;
import java.sql.*;

public final class searchMedicine2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/DBconnection.jsp", Long.valueOf(1768386619785L));
    _jspx_dependants.put("/sessionManager.jsp", Long.valueOf(1768386620471L));
    _jspx_dependants.put("/DBclose.jsp", Long.valueOf(1768386619783L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");

String dbUser = (String) session.getAttribute("id");
String jdbcDriver = (String) session.getAttribute("dbName");
String dbPwd = (String) session.getAttribute("password");

if (dbUser == null || jdbcDriver == null || dbPwd == null) {
    response.sendRedirect("login.jsp");
    return;
}

Connection conn = null;

try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    conn = DriverManager.getConnection(jdbcDriver, dbUser, dbPwd);
} catch (Exception e) {
    e.printStackTrace();
}

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

String dbName = (session != null) ? (String) session.getAttribute("dbName") : null;
String id = (session != null) ? (String) session.getAttribute("id") : null;
String password = (session != null) ? (String) session.getAttribute("password") : null;

String idSortation = (session != null) ? (String) session.getAttribute("idSortation") : null; if (id == null || dbName == null) {
    response.sendRedirect("login.jsp");
    return;
}

jdbcDriver = dbName;

      out.write('\r');
      out.write('\n');

    String medicineName = request.getParameter("medicineName");
    PreparedStatement pstmt = null;
    ResultSet rs = null;

    boolean hasResult = false; // while 문 외부에서 선언

    try {
        Class.forName("com.mysql.cj.jdbc.Driver");

        String sql = " SELECT medicineName, standard, FORMAT(buyingprice, 0) AS byPrice, FORMAT(price, 0) AS price, "
        		   + " countNumber, lowerAndHigest "
			       + " FROM RegistTable "
	 			   + " WHERE medicineName LIKE ?";
        pstmt = conn.prepareStatement(sql);
        pstmt.setString(1, "%" + medicineName + "%");
        rs = pstmt.executeQuery();

      out.write('\r');
      out.write('\n');
 while (rs.next()) { 
     hasResult = true;

      out.write("\r\n");
      out.write("<tr class='result-row' style='cursor: pointer;'\r\n");
      out.write("    data-medicinename='");
      out.print( rs.getString("medicineName") );
      out.write("'\r\n");
      out.write("    data-standard='");
      out.print( rs.getString("standard") );
      out.write("'\r\n");
      out.write("    data-buyingprice='");
      out.print( "1" );
      out.write("'\r\n");
      out.write("    data-price='");
      out.print( rs.getString("price") );
      out.write("'\r\n");
      out.write("    data-lowerandhigest='");
      out.print( rs.getString("lowerAndHigest") );
      out.write("'\r\n");
      out.write("    >\r\n");
      out.write("    <td style='border: 1px solid #ccc; padding: 5px;'>");
      out.print( rs.getString("medicineName") );
      out.write("</td>\r\n");
      out.write("    <td style='border: 1px solid #ccc; padding: 5px;'>");
      out.print( rs.getString("standard") );
      out.write("</td>\r\n");
      out.write("    <td style='border: 1px solid #ccc; padding: 5px;'>");
      out.print( rs.getString("byPrice") );
      out.write("</td>\r\n");
      out.write("    <td style='border: 1px solid #ccc; padding: 5px;'>");
      out.print( rs.getString("price") );
      out.write("</td>\r\n");
      out.write("    <td style='border: 1px solid #ccc; padding: 5px;'>");
      out.print( rs.getString("lowerAndHigest") );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
 } 
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("    <td colspan=\"9\" style=\"text-align: center;\">\r\n");
      out.write("        <div style=\"margin-top: 10px;\">\r\n");
      out.write("            <button class=\"addProduct\" data-medicinename=\"");
      out.print( medicineName );
      out.write("\"><span class=\"topBtn\">등록하러 가기</span></button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </td>\r\n");
      out.write("</tr>\r\n");
 if (!hasResult) { 
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("    <td colspan=\"9\" style=\"text-align: center; padding: 10px;\">검색 결과가 없습니다.</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("    <td colspan=\"9\" style=\"text-align: center; padding: 10px;\">제품 등록을 하시겠습니까?</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("    <td colspan=\"9\" style=\"text-align: center;\">\r\n");
      out.write("        <div style=\"margin-top: 10px;\">\r\n");
      out.write("            <button class=\"addProduct\" data-medicinename=\"");
      out.print( medicineName );
      out.write("\"><span class=\"topBtn\">등록하러 가기</span></button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </td>\r\n");
      out.write("</tr>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    } catch (Exception e) {
        e.printStackTrace();
    } finally {
        try { if (pstmt != null) pstmt.close(); } catch (Exception ignored) {}
        try { if (rs != null) rs.close(); } catch (Exception ignored) {}
    }

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

    try {
        if (conn != null && !conn.isClosed()) {
            conn.close();
        }
    } catch (Exception ignored) {}

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 모달 뼈대 추가 -->\r\n");
      out.write("<div class=\"addMedicine\" style=\"display:none; position:fixed; top:0; left:0; right:0; bottom:0; z-index:9999; justify-content:center; align-items:center;\">\r\n");
      out.write("  <div class=\"modal-content\" style=\"background:white; padding:20px; border-radius:10px; width:80%; max-height:80%; overflow:auto;\">\r\n");
      out.write("    <!-- addProduct.jsp가 여기 삽입됨 -->\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("    // 결과 행 클릭 이벤트\r\n");
      out.write("    $(\".result-row\").on(\"click\", function() {\r\n");
      out.write("        if (window.opener && !window.opener.closed) {\r\n");
      out.write("            const focused = window.opener.document.querySelector(\"input[name='medicineName[]']:focus\");\r\n");
      out.write("            if (focused) {\r\n");
      out.write("                const tr = $(focused).closest(\"tr\");\r\n");
      out.write("                tr.find(\"input[name='medicineName[]']\").val($(this).data(\"medicinename\"));\r\n");
      out.write("                tr.find(\"input[name='standard[]']\").val($(this).data(\"standard\"));\r\n");
      out.write("                tr.find(\"input[name='price[]']\").val($(this).data(\"price\"));\r\n");
      out.write("                tr.find(\"input[name='lowerandhigest[]']\").val($(this).data(\"lowerandhigest\"));\r\n");
      out.write("            }\r\n");
      out.write("            window.close();\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // \"등록하러 가기\" 버튼 클릭 이벤트\r\n");
      out.write("    $(\".addProduct\").on(\"click\", function() {\r\n");
      out.write("        const medicineName = $(this).data(\"medicinename\");\r\n");
      out.write("\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url: \"addProduct.jsp\",\r\n");
      out.write("            method: \"GET\",\r\n");
      out.write("            data: { medicineName: medicineName },\r\n");
      out.write("            success: function(response) {\r\n");
      out.write("                $(\".addMedicine .modal-content\").html(response);\r\n");
      out.write("                $(\".addMedicine\").css(\"display\", \"flex\"); // 모달 보이게\r\n");
      out.write("            },\r\n");
      out.write("            error: function(xhr, status, error) {\r\n");
      out.write("                console.error(error);\r\n");
      out.write("                alert(\"등록 페이지를 불러오는 중 오류가 발생했습니다.\");\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // 모달 바깥쪽 클릭하면 모달 닫기\r\n");
      out.write("    $(\".addMedicine\").on(\"click\", function(e) {\r\n");
      out.write("        if (e.target === this) {\r\n");
      out.write("            $(this).hide();\r\n");
      out.write("            $(\".modal-content\").empty(); // 닫을 때 안에 내용 비워주기\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
