/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.34
 * Generated at: 2026-01-16 12:32:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;
import java.util.*;
import java.io.*;
import java.sql.*;
import java.util.*;
import java.sql.*;

public final class total_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/DBconnection.jsp", Long.valueOf(1768386619785L));
    _jspx_dependants.put("/sessionManager.jsp", Long.valueOf(1768386620471L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(8);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");

String dbUser = (String) session.getAttribute("id");
String jdbcDriver = (String) session.getAttribute("dbName");
String dbPwd = (String) session.getAttribute("password");

if (dbUser == null || jdbcDriver == null || dbPwd == null) {
    response.sendRedirect("login.jsp");
    return;
}

Connection conn = null;

try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    conn = DriverManager.getConnection(jdbcDriver, dbUser, dbPwd);
} catch (Exception e) {
    e.printStackTrace();
}

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

String dbName = (session != null) ? (String) session.getAttribute("dbName") : null;
String id = (session != null) ? (String) session.getAttribute("id") : null;
String password = (session != null) ? (String) session.getAttribute("password") : null;

/* out.println(password);
out.println(dbName);
out.println(id);
out.println(password); */

String idSortation = (session != null) ? (String) session.getAttribute("idSortation") : null; if (id == null || dbName == null) {
	response.sendRedirect("login.jsp");
	return;
}

jdbcDriver = dbName;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>에스팜</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"record/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"wrap\" class=\"sales-wrap\">\r\n");
      out.write("		<header>\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("		</header>\r\n");
      out.write("		<section id=\"section\" class=\"sales-section\">\r\n");
      out.write("			<h1>매출</h1>\r\n");
      out.write("			<div class=\"salesfilter\">\r\n");
      out.write("				<div class=\"datePicker\">\r\n");
      out.write("					결재일 : <input type=\"date\" class=\"endSales\"> ~ <input\r\n");
      out.write("						type=\"date\" class=\"startSales\"> <input\r\n");
      out.write("						class=\"toggleSwitch\" type=\"checkbox\" checked>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"dateBtn\">\r\n");
      out.write("					<input type=\"button\" class=\"dateBtnfilter week\" value=\"1주일\">\r\n");
      out.write("					<input type=\"button\" class=\"dateBtnfilter month\" value=\"1개월\">\r\n");
      out.write("					<input type=\"button\" class=\"dateBtnfilter 3month\" value=\"3개월\">\r\n");
      out.write("					<input type=\"button\" class=\"dateBtnfilter 6month\" value=\"6개월\">\r\n");
      out.write("					<input type=\"button\" class=\"dateBtnfilter 1year\" value=\"1년\">\r\n");
      out.write("					<div class=\"medicineBorder\">\r\n");
      out.write("						<input type=\"text\" class=\"medicineTotal\" placeholder=\"제품명 입력\">\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<button type=\"button\" class=\"buyingTotal\">사입가 통합</button>\r\n");
      out.write("					<button type=\"button\" class=\"excelDownload\">Excel 다운로드</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"tableWrapper\">\r\n");
      out.write("				<table class=\"salesTable\">\r\n");
      out.write("					<thead>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th>날짜</th>\r\n");
      out.write("							<th>판매액</th>\r\n");
      out.write("							<th>사입가</th>\r\n");
      out.write("							<th>마진</th>\r\n");
      out.write("							<th>마진률</th>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</thead>\r\n");
      out.write("					<tbody class=\"totalSales\">\r\n");
      out.write("\r\n");
      out.write("					</tbody>\r\n");
      out.write("				</table>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"detailModal\" class=\"modal-backdrop\">\r\n");
      out.write("		<div class=\"modal\">\r\n");
      out.write("			<div class=\"modal-header\">\r\n");
      out.write("				<div class=\"modal-title\">\r\n");
      out.write("					<strong>상세 내역</strong> <span class=\"modal-day\"></span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<button type=\"button\" class=\"modal-close\" aria-label=\"닫기\">✕</button>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"modal-body modal-flex\">\r\n");
      out.write("				<ul id=\"dayList\" class=\"day-list\"></ul>\r\n");
      out.write("				<div class=\"modal-right\">\r\n");
      out.write("					<table class=\"flaTable\">\r\n");
      out.write("						<colgroup>\r\n");
      out.write("							<col width=\"30%\">\r\n");
      out.write("							<col width=\"20%\">\r\n");
      out.write("							<col width=\"20%\">\r\n");
      out.write("							<col width=\"20%\">\r\n");
      out.write("							<col width=\"10%\">\r\n");
      out.write("						</colgroup>\r\n");
      out.write("						<thead>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<th>제품 이름</th>\r\n");
      out.write("								<th>사입가</th>\r\n");
      out.write("								<th>단가</th>\r\n");
      out.write("								<th>마진</th>\r\n");
      out.write("								<th>마진률</th>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</thead>\r\n");
      out.write("					</table>\r\n");
      out.write("					<div class=\"tbody-wrap\">\r\n");
      out.write("						<table class=\"fotaTable\">\r\n");
      out.write("							<colgroup>\r\n");
      out.write("								<col width=\"30%\">\r\n");
      out.write("								<col width=\"20%\">\r\n");
      out.write("								<col width=\"20%\">\r\n");
      out.write("								<col width=\"20%\">\r\n");
      out.write("								<col width=\"10%\">\r\n");
      out.write("							</colgroup>\r\n");
      out.write("							<tbody id=\"detailTbody\"></tbody>\r\n");
      out.write("						</table>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"modal-footer\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"buyingList\">\r\n");
      out.write("	<div class=\"buying-header-bar\"></div>\r\n");
      out.write("		<div class=\"totalTitle\">사입가 총 합계</div>\r\n");
      out.write("		<div class=\"totalPrice\"></div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<script src=\"jquery-3.7.1.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js\"></script>\r\n");
      out.write("	<script src=\"script.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("	function loadDetailsDaily(saleDate, tbodySelector){\r\n");
      out.write("		  $.ajax({\r\n");
      out.write("		    url: 'salesDetails.jsp',\r\n");
      out.write("		    method: 'GET',\r\n");
      out.write("		    data: { saleDate: saleDate },   // ✅ day → saleDate 로 통일\r\n");
      out.write("		    success: function(res){\r\n");
      out.write("		      var data = (typeof res === 'string') ? JSON.parse(res) : res;\r\n");
      out.write("		      if (data.error){ alert(data.error); return; }\r\n");
      out.write("		      renderDetailRows(data.rows || [], tbodySelector);\r\n");
      out.write("		    },\r\n");
      out.write("		    error: function(xhr){ alert('상세 로드 실패: ' + xhr.status); }\r\n");
      out.write("		  });\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("	// 월 상세 (YYYY-MM)\r\n");
      out.write("	function loadDetailsMonthly(month, tbodySelector){\r\n");
      out.write("	  $.ajax({\r\n");
      out.write("	    url: 'salesDetailsMonthly.jsp',\r\n");
      out.write("	    method: 'GET',\r\n");
      out.write("	    data: { month: month },\r\n");
      out.write("	    success: function(data){\r\n");
      out.write("	    	if (data.error){ alert(data.error); return; }\r\n");
      out.write("	    	renderDetailRows(data.rows || [], tbodySelector);\r\n");
      out.write("	    },\r\n");
      out.write("	    error: function(xhr){ alert('월 상세 로드 실패: ' + xhr.status); }\r\n");
      out.write("	  });\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function renderDetailRows(rows, tbodySelector){\r\n");
      out.write("		  var $tbody = $(tbodySelector || '#detailTbody');\r\n");
      out.write("		  $tbody.empty();\r\n");
      out.write("\r\n");
      out.write("		  if (!rows || rows.length === 0){\r\n");
      out.write("		    $tbody.html('<tr><td colspan=\"5\">데이터 없음</td></tr>');\r\n");
      out.write("		    return;\r\n");
      out.write("		  }\r\n");
      out.write("\r\n");
      out.write("		  rows.forEach(function(r){\r\n");
      out.write("		    var marginRateStr = (r.marginRate != null) ? r.marginRate + '%' : '';\r\n");
      out.write("		    var tr =\r\n");
      out.write("		      '<tr>' +\r\n");
      out.write("		        '<td>'+escapeHtml(r.medicineName || '')+'</td>' +\r\n");
      out.write("		        '<td style=\"text-align:right\">'+fmtMoney(r.buyingPrice)+'</td>' +\r\n");
      out.write("		        '<td style=\"text-align:right\">'+fmtMoney(r.price)+'</td>' +\r\n");
      out.write("		        '<td style=\"text-align:right\">'+fmtMoney(r.margin)+'</td>' +\r\n");
      out.write("		        '<td style=\"text-align:right\">'+marginRateStr+'</td>' +\r\n");
      out.write("		      '</tr>';\r\n");
      out.write("		    $tbody.append(tr);\r\n");
      out.write("		  });\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function fmtMoney(v){ \r\n");
      out.write("		  if (v == null) return '0';\r\n");
      out.write("		  return Number(v).toLocaleString(); \r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function escapeHtml(s){\r\n");
      out.write("		  return String(s).replace(/[&<>\"']/g, function(m){\r\n");
      out.write("		    return ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',\"'\":'&#39;'}[m]);\r\n");
      out.write("		  });\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	function loadDates(){\r\n");
      out.write("		  $.ajax({\r\n");
      out.write("		    url: 'salesDetailsMonthly.jsp',\r\n");
      out.write("		    method: 'GET',\r\n");
      out.write("		    dataType: 'json',\r\n");
      out.write("		    data: { month: \"2025-03\" },  // 원하는 월을 넘김\r\n");
      out.write("		    success: function(res){\r\n");
      out.write("		    	  try {\r\n");
      out.write("		    	    var data = (typeof res === 'string') ? JSON.parse(res) : res;\r\n");
      out.write("		    	    if(data.error){\r\n");
      out.write("		    	      alert(data.error);\r\n");
      out.write("		    	      return;\r\n");
      out.write("		    	    }\r\n");
      out.write("		    	    // 정상 처리\r\n");
      out.write("		    	  } catch(e){\r\n");
      out.write("		    	    console.error(\"JSON 파싱 오류:\", res);\r\n");
      out.write("		    	    alert(\"데이터 오류 발생\");\r\n");
      out.write("		    	  }\r\n");
      out.write("		    	},\r\n");
      out.write("		    error: function(xhr){ alert('날짜 목록 로드 실패: ' + xhr.status); }\r\n");
      out.write("		  });\r\n");
      out.write("		}\r\n");
      out.write("		// 헬퍼\r\n");
      out.write("		function fmtMoney(v){ return Number(v||0).toLocaleString(); }\r\n");
      out.write("	// 모달 닫기\r\n");
      out.write("	function closeDetailModal(){\r\n");
      out.write("	  $('#detailModal').fadeOut(120, function(){\r\n");
      out.write("	    $('#detailTbody').empty();\r\n");
      out.write("	    $('.modal-day').text('');\r\n");
      out.write("	  });\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	// 닫기 이벤트 (X 버튼/하단 버튼/배경 클릭/Esc)\r\n");
      out.write("	$(\"#detailModal .modal\").on('click', '.modal-close', function(){ closeDetailModal(); });\r\n");
      out.write("	$(\"#detailModal .modal\").on('mousedown', '#detailModal', function(e){\r\n");
      out.write("	  if (e.target === this) closeDetailModal();\r\n");
      out.write("	});\r\n");
      out.write("	$(document).on('keydown', function(e){\r\n");
      out.write("	  if (e.key === 'Escape' || e.keyCode === 27){\r\n");
      out.write("		  $(\"#detailModal\").hide();\r\n");
      out.write("	  }\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	// ===== 4) 헬퍼 =====\r\n");
      out.write("	function fmtMoney(v){ var n = Number(v||0); return n.toLocaleString(); }\r\n");
      out.write("	function escapeHtml(s){\r\n");
      out.write("	  return String(s).replace(/[&<>\"']/g, function(m){ return ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',\"'\":'&#39;'}[m]); });\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	// ===== 5) 페이지 로드시 날짜 목록 채우기 =====\r\n");
      out.write("	loadDates();\r\n");
      out.write("	\r\n");
      out.write("	$(\"#wrap #section .salesfilter .dateBtn .medicineBorder .medicineTotal\").on(\"click\", function(){\r\n");
      out.write("		$(this).select();\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	//사입가 총합계\r\n");
      out.write("	$(\".buyingTotal\").on(\"click\", function(){\r\n");
      out.write("		if($(\".buyingList\").is(\":visible\")){\r\n");
      out.write("			$(\".buyingList\").hide();\r\n");
      out.write("		}else{\r\n");
      out.write("		    $.ajax({\r\n");
      out.write("		        url: \"sumBuyingPrice.jsp\",   // DB 합계 구하는 JSP\r\n");
      out.write("		        method: \"POST\",\r\n");
      out.write("		        dataType: \"json\",\r\n");
      out.write("		        success: function (response) {\r\n");
      out.write("		            if (response && response.totalSum !== undefined) {\r\n");
      out.write("		                // 숫자를 3자리마다 콤마 찍어서 표시\r\n");
      out.write("		                $(\".buyingList .totalPrice\").text(\r\n");
      out.write("		                    Number(response.totalSum).toLocaleString() + \" 원\"\r\n");
      out.write("		                );\r\n");
      out.write("		            } else {\r\n");
      out.write("		                $(\".buyingList .totalPrice\").text(\"데이터 없음\");\r\n");
      out.write("		            }\r\n");
      out.write("		        },\r\n");
      out.write("		        error: function (xhr, status, error) {\r\n");
      out.write("		            console.error(\"합계 불러오기 오류:\", error);\r\n");
      out.write("		            $(\".buyingList .totalPrice\").text(\"오류 발생\");\r\n");
      out.write("		        }\r\n");
      out.write("		    });\r\n");
      out.write("		    $(\".buyingList\").show();\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("	$(\"#wrap\").on('dblclick', '.salesTable .totalSales tr', function(){\r\n");
      out.write("		//월별인 경우\r\n");
      out.write("		var checkToggle = $(\".toggleSwitch\").is(\":checked\");\r\n");
      out.write("		if(checkToggle == true){\r\n");
      out.write("			var saleDate = $(this).find(\"td:eq(0)\").text().substr(0,7);\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type: \"POST\",\r\n");
      out.write("				url: \"salesDetails.jsp\",\r\n");
      out.write("				data: {\r\n");
      out.write("				 	saleDate: saleDate // 날짜를 전송!\r\n");
      out.write("				},\r\n");
      out.write("				success: function (response) {\r\n");
      out.write("					$(\"#dayList\").html(response);\r\n");
      out.write("					$(\"#detailModal\").show();\r\n");
      out.write("				},\r\n");
      out.write("				error: function (xhr) {\r\n");
      out.write("				    console.error(\"AJAX 오류:\", xhr.status);\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		}\r\n");
      out.write("		//일별인 경우\r\n");
      out.write("		if(checkToggle == false){\r\n");
      out.write("			var saleDate = $(this).find(\"td:eq(5)\").text().trim();\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type: \"POST\",\r\n");
      out.write("				url: \"daysDetails.jsp\",\r\n");
      out.write("				data: {\r\n");
      out.write("				 	saleDate: saleDate // 날짜를 전송!\r\n");
      out.write("				},\r\n");
      out.write("				success: function (response) {\r\n");
      out.write("					$(\".fotaTable #detailTbody\").html(response);\r\n");
      out.write("					$(\"#detailModal\").show();\r\n");
      out.write("				},\r\n");
      out.write("				error: function (xhr) {\r\n");
      out.write("				    console.error(\"AJAX 오류:\", xhr.status);\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	$(\"#dayList\").on(\"click\", \".salesCheck\", function(){\r\n");
      out.write("		var detailDate = $(this).text();\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type: \"POST\",\r\n");
      out.write("			url: \"salesRight.jsp\",\r\n");
      out.write("			data: {\r\n");
      out.write("				detailDate: detailDate // 날짜를 전송!\r\n");
      out.write("			},\r\n");
      out.write("			success: function (response) {\r\n");
      out.write("				$(\".fotaTable #detailTbody\").html(response);\r\n");
      out.write("			},\r\n");
      out.write("			error: function (xhr) {\r\n");
      out.write("			    console.error(\"AJAX 오류:\", xhr.status);\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("	$(document).on(\"click\", \".salesCheck\", function () {\r\n");
      out.write("	    // 기존 선택 해제\r\n");
      out.write("	    $(\".salesCheck\").removeClass(\"active\");\r\n");
      out.write("	    // 새로 선택\r\n");
      out.write("	    $(this).addClass(\"active\");\r\n");
      out.write("\r\n");
      out.write("	    // 여기서 클릭 이벤트 처리 (예: ajax 호출)\r\n");
      out.write("	    // doSomething($(this).text());\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	// 방향키로 이동\r\n");
      out.write("	$(document).on(\"keydown\", function (e) {\r\n");
      out.write("	    let $current = $(\".salesCheck.active\");\r\n");
      out.write("\r\n");
      out.write("	    if ($current.length === 0) return; // 아직 클릭한 게 없으면 무시\r\n");
      out.write("\r\n");
      out.write("	    if (e.key === \"ArrowUp\") {\r\n");
      out.write("	        let $prev = $current.prev(\".salesCheck\");\r\n");
      out.write("	        if ($prev.length) {\r\n");
      out.write("	            $current.removeClass(\"active\");\r\n");
      out.write("	            $prev.addClass(\"active\").trigger(\"click\");\r\n");
      out.write("	        }\r\n");
      out.write("	        e.preventDefault();\r\n");
      out.write("	    }\r\n");
      out.write("\r\n");
      out.write("	    if (e.key === \"ArrowDown\") {\r\n");
      out.write("	        let $next = $current.next(\".salesCheck\");\r\n");
      out.write("	        if ($next.length) {\r\n");
      out.write("	            $current.removeClass(\"active\");\r\n");
      out.write("	            $next.addClass(\"active\").trigger(\"click\");\r\n");
      out.write("	        }\r\n");
      out.write("	        e.preventDefault();\r\n");
      out.write("	    }\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	$(document).on(\"keydown\", function(e){\r\n");
      out.write("		if((e.key === \"Escape\" || e.keyCode === 27)){\r\n");
      out.write("			e.preventDefault();\r\n");
      out.write("			if($(\".salesDetail\").is(\":visible\")){\r\n");
      out.write("				$(\".salesDetail\").hide();\r\n");
      out.write("			}\r\n");
      out.write("			if($(\".buyingList\").is(\":visible\")){\r\n");
      out.write("			    $(\".buyingList\").hide();\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("	//짝홀수 tr 색상구분\r\n");
      out.write("	function classification(){\r\n");
      out.write("		var $trClassfication = $(\"#wrap #section\").find(\".salesTable tbody tr:visible\");\r\n");
      out.write("		$trClassfication.each(function(index){\r\n");
      out.write("			if(index % 2 === 0){\r\n");
      out.write("				$(this).css(\"background-color\", \"#ddd\");\r\n");
      out.write("			}else{\r\n");
      out.write("				$(this).css(\"background-color\", \"#bbb\");\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		$(\"#dayList\").empty();\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	//토글 변함에 따라 표시값도 변화\r\n");
      out.write("	function applyView() {\r\n");
      out.write("		const grouped = $(\".toggleSwitch\").is(\":checked\");\r\n");
      out.write("		$(\".glanceSummary\").toggle(!grouped);\r\n");
      out.write("		$(\".group-summary\").toggle(grouped);\r\n");
      out.write("		classification();\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	//클릭한 날짜 변수 값에 따라 필터 날짜 변환\r\n");
      out.write("	function getDateRangeByValue(valueText){\r\n");
      out.write("		let months = 0, days = 0;\r\n");
      out.write("		if (valueText.includes(\"1주일\")) days = 7;\r\n");
      out.write("		else if (valueText.includes(\"1개월\")) months = 1;\r\n");
      out.write("		else if (valueText.includes(\"3개월\")) months = 3;\r\n");
      out.write("		else if (valueText.includes(\"6개월\")) months = 6;\r\n");
      out.write("		else if (valueText.includes(\"1년\")) months = 12;\r\n");
      out.write("		let endDate = new Date();\r\n");
      out.write("		let startDate = new Date();\r\n");
      out.write("		if (months > 0) startDate.setMonth(startDate.getMonth() - months);\r\n");
      out.write("		else if (days > 0) startDate.setDate(startDate.getDate() - days);\r\n");
      out.write("		return {\r\n");
      out.write("			start: startDate.toISOString().split(\"T\")[0],\r\n");
      out.write("			end: endDate.toISOString().split(\"T\")[0],\r\n");
      out.write("			months: months\r\n");
      out.write("		};\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	//검색한 의약품 이름에 따라 토글 사용방식 변환\r\n");
      out.write("	function fetchData(opts){\r\n");
      out.write("		const isGrouped = $(\".toggleSwitch\").is(\":checked\") ? \"1\" : \"0\";\r\n");
      out.write("		const medicine = $(\".medicineTotal\").val().trim();\r\n");
      out.write("		const data = {\r\n");
      out.write("			startDate: opts.startDate,\r\n");
      out.write("			endDate: opts.endDate,\r\n");
      out.write("			checkedState: isGrouped,\r\n");
      out.write("			filterValue: opts.months || 0\r\n");
      out.write("		};\r\n");
      out.write("		if (medicine !== \"\") {\r\n");
      out.write("			data.medicineTotal = medicine;\r\n");
      out.write("			$.post(\"filterMedicine.jsp\", data, function(resp){\r\n");
      out.write("				$(\".totalSales\").html(resp);\r\n");
      out.write("				applyView();\r\n");
      out.write("			});\r\n");
      out.write("		} else {\r\n");
      out.write("			$.post(\"filterSales.jsp\", data, function(resp){\r\n");
      out.write("				$(\".totalSales\").html(resp);\r\n");
      out.write("				applyView();\r\n");
      out.write("			});\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	$(\".medicineTotal\").on(\"keydown\", function(e){\r\n");
      out.write("		if(e.key !== \"Enter\") return;\r\n");
      out.write("		e.preventDefault();\r\n");
      out.write("		const selected = $(\".filterSelect\").val() || \"1개월\";\r\n");
      out.write("		const range = getDateRangeByValue(selected);\r\n");
      out.write("		$(\".startSales\").val(range.start);\r\n");
      out.write("		$(\".endSales\").val(range.end);\r\n");
      out.write("		fetchData({startDate: range.start, endDate: range.end, months: range.months});\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	$(\".dateBtnfilter\").on(\"click\", function(){\r\n");
      out.write("		$(\".filterSelect\").removeClass(\"filterSelect\");\r\n");
      out.write("		$(this).addClass(\"filterSelect\");\r\n");
      out.write("		const valueText = $(this).val();\r\n");
      out.write("		const range = getDateRangeByValue(valueText);\r\n");
      out.write("		$(\".startSales\").val(range.start);\r\n");
      out.write("		$(\".endSales\").val(range.end);\r\n");
      out.write("		fetchData({startDate: range.start, endDate: range.end, months: range.months});\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	$(\".startSales, .endSales\").on(\"change\", function(){\r\n");
      out.write("		const start = $(\".startSales\").val();\r\n");
      out.write("		const end = $(\".endSales\").val();\r\n");
      out.write("		if(start && end) fetchData({startDate: start, endDate: end, months: 0});\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	$(\".toggleSwitch\").on(\"change\", function(){\r\n");
      out.write("		const start = $(\".startSales\").val();\r\n");
      out.write("		const end = $(\".endSales\").val();\r\n");
      out.write("		if (start && end) fetchData({startDate: start, endDate: end, months: 0});\r\n");
      out.write("		$(\".filterSelect\").click();\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	$(\".excelDownload\").on(\"click\", function(){\r\n");
      out.write("		var table = document.querySelector('.salesTable');\r\n");
      out.write("		var workbook = XLSX.utils.table_to_book(table, { sheet: \"Sheet1\" });\r\n");
      out.write("		let today = new Date();\r\n");
      out.write("		let year = today.getFullYear();\r\n");
      out.write("		let month = today.getMonth() + 1;\r\n");
      out.write("		let date = today.getDate();\r\n");
      out.write("		XLSX.writeFile(workbook, `");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${year}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('.');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${month}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('.');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${date}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("_판매매출현황.xlsx`);\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	$(\".salesTable\").on(\"mouseover\", \".totalSales tr\", function(){\r\n");
      out.write("		$(\".salesTable tr\").removeClass(\"detailTR\");\r\n");
      out.write("		$(this).addClass(\"detailTR\");\r\n");
      out.write("	}).on(\"mouseout\", function(){\r\n");
      out.write("		$(\".salesTable .totalSales tr\").removeClass(\"detailTR\");\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	let today = new Date();\r\n");
      out.write("	$(\".startSales, .endSales\").val(today.toISOString().substring(0, 10));\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
